### ISSUE TITLE
Can't spin up Refinery instance on AWS

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1003]
**This is prohibiting https://github.com/parklab/refinery-platform/pull/993 from being tested**

Commit: 8120b511d93ca22e250ec9b2017354666bc72398

AWS Permissions: 
```
AmazonRDSFullAccess
AmazonEC2FullAccess
AmazonS3FullAccess
AmazonSESFullAccess
```

### Steps to reproduce
- Follow instructions from: https://github.com/parklab/refinery-platform/wiki/AWS-installation

### Observed behavior
- The step: `Spin up an RDS instance:` fails for me with this error.

```
A client error (AccessDenied) occurred when calling the CreateDBInstance operation: User: arn:aws:iam::643366669028:user/scott is not authorized to perform: rds:CreateDBInstance on resource: arn:aws:rds:us-east-1:643366669028:db:rds-refinery
```
### Expected behavior
- For this not to fail

**Comment by drj11** [comment]
thanks for testing! I haven't tried minimising by IAM account access, so on the one hand I'm not surprised that it doesn't work. On the other hand, that list of permissions looks very plausible.

**Comment by drj11** [comment]
Thanks for testing!

I think this might actually be that everyone needs to set a different name for their RDS (each RDS running in the AWS account needs a separate name). So I've changed the instructions; they now say to pick an `RDS_NAME` (this was possible before, just not so clearly required).

**Comment by scottx611x** [comment]
Closing as this was simply an issue with my env vars and `boto` dot-file being configured for another AWS account.
