### ISSUE TITLE
Combine CloudFormation stacks into a single template

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1005]
Currently, we have separate stacks for the web application (EC2), data volume (EBS) and database (RDS). User is responsible for launching them in order, monitoring instantiation and providing appropriate values to subsequent stages. This is not a best practice.

Single stack would simplify provisioning and allow us to keep the database and data files in snapshots: https://blogs.aws.amazon.com/application-management/post/Tx2W35XGG70IIQI/Delete-Your-Stacks-But-Keep-Your-Data

also, set stack policy that prevents delete to PROD_DATABASE resource: http://geekery.freecharge.in/2015/11/29/protection-of-aws-cloudformation-resources/

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html
http://stackoverflow.com/questions/32255309/how-do-i-restore-rds-snapshot-into-a-cloudformation

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>

**Comment by drj11** [comment]
In favour in principle. I think it's a good idea, but it's no free lunch.

There are still 2 different circumstances in which we're bring up a stack:
initial: The very first time, no populated data.
iterative: stack is destroyed/switch off and then, later, recreated with hopefully the same data.

Moving to one stack doesn't change that. We'll need one cloudformation description for the initial case (that has *ab initio* creation of RDS and EBS) and a different description for the iterative case (that create RDS and EBS from snapshots).

In the iterative case, I'm not sure how the next stack creation picks up the snapshot from the previous stack delete (it will presumably change each time the stack is deleted and recreated). It's clearly possible, but not necessarily straightforward.

**Comment by drj11** [comment]
Another blogpost with some experience and advice: http://blog.jasonantman.com/2014/12/aws-cloudformation-and-rds-snapshots/

**Comment by hackdna** [comment]
Single stack implementation is not a silver bullet but it should allow bringing up the application using a single command (as opposed to the existing sequence of three which needs to be choreographed) and it would specify explicit protections on resources. The issue of finding the existing snapshots is already solved by using config files but the use would be simplified in case of single stack.

**Comment by drj11** [comment]
when shutting down a stack, something will need to put the new snapshots in the config. I don't think CloudFormation delete policies can do that. AWS lambda?

Anyway, I think this is getting too bogged down in details. I think what we're aiming for is:

To begin a stack: a single command. I'm convinced that (a python script +) a single cloudformation stack is the way forward for this. (maybe eventually this will be a small web app, like cloudman launcher).

To "suspend" a stack (delete, really); a single command. Not sure on the details, but it may need something special to store snapshot IDs in a config (in S3).

To "resume" a stack: a single command, which will likely take the location of an existing config. It may have a feature to discover suspended stacks and offer to resume them.

If we can achieve that, I don't think it really matters how many stacks we have, whether the instance does resource discovery or whether the stack does. the details will depends on technically what happens to be easiest.

**Comment by ngehlenborg** [comment]
From cloud meeting discussion with @hackdna and @drj11:

1. If there are no snapshot ids in the config, create EBS and RDS.
1. If there are snapshot ids in the config, use those to launch the stack.
  1. For now, users need to get snapshot ids via the AWS console and enter them manually into the config.
  1. In the future, we should store the snapshot ids in an S3 bucket so that no manual intervention is necessary. This the approach that Galaxy Cloudman Cloud Launch is using.

**Comment by ngehlenborg** [comment]
Currently, re-launching the web stack will overwrite the site model information in the database (and reset configured URLs for the instance). Will this continue to be an issue with a single stack?
