### ISSUE TITLE
The "forgot password" button is totally broken

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#1010]
Commit:

https://github.com/parklab/refinery-platform/commit/a78f0d5c70cf2ee1e3404e65de8893bbae1ca615

### Steps to reproduce

From the login page click the "Forgot password" link.

### Observed behavior

Goes to http://dev.genometranslationcommons.org/accounts/password/reset/ which produces a NoReverseMatch error

Screenie from Win Hide who reported the bug:

![img_6081](https://cloud.githubusercontent.com/assets/1215412/14559383/3b8e558c-0300-11e6-923e-d4b45d18ba73.PNG)

### Expected behavior

A nice password reset form?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-deploy-scc-release-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> deploy SCC release on AWS</a>
