### ISSUE TITLE
Easy-to-usify collaboration

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1017]
Commit: df3ad330c524a01a68bd534c610a7347d918cfa5

### Steps to reproduce
1. Go to http://192.168.50.50:8000/collaboration
2. Create a new group
3. Click on the _cog wheel_ next to your name
4. Click on _demote_ or _remove_

### Observed behavior
1. Both clicks open the same dialog.
2. The first popup doesn't have any _X_ button on the top right and closes with an outside click while the second dialog contains an _X_ button and doesn't close with an outside click.
3. The second dialog is not really user-friendly. It only asks the question "Are you the only member or manager left?"

### Expected behavior
1. Both dialogs should behave the same
2. Instead of asking the user whether he / she is the only user it should tell the user that he / she is the only user.
3. Instead of only providing an _Okay_ button the second dialog should include an option to remove the group to save the user another 3 or 4 clicks.
4. The two buttons _demote_ and _remove_ could also be grayed out and disabled in the first place to avoid confusion.

**Comment by flekschas** [comment]
Also, a non-manager still sees the _Pending Invitations_ panel, which is always empty. This should not be shown unless the user is a group manager.

**Comment by flekschas** [comment]
The _plus_ button to add new members is not really apparent. It should be bigger and maybe include a label like _Add person_.

**Comment by flekschas** [comment]
The _members_ and _invitations_ panel could be merged. After sending out an invitation the email could be added as a new _member_ with an label saying that this member hasn't accepted yet. This would solve the issue of needing to design a two column and three column layout for managers and non-managers.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>
