### ISSUE TITLE
IGV launcher has 2 empty entries

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1018]
Commit: df3ad330c524a01a68bd534c610a7347d918cfa5

### Steps to reproduce
1. Go to https://refinery-dev.stemcellcommons.org/data_sets/781dbf25-2ab7-41a9-953c-6bbed44e5c8e/#/files/visualize/
2. Choose _current selection_
3. Click on the drop down list
4. Select the second empty entry
5. click on _launch_

### Observed behavior
1. Looks like this
![bildschirmfoto 2016-04-15 um 12 59 58](https://cloud.githubusercontent.com/assets/932103/14569082/5e065a38-030a-11e6-8a77-3f990c5506ab.png)
2. after click on _lauch_ the two empty options are gone.

### Expected behavior
Either add a label to the drop down menu so that the user knows what this is about or preset one organism.

**Comment by jkmarx** [comment]
Might be a missing label for entries.

**Comment by ngehlenborg** [comment]
It looks like the list of species entries is returned correctly, it must be an issue with filing the dropdown:

![screen shot 2016-04-26 at 5 33 44 pm](https://cloud.githubusercontent.com/assets/1216518/14834930/111d89de-0bd5-11e6-8348-cc666ddeb23f.png)

**Comment by jkmarx** [comment]
We are using https://github.com/angular-ui/ui-select2 . "This directive is now obsolete. A new initiative, more active, and 100% angular is available at https://github.com/angular-ui/ui-select."

**Comment by jkmarx** [comment]
https://github.com/angular-ui/ui-select/wiki/FAQs

**Comment by jkmarx** [comment]
Resolves does not work with and between the commits. Pull request #1059
