### ISSUE TITLE
Provide two button for quick asignment of files to paired input analyses

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1019]
Commit: df3ad330c524a01a68bd534c610a7347d918cfa5
### Steps to reproduce
1. Open your favorite data set
2. Click on Analyze
3. Select a paired-input analysis
### Observed behavior

The user needs to drag and drop files.
### Expected behavior

It would be great to display two buttons, maybe called _tag_ and _control_, where the user can click on to quickly assign a files to either input _tag_ or _control_.

I wouldn't touch the drag-drop  component but just add the two buttons as a short cut.

**Comment by jkmarx** [comment]
Issue no longer applicable with the new data set 2 design. Ref #1267
