### ISSUE TITLE
Progress bar of custom file upload is broken

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1022]
Commit:

### Steps to reproduce
1. Go to https://refinery-dev.stemcellcommons.org/data_set_manager/import/ _step 2_
2. Choose random files
3. Hit _start upload_

### Observed behavior
Nothing happens. Two empty bars pop up and the console says everything is fine but the ui doesn't change:

![broken upload](https://cloud.githubusercontent.com/assets/932103/14570412/1198a450-0312-11e6-8229-86f677bca1e3.gif)

```
angular.js:12722You have successfully uploaded annotation-statistics.sh
angular.js:12722You have successfully uploaded ontology.txt
angular.js:12722You have successfully uploaded tabular test file.txt
angular.js:12722You have successfully uploaded term_usage.txt
angular.js:12722You have successfully uploaded annotation-statistics.sh
angular.js:12722You have successfully uploaded ontology.txt
angular.js:12722You have successfully uploaded tabular test file.txt
angular.js:12722You have successfully uploaded term_usage.txt
angular.js:12722You have successfully uploaded annotation-statistics.sh
angular.js:12722You have successfully uploaded ontology.txt
angular.js:12722You have successfully uploaded tabular test file.txt
angular.js:12722You have successfully uploaded term_usage.txt
```

### Expected behavior
Something should happen.

**Comment by flekschas** [comment]
The API returning a success message but nothing appears in  File store › File store items

**Comment by flekschas** [comment]
Turns out that the actual upload works but there is no user feedback whether it actually finished or not. And uploads are also not stored as File store items...

**Comment by flekschas** [comment]
Somehow something internally is broken and the progress bars are not shown properly anymore. Since most things happen just magically it's really hard to spot the broken piece.

**Comment by jkmarx** [comment]
Nils checkout.

**Comment by hackdna** [comment]
I've just realized that this is probably due to the small size of uploaded files: the progress bars show up but simply disappear too quickly to notice.

**Comment by ngehlenborg** [comment]
Just tested with a couple of larger files (110 KB) on the dev instance: the progress bars are visible for some time but not progress is shown, neither for individual progress bars nor for the overall progress bar (I uploaded about 100 files at once).

**Comment by ngehlenborg** [comment]
I tried it with even larger files (10 to 20 MB each) and still no progress bars:

![screen shot 2016-04-26 at 5 42 10 pm](https://cloud.githubusercontent.com/assets/1216518/14835137/414ebcda-0bd6-11e6-8169-5799166b7bcf.png)

**Comment by hackdna** [comment]
Also, the [upload chunk size is set to 10MB](https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/source/js/data-set-import/settings.js#L8), so no incremental progress will be shown for files smaller than that.

**Comment by ngehlenborg** [comment]
Thanks @hackdna, that's good to know. Testing now with files > 100 MB but I noticed that if I drag and drop the files into the browser it launches the upload immediately which showing a spinner, rather than a progress bar:

![screen shot 2016-04-26 at 5 48 18 pm](https://cloud.githubusercontent.com/assets/1216518/14835341/461f7ece-0bd7-11e6-83f5-1402c3ce9d76.png)

**Comment by ngehlenborg** [comment]
Ok, once all buttons have been activated (after the first upload is complete) I can click start upload, which will upload the files in chunks again but still no progress in the progress bars. 

![screen shot 2016-04-26 at 5 50 24 pm](https://cloud.githubusercontent.com/assets/1216518/14835394/8694a8d0-0bd7-11e6-8e03-e2ff4a55bffd.png)

We will need to investigate why upload is launching immediately and why there are no progress bars.

**Comment by hackdna** [comment]
The first step in the upload process is to calculate md5 for every file which is indicated by the spinner.

**Comment by flekschas** [comment]
It has definitely nothing to do with the file size because I do see a progress bar when uploading something via the test online version. https://blueimp.github.io/jQuery-File-Upload/angularjs.html I've also tested it locally and do see progress bars.

![upload](https://cloud.githubusercontent.com/assets/932103/14956732/40a02314-104f-11e6-94e9-2d08c0b92cfb.gif)
