### ISSUE TITLE
DataSet 2 - Assay Attribute API -- Ranks Initially 0

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1035]
Commit: 83fbabe0373762a5936f1fbe340f1a91de99cdf8

### Steps to reproduce
1. In DataSet 2 browser, select RFC data set. (Any data set in which you're the owner and is fairly new. One where you haven't set the attriubtes)
2. Select Table Utilities Icon
### Observed behavior
<img width="584" alt="screen shot 2016-04-20 at 6 13 24 pm" src="https://cloud.githubusercontent.com/assets/9956764/14692230/d50f0518-0723-11e6-9767-940f91a2563d.png">

From the http://192.168.50.50:8000/api/v1/attributeorder  data set browser, response from solr
```{"meta": {"limit": 1000, "next": null, "offset": 0, "previous": null, "total_count": 20}, "objects": [{"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 125, "is_active": true, "is_exposed": true, "is_facet": false, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/125/", "solr_field": "Group_Name_Comment_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 126, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/126/", "solr_field": "REFINERY_SUBANALYSIS_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 127, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/127/", "solr_field": "REFINERY_WORKFLOW_OUTPUT_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 128, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/128/", "solr_field": "REFINERY_TYPE_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 129, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/129/", "solr_field": "organism_part_Characteristics_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 130, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/130/", "solr_field": "REFINERY_ANALYSIS_UUID_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 131, "is_active": false, "is_exposed": true, "is_facet": true, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/131/", "solr_field": "is_annotation", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 132, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/132/", "solr_field": "disease_Factor_Value_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 133, "is_active": false, "is_exposed": true, "is_facet": false, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/133/", "solr_field": "uuid", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 134, "is_active": false, "is_exposed": true, "is_facet": false, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/134/", "solr_field": "assay_uuid", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 135, "is_active": false, "is_exposed": true, "is_facet": false, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/135/", "solr_field": "study_uuid", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 136, "is_active": false, "is_exposed": true, "is_facet": true, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/136/", "solr_field": "type", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 137, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/137/", "solr_field": "organism_Characteristics_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 138, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/138/", "solr_field": "disease_state_Characteristics_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 139, "is_active": true, "is_exposed": true, "is_facet": true, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/139/", "solr_field": "REFINERY_FILETYPE_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 140, "is_active": true, "is_exposed": true, "is_facet": false, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/140/", "solr_field": "notes_Characteristics_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 141, "is_active": true, "is_exposed": true, "is_facet": false, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/141/", "solr_field": "REFINERY_NAME_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 142, "is_active": true, "is_exposed": true, "is_facet": false, "is_internal": false, "rank": 0, "resource_uri": "/api/v1/attributeorder/142/", "solr_field": "Replicate_Id_Comment_14_7_s", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 143, "is_active": false, "is_exposed": true, "is_facet": false, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/143/", "solr_field": "name", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}, {"assay": "/api/v1/assay/6a0ea6d3-f80a-40a7-9b00-a81d0a071781/", "id": 144, "is_active": false, "is_exposed": true, "is_facet": false, "is_internal": true, "rank": 0, "resource_uri": "/api/v1/attributeorder/144/", "solr_field": "file_uuid", "study": "/api/v1/study/40cec7b3-3c38-47cb-9794-4dd8a0d1670c/"}]}```

### Expected behavior
A default rank should be set or backend algorithm for setting ranks adjusted.

**Comment by ngehlenborg** [comment]
Remove rank numbers and replace with hamburger icon to indicate drag-and-drop support.

**Comment by jkmarx** [comment]
If you're trying to move two columns next to each other, there's no guarantee you can accomplish this easily due to this bug. Also, the attribute order does not match the table column order due to this bug.

**Comment by jkmarx** [comment]
Also change the close button to an okay button.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-upgrade-phase-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Upgrade, Phase 1</a>
