### ISSUE TITLE
Console Error - Missing data-set-ui-node-mapping.html 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1043]
Commit:
0b168c398f51fd5021012e4902926ad054c53076
### Steps to reproduce
1. Open data set explorer for any data set you own
2. Click analyze

### Observed behavior
Console Error
```angular.js:10967 GET http://192.168.50.50:8000/static/partials/data-set-ui-node-mapping.html 404 (NOT FOUND)(anonymous function) @ angular.js:10967r @ angular.js:10760g @ angular.js:10470(anonymous function) @ angular.js:14991r.$eval @ angular.js:16251r.$digest @ angular.js:16069r.$apply @ angular.js:16359g @ angular.js:10791R @ angular.js:10989v.onload @ angular.js:10930```

### Expected behavior
No Console error

**Comment by jkmarx** [comment]
Resolve missing partial. But, then I discovered the dual input workflow drag-drop ui is no longer showing.
<img width="1413" alt="screen shot 2016-04-27 at 9 20 47 am" src="https://cloud.githubusercontent.com/assets/9956764/14853413/771f817c-0c59-11e6-9db1-7aaf213b2af9.png">

**Comment by ngehlenborg** [comment]
Let's create a separate issue if `data-set-ui-node-mapping.html` is no longer missing.
