### ISSUE TITLE
Data Set - Pairs Analysis UI Missing

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1052]
Commit: da1fee049dd1437b2ab21d5be9e26133bdd1ab64

### Steps to reproduce
1. Data Set Browser Locally
2. Click analyze tab
3. Select Test Workflow: SPP Analog

### Observed behavior
<img width="1413" alt="screen shot 2016-04-27 at 9 20 47 am" src="https://cloud.githubusercontent.com/assets/9956764/14854234/e63a99c2-0c5c-11e6-9acb-fce468db0543.png">

### Expected behavior
Drag and drop interface to show

**Comment by jkmarx** [comment]
@ngehlenborg Should this be in Taunton?

**Comment by ngehlenborg** [comment]
See also #1051.

**Comment by ngehlenborg** [comment]
@jkmarx: Did you try to click "New"? Using 842f3ac I get the correct UI after clicking new.

**Comment by jkmarx** [comment]
No, previously it was not required.

**Comment by ngehlenborg** [comment]
It seems that the "Current Mapping" option is not added and selected by default in the dropdown in the "Inputs" section. After adding a new mapping, the dropdown is populated (with "Current Mapping" and all explicitly created mappings). The `noderelationship` API is not queried until after I confirm creation of a new node mapping.
