### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1054]
There is a problem with Grunt that can be solved by updating the npm on the vm to version 3.8.7 (from 2.15.1): http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies

Updating npm requires updating Node.js to v5 in the Puppet manifest: https://github.com/parklab/refinery-platform/blob/develop/deployment/refinery-modules/refinery/manifests/init.pp#L311

It might be worth waiting for v6 RPM to become available:
https://nodejs.org/en/blog/release/v6.0.0/
https://github.com/nodesource/distributions

**Comment by hackdna** [comment]
Need to make sure this also works on AWS.

**Comment by ngehlenborg** [comment]
Works on AWS.

```
octothorpe:deployment nils$ ssh -i xxx ubuntu@ec2-54-83-151-116.compute-1.amazonaws.com
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)

[...]

Last login: Fri Apr 29 12:00:25 2016 from 134.174.140.208
ubuntu@ip-172-31-62-55:~$ npm -v
3.8.6
ubuntu@ip-172-31-62-55:~$ nodejs -v
v6.0.0
ubuntu@ip-172-31-62-55:~$ 
```
