### ISSUE TITLE
IGV session file contains URLs without base URL for local files 

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1056]
Commit: 842f3acd0df75eebdbf4b3ef3cf2a22f0dd6c19e

### Steps to reproduce
1. Select IGV readable files, e.g. from https://github.com/refinery-platform/sample-data/tree/develop/file-type-test in file browser.
1. Open visualization tab, select species, and select "Launch IGV".

### Observed behavior
IGV session file contains incorrect URLs for downloads (`Resource` entries) of files that are stored locally (the base URL of the Refinery instance is missing) and potentially incorrect names for remote resources as well (the full URL is included in the name field):

```
<?xml version="1.0" ?>
<Global genome="hg19" locus="All" version="4">
  <Resources>
    <Resource name="http://www.gehlenborg.com/wp-content/uploads/refinery-data/file-type-test/1_igv_count.igv_11.tdf" path="http://www.gehlenborg.com/wp-content/uploads/refinery-data/file-type-test/1_igv_count.igv_11.tdf"/>
    <Resource name="HMM_ES_K36.bed" path="/media/file_store/11/05/HMM_ES_K36.bed"/>
    <Resource name="Sample Information" path="http://192.168.50.50:8000/media/file_store/09/67/tmprujO_V.txt"/>
  </Resources>
  <HiddenAttributes>
    <Attribute name="DATA FILE"/>
    <Attribute name="Linking_id"/>
    <Attribute name="DATA TYPE"/>
  </HiddenAttributes>
</Global>
```

### Expected behavior
1. Full URLs for file that are local to the Refinery instance, i.e. have been downloaded to the file store.
1. Shorter names for remote files.

**Comment by scottx611x** [comment]
This has been addressed as of commit: f34c5ceea039e8d583c192491f43bee6f8c0506c
