### ISSUE TITLE
Dashboard Preview: Abstract caret misdirection

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1062]
Commit:
561ef26272fb221416e38e5473f1bed7b913601e
### Steps to reproduce
1. On the SCC, preview a file with a long abstract. ex NKX2-1 occupancy in human lung adenocarcinoma cell lines
2. Click to open preview
3. 
![screen shot 2016-04-29 at 11 13 57 am](https://cloud.githubusercontent.com/assets/9956764/14920507/0162ebb4-0dfc-11e6-9853-a7e821e357c7.png)

### Observed behavior
In the Abstract, the carnet is misdirected when expanded.
![screen shot 2016-04-29 at 11 14 03 am](https://cloud.githubusercontent.com/assets/9956764/14920515/07dbbf5c-0dfc-11e6-915d-96f03bf1b099.png)

In the description, there's a hanging caret.
![screen shot 2016-04-29 at 11 24 35 am](https://cloud.githubusercontent.com/assets/9956764/14920766/0260d8fe-0dfd-11e6-901a-a52c291af593.png)

![screen shot 2016-04-29 at 11 22 29 am](https://cloud.githubusercontent.com/assets/9956764/14920725/de099072-0dfc-11e6-83c4-51e68228ef0f.png)

### Expected behavior
Caret should point left when the text is expanded. Carets should only show when needed.

**Comment by jkmarx** [comment]
Not sure if this is a bug or enhancement.

**Comment by flekschas** [comment]
Usability-wise it's a bug but implementation-wise it is expected :). I will look into it.
