### ISSUE TITLE
Analyses Disable Links for Failed/Unknown

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1068]
1. On the dashboard, global analysis popover, and the analyses tab disable links for completed failed or unknown analyses.

## Expected
For complete analyses, links should only be able for successful completed ones.

**Comment by ngehlenborg** [comment]
@jkmarx @flekschas: does this also cover the analysis list included in the dataset preview?

**Comment by jkmarx** [comment]
@ngehlenborg Sorry, dashboard meant dataset preview.
