### ISSUE TITLE
Remove Analysis Email Capabilities

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1069]
### Observed behavior
1.  When an analysis completes, an email should be sent confirming it's completion

### Expected behavior
2. Disable sending email

**Comment by jkmarx** [comment]
Failed emails currently sent: ```[2016-05-04 09:38:10,851: WARNING/Worker-1] MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Refinery] FAILURE: Test workflow: 5 steps without branching
 2016-5-4@9:37:27 (Test workflow: 5 steps without branching)
From: webmaster@localhost
To: admin@example.com
Date: Wed, 04 May 2016 13:38:10 -0000
Message-ID: <20160504133810.21709.67943@refinery>

Dear   (admin),


Unfortunately, your analysis failed.  Please forward this email to your admin at 
webmaster@localhost for further assistance.


Project: Catch-All Project - admin - 
Analysis: Test workflow: 5 steps without branching 2016-5-4@9:37:27
Dataset used: Test 1: Request for Comments (RFC) Test
Workflow used: Test workflow: 5 steps without branching
Start time: Wednesday, 04 May 2016 01:37:28 PM 
End time: Wednesday, 04 May 2016 09:38:04 AM
Duration: 0-4:00 hours

We are looking forward to your next visit.

Refinery - 192.168.50.50:8000
[2016-05-04 09:38:10,853: WARNING/Worker-1] ```

**Comment by jkmarx** [comment]
@ngehlenborg This doesn't include the url link to the failed analysis.

**Comment by ngehlenborg** [comment]
Good. Can we add the analysis uuid?

**Comment by jkmarx** [comment]
```[2016-05-04 14:13:22,589: WARNING/Worker-1] MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Refinery] SUCCESS: Test workflow: 5 steps without branching
 2016-5-4@14:12:24 (Test workflow: 5 steps without branching)
From: webmaster@localhost
To: admin@example.com
Date: Wed, 04 May 2016 18:13:22 -0000
Message-ID: <20160504181322.11922.85236@refinery>

Dear   (admin),


Your analysis successfully completed.  View your results here: http://192.168.50.50:8000/analyses/e6f5c3b4-0594-49f8-b03f-eadc3b581ded/


Project: Catch-All Project - admin - 
Analysis: Test workflow: 5 steps without branching 2016-5-4@14:12:24
Dataset used: Test 1: Request for Comments (RFC) Test
Workflow used: Test workflow: 5 steps without branching
Start time: Wednesday, 04 May 2016 06:12:26 PM 
End time: Wednesday, 04 May 2016 02:13:16 PM
Duration: 0-4:00 hours

We are looking forward to your next visit.

Refinery - 192.168.50.50:8000
[2016-05-04 14:13:22,595: WARNING/Worker-1] ```

The url for successful analysis are problematic.

Should be http://192.168.50.50:8000/data_sets/855f15f7-a385-4e50-bcf2-aeb575748c20/analysis/e6f5c3b4-0594-49f8-b03f-eadc3b581ded/#/files/browse

**Comment by ngehlenborg** [comment]
What do you mean by problematic? We need to update the URL that is pasted into the email (also the one at the bottom of the message, both for successful and failed analyses).

**Comment by jkmarx** [comment]
The current url leads to here.

<img width="1413" alt="screen shot 2016-05-04 at 2 29 00 pm" src="https://cloud.githubusercontent.com/assets/9956764/15024849/a4064382-1204-11e6-9303-53b395264ea0.png">
