### ISSUE TITLE
allow taking ownership of public data sets via file re-import

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1072]
Users should be able to easily import the ISA-Tab or tab-delimited data associated with a public  data set into their own space for analyses by clicking a button in the data set browser or preview.

**Comment by scottx611x** [comment]
Useful link: https://stackoverflow.com/questions/4733609/how-do-i-clone-a-django-model-instance-object-and-save-it-to-the-database

**Comment by scottx611x** [comment]
@ngehlenborg I know there was a laundry list of steps that you mentioned for this to be achieved. Could you list them here when you have time?

**Comment by scottx611x** [comment]
- [ ] Identify zipfile (look at details tab metadata field)
- [ ] Provide button that gets this url to zipfile and provides the same functionality as the dataset import url option. 
- [ ] Make sure user's  only see this option if the dataset `is_public` and they don't already own it
