### ISSUE TITLE
Analysis Launch/Completion Emails Not Sent

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1076]
Commit: c798117748aaf0ee5c71ce6c035ff1369bb5eefd

### Steps to reproduce
1. Launch an analysis
2. Check refinery.log for emails related to launching and completion

### Observed behavior
No emails

### Expected behavior
Emails in the log

**Comment by hackdna** [comment]
Could you post the result of the following:
```python
>>> from django.conf import settings
>>> settings.EMAIL_BACKEND
```

**Comment by jkmarx** [comment]
<img width="721" alt="screen shot 2016-05-03 at 2 27 47 pm" src="https://cloud.githubusercontent.com/assets/9956764/14993940/43f0b9a6-113b-11e6-8336-cf22053ff626.png">

**Comment by ngehlenborg** [comment]
Important to note: registration as well as collaboration invites are getting "sent", correct @jkmarx?

**Comment by jkmarx** [comment]
@ngehlenborg Yes, collaboration invites are sent correctly.

**Comment by hackdna** [comment]
By sent correctly you mean they are logged in refinery.log?

**Comment by jkmarx** [comment]
@hackdna Yes

**Comment by hackdna** [comment]
Btw, did you run the above commands in the shell or in the python interpreter?

**Comment by jkmarx** [comment]
shell

**Comment by jkmarx** [comment]
```>>> from django.conf import settings
>>> settings.EMAIL_BACKEND
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting EMAIL_BACKEND, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.```

**Comment by hackdna** [comment]
I see. This is Python code that you need to run from the refinery-platform virtual environment.

**Comment by jkmarx** [comment]
In the send_email model file: First issue, missing a parenthesis for a method call. Next, ```[2016-05-04 08:52:05,240: ERROR/MainProcess] Task analysis_manager.tasks.run_analysis[e86c3bde-873e-43ba-af6b-73b717d780cb] raised unexpected: TypeError("can't subtract offset-naive and offset-aware datetimes",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/refinery/analysis_manager/tasks.py", line 201, in run_analysis
    analysis.send_email()
  File "/vagrant/refinery/core/models.py", line 1158, in send_email
    duration = end - start
TypeError: can't subtract offset-naive and offset-aware datetimes```

**Comment by jkmarx** [comment]
http://stackoverflow.com/questions/796008/cant-subtract-offset-naive-and-offset-aware-datetimes

**Comment by hackdna** [comment]
Looks like this has to do with time zone support in Django:
https://docs.djangoproject.com/en/1.7/topics/i18n/timezones/#troubleshooting http://stackoverflow.com/questions/10594314/cant-subtract-datetime-and-timestamp-in-django
