### ISSUE TITLE
remote data automatically imported into Refinery even when not requested

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1079]
Commit: 0ed3ddfa44c853ede02372406c390e0d490e6099

### Steps to reproduce
1. See #1077. 
2. Do not check "Data file permanent".

### Observed behavior
1. See #1077.

### Expected behavior
1. Remote files should not be imported.

**Comment by flekschas** [comment]
Look:
- https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/single_file_column_parser.py
- https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/single_file_column_parser.py#L185

**Comment by scottx611x** [comment]
> Note:  The `permanent` argument is never actually used here: https://github.com/parklab/refinery-platform/blob/develop/refinery/data_set_manager/single_file_column_parser.py#L185

See: 
* https://github.com/parklab/refinery-platform/blob/develop/refinery/file_store/tasks.py#L51
* https://github.com/parklab/refinery-platform/blob/develop/refinery/file_store/tasks.py#L198

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>
