### ISSUE TITLE
data set list on top of data set list filter when data set summary is open

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1089]
Commit: acda478d8d2670c521b95cbd635bb483e08111bd

### Steps to reproduce
1. Open summary for data set at top of the list.
2. Open data set list filter.

### Observed behavior
![screen shot 2016-05-05 at 2 28 17 pm](https://cloud.githubusercontent.com/assets/1216518/15053365/45891efc-12d0-11e6-8660-6831040158aa.png)

### Expected behavior
1. data set list filter on top of data set list

**Comment by flekschas** [comment]
Fixed via 011208f83b9d13967943ab1dea2000a2c0cee9d9
