### ISSUE TITLE
Make all datetimes time zone aware

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1090]
The [fix](https://github.com/parklab/refinery-platform/pull/1084) for [`TypeError: can't subtract offset-naive and offset-aware datetimes`](https://github.com/parklab/refinery-platform/issues/1076#issuecomment-216853911) doesn't address the root cause which is "[to change your code to use an aware datetime](https://docs.djangoproject.com/en/1.7/topics/i18n/timezones/#troubleshooting)".

It looks like we need to replace the call to `datetime.now()` at https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L931 with a call to [`django.utils.timezone.now()`](https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.timezone.now).

In addition, we should replace other instances of `datetime.now()` as well.

**Comment by jkmarx** [comment]
datetime.now() returns local time
timezone.now() returns current time in UTC
timezone.localtime(timezone.now()) returns local time
