### ISSUE TITLE
Analysis monitor throws error when no object is returned by the API

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1097]
Commit: 336b2be21635b8735b7f5c2f0f3f6a384f80fac4

### Steps to reproduce
1. Open a data set in a file browser and go to the Analyses tab

### Observed behavior
When the API endpoint http://192.168.50.50:8000/api/v1/analysis/?format=json&limit=1&order_by=-time_start&uuid=UUID returns the following:
```
{"meta": {"limit": 1, "next": null, "offset": 0, "previous": null, "total_count": 0}, "objects": []}
```
the following error is thrown:
```
angular.js:12722 TypeError: Cannot read property 'status' of undefined
    at analysis-monitor.js:397
    at angular.js:14991
    at r.$eval (angular.js:16251)
    at r.$digest (angular.js:16069)
    at r.$apply (angular.js:16359)
    at g (angular.js:10791)
    at R (angular.js:10989)
    at XMLHttpRequest.v.onload (angular.js:10930)
```
Because the monitor assumes that always one object is returned.

### Expected behavior
The analysis monitor should handle cases when no object is returned.

**Comment by flekschas** [comment]
This seems to be the case for lost analyses

**Comment by jkmarx** [comment]
@flekschas Please give more instructions on how to recreate this console error.

**Comment by flekschas** [comment]
@jkmarx As mentioned [above](https://github.com/parklab/refinery-platform/issues/1097#issuecomment-217568154): simply query for an unknown analysis.

**Comment by jkmarx** [comment]
@flekschas From the UI, how did you end up querying for an unknown analysis?

**Comment by flekschas** [comment]
@jkmarx For whatever reasons I don't know I have a lost or deleted analyses which still ends up in the file browser but the API doesn't return anything. I honestly don't know how this could happen but there must be some way because I found another bug (#1098) in provvis where the source code mentioned deleted analyses.

@ngehlenborg Do you by chance know how analyses can get lost or broken in such a way that they appear in the file browser but the API doesn't return anything?

**Comment by ngehlenborg** [comment]
> Do you by chance know how analyses can get lost or broken in such a way that they appear in the file browser but the API doesn't return anything?

Shown in the file browser - you mean in the facet filter? Those are analyses indexed in Solr, maybe you deleted an analysis that didn't get removed properly? Maybe it is a sharing issue?
