### ISSUE TITLE
relaunching stack with RDS snapshot fails due to missing host and port in config.json

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1099]
Commit: 1077232af3389ca562a3f8813a69352e259be146

### Steps to reproduce
1. Launch single stack Refinery on AWS using `make web-stack`.
2. Delete stack.
3. Look up RDS and EBS stack ids and add to `aws-config/50local.yaml` as `RDS_SNAPSHOT` and `DATA_SNAPSHOT` respectively. 
4. [back to 1.] Launch single stack Refinery on AWS using `make web-stack`.

### Observed behavior
Refinery launches but fails to connect to database. Django error page indicates 

```
ValueError at /
invalid literal for int() with base 10: 'null'
Request Method:	GET
Request URL:	http://dev.cloud.refinery-platform.org/
Django Version:	1.6.11
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: 'null'
Exception Location:	/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/psycopg2/__init__.py in connect, line 167
...
```
The problem is caused by the following (note missing host and port info):
```
database: u'refinery'
items:	
[('dbname', u'refinery'),
 ('user', u'refinery'),
 ('password', 'password'),
 ('host', u'null')]
port: u'null'
dsn: None
host: u'null'
user: u'refinery'
kwargs: {}
async: False
password: 'password'
connection_factory: None
```

### Expected behavior
1. Host and port are configured correctly so that Refinery can connect to RDS.

I was able to fix this by manually entering the host and port number (looked up on RDS dashboard in AWS UI - the snapshot did launch properly) and rebooting the EC2 instance.

**Comment by drj11** [comment]
Initial thoughts:

a) this is supposed to work and definitely does for me, so perhaps some configuration issue.

b) one of the first thing the `cloud-init` does is to write a file `/home/ubuntu/rds` that contains (what it thinks are) the RDS connection details. That's worth checking if you see it again.

c) I wonder if having `RDS_NAME` set in the aws-config (which is supposed to work) in fact breaks thing.

**Comment by ngehlenborg** [comment]
Re: b)  `/home/ubuntu/rds` looks like this:

```
null
```

Re: c) Isn't that required to for a)?

**Comment by drj11** [comment]
On `RDS_NAME`:

If `RDS_NAME` is set then that name will be used for the stack;
if `RDS_NAME` is not set then `stack.py` will pick a name at random and use that.

In either case it's supposed to work, and in either case the name will be visible in the config stored in S3.

I've tested (today) creating a stack both with and without `RDS_NAME` set and it seems to work.

@ngehlenborg what's your `RDS_NAME` set to? Can you give me a copy of the config as stored in S3? (a URL to the S3 object should work, but be careful as the contents contain secrets)

**Comment by drj11** [comment]
`/home/ubuntu/rds` is created by part of the `aws.sh` script: https://github.com/parklab/refinery-platform/blob/develop/deployment/aws.sh#L45-L48 which runs the `bin/aws-rds-endpoint`.

Looking at it now it does seem a bit fragile (for example, there are many "funny characters" which if they appear in `RDS_NAME` will break that script). But, that script does work, at least in what appear to be "normal" circumstances.

**Comment by ngehlenborg** [comment]
'RDS_NAME' or 'RDS_SNAPSHOT'?

**Comment by drj11** [comment]
`RDS_NAME`.

I'm pretty sure the stack just plain doesn't start if `RDS_SNAPSHOT` is wrong, so that's not likely.

**Comment by ngehlenborg** [comment]
Where do I set the `RDS_NAME` and what do I set it to? It is not documented on https://github.com/parklab/refinery-platform/wiki/AWS-installation (only mentions `RDS_SNAPSHOT`) and therefore I never configured it!

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-deploy-scc-release-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> deploy SCC release on AWS</a>

**Comment by drj11** [comment]
Investigating a live one I find:

`/home/ubuntu/rds` contains:

```
null
```

Running
```
/srv/refinery-platform/deployment/bin/aws-rds-endpoint rds-refinery-6jjfd15
```
produces the (plausible, and plausibly correct) output:
```
{
  "Port": 5432,
  "Address": "rds-refinery-6jjfd15.c1alfzbtiqkj.us-east-1.rds.amazonaws.com"
}
```

The `/home/ubuntu/rds` is supposed to have that JSON as its contents.
The fact that it doesn't suggests that the command is getting the wrong output when it is run by `aws.sh`.
Which suggests that the RDS instance doesn't have an endpoint by the time the EC2 instance asks for it (it's too early).

**Comment by drj11** [comment]
Now everything is in a single stack we should refer to the RDS DBInstance directly, getting its identifier using `Ref` and its endpoint using `GetAtt` http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#aws-properties-rds-database-instance-ref

**Comment by hackdna** [comment]
Also, we should specify dependencies explicitly: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html

**Comment by drj11** [comment]
Fixed by https://github.com/parklab/refinery-platform/pull/1189

At least, I think so. It is now structurally impossible for the EC2 instance to start without already having the RDS credentials.
