### ISSUE TITLE
analysis in initializing, failed, or unknown status should be linked to corresponding data set analysis tab

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1100]
Commit: 1077232af3389ca562a3f8813a69352e259be146

### Steps to reproduce
1. Launch analysis.
2. View analysis in launchpad or in global analysis monitor.

### Observed behavior
1. Analysis is not clickable and it is impossible to find out more about the analysis because the data set is not referenced.
![screen shot 2016-05-07 at 3 15 29 pm](https://cloud.githubusercontent.com/assets/1216518/15094037/90b29718-1466-11e6-9296-84d4f83e28d2.png)

### Expected behavior
- Analysis link is clickable and takes user to the analysis tab of the associated data set for initializing, unknown, and failed analyses.
- Analysis link is clickable and takes user to the file browser of the associated data set with the results of the analysis pre-selected. _To my knowledge this is already implemented._

**Comment by jkmarx** [comment]
@ngehlenborg During the dev meeting, we decided to unlink the failed, or unknown status completed analyses. The analyses on the dashboard do not update unless the page is refreshed, ref #693 . I can link them to the data set analyses/tab page.

**Comment by ngehlenborg** [comment]
>  I can link them to the data set analyses/tab page.

That's what we need.

**Comment by jkmarx** [comment]
Ref #1068
