### ISSUE TITLE
Reword tabular file import instructions and add more help

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1111]
Commit: 2b765bf888a3b0382833489babdabedf18e9f08f

### Steps to reproduce
1. https://refinery-dev.stemcellcommons.org/data_set_manager/import/

### Observed behavior
The description of the required columns is not very clear.

### Expected behavior
Avoid dev slang, e.g. _slug_. Explanations should be clear. Examples should be given.

**Comment by ngehlenborg** [comment]
@flekschas: can you post your notes here? Thanks!

**Comment by flekschas** [comment]
I noted the following things which were / are unclear in my mind:

## Base path
- Base path == base URL? E.g. /data/ or http://www.example.com/data

## Annotation column
- How can a flat file contain Boolean values? Does that mean the String _true_ or _false_ should be parsed to their Boolean counterparts or is anything truthy (i.e. any non empty string) regarded to be true?

## Data File Permanent
- What exactly does this mean exactly? Aren't files always stored permanently? I assume if this input is checked the data files are downloaded automatically and the source / download URL is renamed to point to the instance.

## Is public
- Very minor but I would rename it to _make public_.

Another idea:
Add a drop down list of groups the user is a member of, so that a data set can immediately be shared with a certain group. The logic would probably be the same as making the imported data set public.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>
