### ISSUE TITLE
Data sets are not displayed on the home page when served over HTTPS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1135]
Commit: b6dcd51

### Steps to reproduce
1. Configure the site to run over HTTPS
1. Open the home page

### Observed behavior
Data set are not displayed and two errors are logged in the browser console:
```
Mixed Content: The page at 'https://dev.stemcellcommons.org/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.stemcellcommons.org/api/v1/data_sets/?format=json&limit=50&offset=0&order_by=-modification_date'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://dev.stemcellcommons.org/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.stemcellcommons.org/api/v1/data_sets/ids/?format=json&order_by=-modification_date'. This request has been blocked; the content must be served over HTTPS
```

### Expected behavior
Data sets are displayed, no errors are logged in the browser console.

### Notes
This is most likely due to use of absolute URLs that hard code HTTP URL scheme (either in Angular code or Django templates).

**Comment by jkmarx** [comment]
Configure the site to run over HTTPS, is this in the wiki?

**Comment by hackdna** [comment]
No but you can try https://dev.stemcellcommons.org/

**Comment by jkmarx** [comment]
It'd be better if I can reproduce the error locally.

**Comment by jkmarx** [comment]
In the ui folder: refinery-setting.js is setting these urls for the common services,
 ```appRoot: document.location.protocol + '//' + document.location.host,```

**Comment by hackdna** [comment]
OK but that seems to be working correctly because all other API calls that use this construct are fine, so the question is where exactly are those two problematic calls made from - there might be some special handling there.

**Comment by jkmarx** [comment]
Similar error is thrown on the dataSet2 browser: https://dev.stemcellcommons.org/data_sets2/816fcfff-1517-4a52-ab2f-b0908b782167/#/files/
