### ISSUE TITLE
Django AWS settings are hardcoded to inherit from dev settings

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1137]
There should be separate dev and prod modes for AWS environment configurable via `$DJANGO_SETTINGS_MODULE`

**Comment by drj11** [comment]
rename `settings/aws.py` to `settings/aws_dev.py` and add `settings/aws_prod.py` ?

And add `manifests/aws_prod.pp` ?

**Comment by hackdna** [comment]
Yes and we probably don't even need a separate `manifests/aws_prod.pp`. `$DJANGO_SETTINGS_MODULE` should be configurable in `config.yaml.template`.

**Comment by hackdna** [comment]
Also, need to add `SITE_URL` to `ALLOWED_HOSTS` (which should be configurable in the `config.yaml.template`) for the prod mode to work properly.

**Comment by hackdna** [comment]
@drj11: do you think you'd be able to wrap this up today? It be great to use this functionality to spin up the production stack.

**Comment by drj11** [comment]
Fixed by #1156

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FlZ1oY2M&#x2F;25-1137"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1137</a>
