### ISSUE TITLE
Add variables to config.yaml.template

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1138]
EBS data volume size and `ADMIN_PASSWORD`.

**Comment by drj11** [comment]
`ADMIN_PASSWORD` is already in (and is now more clearly documented)

**Comment by hackdna** [comment]
@drj11: would it make sense to make the `VolumeType` configurable as well? SSD (gp2) is twice as expensive as magnetic, and I don't think performance is critical for the data volume.

**Comment by drj11** [comment]
yes, will make `VolumeType` configurable

**Comment by drj11** [comment]
- [ ] need to document `DATA_VOLUME_SIZE` and `DATA_VOLUME_TYPE`
