### ISSUE TITLE
REFINERY_DATA_IMPORT_DIR is not set correctly on AWS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1139]
Current value in `config.json.erb` is hardcoded to `/vagrant/import`. It should something like `/data/import` (similar to `MEDIA_ROOT`).

**Comment by drj11** [comment]
On it.

FWIW I've grepped the `config.json` on a live AWS instance and there don't seem to be any more mentions of `vagrant`:

```
$ grep vagrant ./config/config.json
  "REFINERY_DATA_IMPORT_DIR": "/vagrant/import",
```
