### ISSUE TITLE
show admin contact information on registration confirmation page

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1148]
Commit: a60c4e183b4910a2d8bdd5238dab2384cdbe34b6

### Steps to reproduce
1. Register for an account. 

### Observed behavior
1. Message "Your account is currently pending approval. An activation link has been sent to the Administrator." is displayed.

### Expected behavior
1. Information on how to contact the administrator is displayed in addition to above message, e.g. "We generally attempt to approve accounts within 2 business days. If you do not hear from us within that time frame, please contact the Administrator (<email address clickable link>) mentioning your username.

**Comment by scottx611x** [comment]
This is fixed as of commit: b977c882ab84d8af030d94aeaea02ed767e6e7c1
