### ISSUE TITLE
account activation email needs to be more specific

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1149]
Commit: a60c4e183b4910a2d8bdd5238dab2384cdbe34b6

### Steps to reproduce
1. Register for an account.
2. Have administrator activate the account.
3. Receive account activation email.

### Observed behavior
1. Current message says:
```
Subject: Welcome to Refinery
Body: Please fill out your user profile
```

### Expected behavior
1. Message subject should be `Welcome to <SITE NAME>`
2. Body should be: 
```
Your account has been activated.

To log into <SITE NAME>, please follow this link and use your username or email address and password provided when you registered:

<URL TO LOGIN PAGE>

If you have any questions, please contact the <SITE NAME> team at <ADMINISTRATOR EMAIL>.
```

@scottx611x: Let me know if you need pointers to any of the variables that are required here.

**Comment by ngehlenborg** [comment]
@hackdna and @sjhosui - please comment if you have any thoughts on that.

**Comment by hackdna** [comment]
These are customizable for each installation via `config.json`.

**Comment by scottx611x** [comment]
@ngehlenborg @ilya: So should I be taking action on this or are these setting just something the instance's admin should be taking care of?

**Comment by hackdna** [comment]
We can change the default text in the template to what Nils suggested but ultimately this is unique for each installation. Also, `REFINERY_WELCOME_EMAIL_MESSAGE` and `REFINERY_WELCOME_EMAIL_SUBJECT` might be useful to add to `config.yaml.template` for cloud deployments (@drj).

**Comment by ngehlenborg** [comment]
@hackdna: can variables be inserted into the config? e.g. could `REFINERY_WELCOME_EMAIL_SUBJECT` be defined as `Welcome to <SITE_NAME>"?

**Comment by hackdna** [comment]
You'd probably have to use templates for that. However, items like site name, login URL and admin email need to be set only once (at deployment), so it's sufficient to add them to REFINERY_WELCOME_EMAIL_MESSAGE and REFINERY_WELCOME_EMAIL_SUBJECT directly.

**Comment by hackdna** [comment]
It should be possible to set `REFINERY_WELCOME_EMAIL_MESSAGE` and `REFINERY_WELCOME_EMAIL_SUBJECT` in `config.yaml.template`.

**Comment by scottx611x** [comment]
@hackdna: I believe what we're trying to achieve here can't be done with just YAML.

For Example, reusing values works great:
```yaml
person: &person 'Scott Ouellette'
another_person: *person
#'another_person': 'Scott Ouellette'
```
But concatenating to a reused value isn't possible. The closest I've come is to make an array of reused values with normal strings inbetween.
```yaml
person: &person 'Scott'
message: &message 'loves coffee'
combined: 
- *person
- 'really'
- *message
#'combined': ['Scott', 'really', 'loves coffee']
```

**Comment by hackdna** [comment]
Lets just set them to simple strings that can be configured at the time of deployment for now.

**Comment by scottx611x** [comment]
@hackdna Sounds good to me 👍

**Comment by scottx611x** [comment]
@mccalluc Yes i just did it through the admin UI

**Comment by mccalluc** [comment]
I made another account, ilya approved it, and I did get the email. Nothing to worry about here.
