### ISSUE TITLE
Undefined slug should be allowed

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1166]
Commit: 1cd68b1e4cc2a0e045829b1c166167b7f08cdafc

### Steps to reproduce
1. Create a new data set with _slug_ to be `None`
2. Open the log file

This happens when importing the same tabular file multiple times with different names.

Also see 

### Observed behavior
```ERROR    core.models:235 save() - DataSet with slug: None already exists!```

### Expected behavior
```INFO    core.models:235 save() - DataSet with slug: None is okay!```

**Comment by scottx611x** [comment]
@flekschas: I've spent too long on this now, but with the current logic in place the only way line 235 in `core/models.py` can be reached is if the slug's value is truthy.  If the slug in question is `None` or `""` it wont't [ass the `if self.slug` logic and will be saved no matter what.

I could be mistaken, although I really think you may have been doing something like:

`>>> DataSet.objects.create(slug="None")`
`>>> DataSet.objects.create(slug="None")`

Which would yield the error message that you were seeing: `ERROR core.models:235 save() - DataSet with slug: None already exists!`

I believe the newly introduced tests here illustrate my point: core.tests.BaseResourceSlugTest#test_save_empty_slug_when_another_model_with_same_slug_exists
&
core.tests.BaseResourceSlugTest#test_save_empty_slug_when_same_model_with_same_empty_slug_exists

**Comment by flekschas** [comment]
@scottx611x Could you try to import two test data sets view the metadata table import and leave the slug empty? I came across this issue when testing the old legacy metadata table importer which might have send an empty or _None_ String to the backend. So this issue might have been fixed with the new import UI already. Thanks :)

**Comment by scottx611x** [comment]
@flekschas I tried this out today and had no luck reproducing the issue you saw. Looks like the new importer does some magic :)

**Comment by flekschas** [comment]
@scottx611x Great! Thanks for checking.
