### ISSUE TITLE
Integrate ELB with the CloudFormation stack

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1170]
The current beta site is deployed behind an ELB which terminates HTTPS. We should be able to create a new ELB when setting up a brand new stack or re-use an existing one if available.
There should be settings added to the config.yml.template for load balancer name, all necessary HTTPS certificate files and other items necessary for provisioning an ELB.
Apache config template should be changed to configure redirect from HTTP to HTTPS.
Set ServerName in Apache config from SITE_URL

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yK35fIKV&#x2F;260-add-elb-to-the-stack"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add ELB to the stack</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WKWVJxrD&#x2F;261-configure-https-using-puppet"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Configure HTTPS using Puppet</a>

**Comment by hackdna** [comment]
An example of Apache config file updated for HTTPS:
```
# Generated from apache.erb.conf
# by refinery-modules/refinery/manifests/init.pp

WSGIPythonHome /home/ubuntu/.virtualenvs/refinery-platform

SetEnv DJANGO_SETTINGS_MODULE config.settings.aws

<VirtualHost *:80>
    ServerName dev.stemcellcommons.org

    RewriteEngine On
    RewriteCond %{HTTP:X-Forwarded-Proto} !https
    RewriteRule ^.*$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    <Directory /srv/refinery-platform/refinery/config>
        <Files wsgi.py>
            Order deny,allow
            Require all granted
        </Files>
    </Directory>
    WSGIScriptAlias / /srv/refinery-platform/refinery/config/wsgi.py

    WSGIDaemonProcess refinery user=ubuntu group=ubuntu \
        python-path=/srv/refinery-platform/refinery:/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages
    WSGIProcessGroup refinery

    #Alias /robots.txt /vagrant/refinery/static/robots.txt
    #Alias /favicon.ico /vagrant/refinery/static/favicon.ico

    AliasMatch ^/([^/]*\.css) /srv/refinery-platform/refinery/static/styles/$1

    Alias /static/ /srv/refinery-platform/static/
    Alias /media/ /data/media/

    <Directory /srv/refinery-platform/static>
        Order deny,allow
        Require all granted
    </Directory>

    <Directory /data/media>
        Order deny,allow
        Require all granted
    </Directory>

</VirtualHost>
```

**Comment by drj11** [comment]
Noting here so I don't lose it. Can get Amazon to create our certificates: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/ssl-server-cert.html

**Comment by hackdna** [comment]
Btw, it is possible to have conditionals in the template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html

**Comment by hackdna** [comment]
As we discussed, there should be a single file for all stack settings, including tags. Also, we should probably have two AWS deployment modes. Prod: with SSL and dev: with no SSL. Dev mode settings/templates would be useful for Vagrant deployments too.

**Comment by hackdna** [comment]
Regarding HTTPS handing in Django: https://docs.djangoproject.com/en/1.9/topics/security/#ssl-https

**Comment by hackdna** [comment]
Also, we should log actual client IPs in Apache logs, not the ELB IPs ([X-Forwarded-For](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-for) header)
