### ISSUE TITLE
Django Rest - Node Set API

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1175]
Upgrade the current Node Set API to django rest. Required for launching analyses in data set 2 browser.
- [x] Solidify requirements 
       Which fields are required, no longer neccessary 
       Ensure relationships
       Enable Launching analysis successfully
- [x] New model should store UUIDs
- [x] Get Node Group List
- [x] Get a Node Group - uuid
- [x] Create new node group

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-upgrade-phase-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Upgrade, Phase 1</a>

**Comment by jkmarx** [comment]
@ngehlenborg 
Node Collection -> Investigation -> Study -> NodeSet -> Node Relationship <- Node Pair <- Node
Django Rest Node Set API rename suggestions: 
Node Group
Node Faction
Node Cluster
Node Lot
Node Pack

Fields are generally the same. 
assay
study
expiration
is_implicit ?? (What is this field for?)
node_count
uuids

**Comment by ngehlenborg** [comment]
I like NodeGroup!

**Comment by ngehlenborg** [comment]
`is_implicit` was used to denote node sets generated by the software rather than the user (such as the _Current Selection_). Should maybe renamed to `is_internal`?
