### ISSUE TITLE
Admin user does not belong to the Public Group

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1182]
Erring code introduced in commit: 0c4cc0610ef1827f2d289207b15f2353559c9e2b

**Reproduce:**
Check out the object permissions on the `admin` user in the admin interface.

**Observed:**
The Public Group is not assigned!
This was noticed while trying to share a DataSet. When the admin user has no public group associated you'll see this:
![screen shot 2016-06-01 at 2 24 14 pm](https://cloud.githubusercontent.com/assets/5629547/15721541/77432d7e-2807-11e6-9914-dbff8e687f44.png)

**Expected:**
It should have the Public Group assigned to it.

### **How to fix:**

The `init_refinery` step here: https://github.com/parklab/refinery-platform/blob/develop/deployment/refinery-modules/refinery/manifests/init.pp#L114

Needs to occur after the creation of the `admin` user here: https://github.com/parklab/refinery-platform/blob/develop/deployment/refinery-modules/refinery/manifests/init.pp#L128

Since the method that adds the admin user to the `Public Group` occurs within the `init_refinery` management command here: https://github.com/parklab/refinery-platform/blob/0c4cc0610ef1827f2d289207b15f2353559c9e2b/refinery/core/management/commands/init_refinery.py#L43

**Comment by hackdna** [comment]
We should probably break up the `init_refinery` command into its individual steps and encode them using Puppet. This would provide the required flexibility and further separate application configuration from application code.

**Comment by scottx611x** [comment]
@hackdna Thanks for the input! I'll do that once I get to this!
