### ISSUE TITLE
Remove all print statements from Python code

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1195]
Commit: d59d50411c63a4639c9b45a15e3b347c654c6ec1

Replace all `print` statements either with logging calls, `sys.stdout.write()` or `sys.stderr.write()` as appropriate.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6xe10og5&#x2F;53-1195"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1195</a>
