### ISSUE TITLE
Inactive workflows included in the total on Statistics page

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1205]
Commit: aafd8accf8275a001f059454d0ea975be706aca1

### Steps to reproduce
1. Import Galaxy workflows from an instance twice
1. Open the Statistics page (`/statistics/`)

### Observed behavior
The number of workflows on the Statistics page is greater than the total number of workflows available to the users (active workflows)

### Expected behavior
The number of workflows on the Statistics page should be equal to the total number of workflows available to the users

**Comment by scottx611x** [comment]
Closing as of commit: 8ae8ee917d6f0967645c1f18cc66ceb47261d925
