### ISSUE TITLE
Workflow API V2 Exposes All Workflows

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1207]
Commit: f377cda95ee32c88d8e2f45f582c7f79b1050446

### Steps to reproduce
-- In Django Swagger:
1. Locally http://192.168.50.50:8000/docs/#!/workflows/Workflow_list
or
https://refinery-dev.stemcellcommons.org/docs/#!/workflows/Workflow_list

![screen shot 2016-06-14 at 2 04 18 pm](https://cloud.githubusercontent.com/assets/9956764/16054069/8757132e-3239-11e6-9470-7978b9adeeb4.png)

### Observed behavior
Workflow API2 allows all CRUD actions, unprotected.

### Expected behavior
Which actions do we require?

**Comment by jkmarx** [comment]
@hackdna @ngehlenborg @scottx611x : It doesn't appear the front end is using this API, but I could be mistaken. Please comment on the expected behavior.

**Comment by hackdna** [comment]
The only allowed operation for APIs by default should be a GET.

**Comment by scottx611x** [comment]
I've gotten rid of the Workflow API v2 in one of my recent branches. We should have some discussion if it's worth keeping/upgrading it to DRF.

**Comment by ngehlenborg** [comment]
Can you please clarify why you would want to get rid of the API?

**Comment by scottx611x** [comment]
@nils sure, the api was updated to DRF to support a feature that never came into fruition. I believe https://github.com/parklab/refinery-platform/issues/866

I figured if we are not working on this feature I could reimplement the v2 API once #866 comes back into the loop
