### ISSUE TITLE
Node Set Button - Reset Broken

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1215]
Commit:
c6aae7951b62e70fded561d76e1c65c9b2f4c281
### Steps to reproduce
1. https://beta.stemcellcommons.org/#/
2. Go to the file brower of any data set
3. Select some nodes
4. Hit Reset

### Observed behavior
~~Nothing Occurs~~
Attribute filters reset but the default is blacklist mode instead of whitelist mode.

### Expected behavior
Nodes should be deselected.

**Comment by jkmarx** [comment]
![reset_issue](https://cloud.githubusercontent.com/assets/9956764/16987496/92afade8-4e5a-11e6-92b1-3d8421bb6857.gif)

**Comment by jkmarx** [comment]
@ngehlenborg Please confirm: after clearing the facets, should the default be all nodes are deselected?

**Comment by ngehlenborg** [comment]
The selection should be the same as if the user just loaded the page. I believe that corresponds to "all nodes are deselected" at this point (it used to be the other way around).

**Comment by jkmarx** [comment]
@ngehlenborg Great, thanks.

**Comment by jkmarx** [comment]
@sjhosui Will you please confirm this was the reset bug you observed? The facets reset but the nodes go to select all.
