### ISSUE TITLE
Incorrect message displayed when admin approves user account

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1228]
Commit: 9a197d34ee4340a2e0224e8de6337291e95cfe71

### Steps to reproduce
Click on the URL in the confirmation email to approve the account registration request

### Observed behavior
Message displayed:
```
Account activated.
Thanks for signing up! Now you can log in.
```

### Expected behavior
Message displayed should be something like:
```
Account activated. Confirmation email sent to the user.
```

**Comment by scottx611x** [comment]
Closing as of commit: a62e47f60316c815ec5cd1fd80dc41c02c9e12cd
