### ISSUE TITLE
Django settings cannot be controlled from config.yaml on AWS

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#1232]
Commit:

### Steps to reproduce

When deploying to AWS (particularly production instances), there a bunch of Django settings that we would like to be able to set.

The trello card: https://trello.com/c/3zHgFSvn/288-add-django-settings-to-config-yaml-template

### Observed behavior

See trello card.

**Comment by drj11** [comment]
See also https://trello.com/c/dNYokUZJ/71-switch-config-json-to-a-format-that-support-comments

**Comment by drj11** [comment]
There are a lot of settings. The normal life of a setting for AWS deployment is:

- a key value pair in `aws-config/config.yaml`;
- gets read by the pythong script `stack.py`;
- becomes a shell script environment variable assignment of the form `CONFIG_VAR="custom value"` in the EC2 instance's `cloud-init` script;
- the `cloud-init` script is part of the Cloud Formation JSON template that `stack.py` writes (the file `web.json`);
- the instance starts and runs the `cloud-init` script, which sets the environment variable;
- puppet runs, creating Facter facts from `FACTER_*` environment variables (see https://puppet.com/blog/facter-part-1-facter-101);
- values get templated into various files, in particular `config.json` is templated from `config.json.erb`;

This seems really complicated. It is okay for one or two things, but for bulk settings which are expected to go into `config.json` and not otherwise be used by puppet, we can probably do something similar.

**Comment by drj11** [comment]
The kinds of things that get set in `config.json` can be divided
into 3 categories, which we can order in terms of frequency of
change (from slowest to highest).

- Infrastructue (eg, Vagrant versus AWS (versus
Azure / Cloudstack));
- Site (eg, stemcellcommons.example.org vs
genometranslationcommons.example.org);
- Activation (for example, between stopping an instance and
restarting it);

Currently the kinds of things in the 3 categories are:

- Infrastructure: system paths (eg `/vagrant` versus
`/home/ubuntu` versus `/srv/refinery-platform`), isatab dir,
import dir, solr lib dir

- Site: URL, e-mail addresses

- Activation: (private) IP address, RDS details, SMTP Credentials

The things in `Activation` are generally automatically
discovered by "the system" and configured somehow.
At the moment, generally when an EC2 instance is created and the
`cloud-init` script runs.

The things in `Infrastructure` are generally chosen once by
developers who are packing refinery for some particular infrastructure 
(Vagrant, or AWS).
At the moment there are very few
and they can probably be unified and so not required.

Things in `Activation` are, at the moment,
a mixture of templated into `config.json` (SMTP credentials)
and picked up at runtime
by `settings.py` (Private instance IP address).

Things in the `Site`, the middle category, are generally chosen by
someone mamanging a site.
Incuding developers who are "managing" a site for their own use.

There might be quite a lot of things in `Site`,
and most of them are Django settings
that none of the rest of the system needs to deal with.
Ideally they would be bulk transferred into Django settings
somehow.
drj@mus:~/prj/refinery-platform$

**Comment by drj11** [comment]
In particular templating into config.json seems particular error prone and fragile. It's okay for one or two things, but for a large number of variables its too circuitous. If puppet already needs the configuration variable (for example, `$media_root` is used to configure apache), then it seems okay for puppet to template it into `config.json`.

But a lot of variables just need to go straight to Django settings from where the site administrator has originally specified them.

**Comment by drj11** [comment]
So I think there should be two files:

`config.json`. currently templated in from `config.json.erb` from puppet. Can only change a few variables this way.

`site-config.json` (open to better names). Which is simply a second source of Django settings. The file is created by the Site administrator and is copied by `stack.py` into the target file system.

If we adopt this, probably most of the things you can currently set in `aws-config` will move to `site-config.json`. Which is good because a lot of them would need setting in a Vagrant setup anyway.

**Comment by drj11** [comment]
Looking at the variables currently used by `stack.py` they divide into 3 categories:

`config.json`: `ADMIN`, `DEFAULT_FROM_EMAIL`, `SERVER_EMAIL`

Entirely internal to CloudFormation (the EC2 instance never sees them): `AVAILABILITY_ZONE`, `RDS_NAME`, `RDS_SNAPSHOT`, `DATA_VOLUME_SIZE`, `DATA_VOLUME_TYPE`, `DATA_SNAPSHOT`, `KEY_NAME`

Variables used by puppet that actually do some puppety configuration stuff: `SITE_NAME`, `RDS_ROLE`, `S3_CONFIG_URI`, `SITE_URL`, (and `RDS_SUPERUSER_PASSWORD` which is currently buggy).

**Comment by hackdna** [comment]
Btw, an example of how to output web server instance URL (among other things) after a stack is created: https://s3-us-west-2.amazonaws.com/cloudformation-templates-us-west-2/LAMP_Single_Instance.template

**Comment by hackdna** [comment]
[Integrating AWS CloudFormation with Puppet](https://s3.amazonaws.com/cloudformation-examples/IntegratingAWSCloudFormationWithPuppet.pdf)

**Comment by drj11** [comment]
Fixed by #1266
