### ISSUE TITLE
Make Django's ALLOWED_HOSTS work with AWS ELB Health Checks

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1239]
[Description of the problem and a possible solution](https://dryan.com/articles/elb-django-allowed-hosts/)

**Comment by hackdna** [comment]
[An alternative solution](https://www.xormedia.com/django-allowed-hosts-and-amazon-elastic-load-balancer/)

**Comment by drj11** [comment]
The alternate seems weird. It's not hard to get the internal IP address (as the first link shows).

Stealing the relevant code, just in case it disappears
```
# Hosts/domain names that are valid for this site; required if DEBUG is False
# See https://docs.djangoproject.com/en/1.5/ref/settings/#allowed-hosts
ALLOWED_HOSTS = [
    'yourdomain.tld',
    '.compute-1.amazonaws.com', # allows viewing of instances directly
]

import requests
EC2_PRIVATE_IP  =   None
try:
    EC2_PRIVATE_IP  =   requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout = 0.01).text
except requests.exceptions.RequestException:
    pass

if EC2_PRIVATE_IP:
    ALLOWED_HOSTS.append(EC2_PRIVATE_IP)
```

**Comment by hackdna** [comment]
I don't think we should use the `'.compute-1.amazonaws.com'` entry since it allows every EC2 instance and ELB is actually using IP addresses to do health checks.
I think we should log a warning if there is a problem obtaining the IP address.

**Comment by drj11** [comment]
I hadn't even spotted the `.compute-1.amazonaws.com` entry. As it happens, I hadn't copied it into the code I am working on. And I agree, we don't want it.

I had decided that failure to obtain the IP address was bad enough that we just stop (`import settings` fails), but perhaps just a warning is okay.
The thing is, it's basically untestable and the situations in which it will happen are weird (for example, the AWS admin has launched the instance in a security group where instances do not have access to their own metadata.

**Comment by drj11** [comment]
This is now implemented in https://github.com/parklab/refinery-platform/pull/1249

**Comment by hackdna** [comment]
There's a couple of potential solutions: ask user to set SITE_URL to a DNS record that would need to point to the public IP/hostname automatically assigned to the EC2 instance (once it becomes available) or an Elastic IP; or ask user to set up an ELB and point SITE_URL to it.

**Comment by drj11** [comment]
ELB's don't have permanent IP addresses, right? But they are sufficiently long lived that you can not care about that for development purposes.

**Comment by hackdna** [comment]
ELBs have permanent hostnames that can be used for CNAMEs.
