### ISSUE TITLE
Remove infrastructure and code for Sphinx docs

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1240]
Related to #304 and #482 

In addition to removing the docs, we also need to remove the Python packages that were used to generate them.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jtuvuuPD&#x2F;14-482"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Convert documentation from reStructuredText to Markdown</a>

**Comment by ngehlenborg** [comment]
Addressed by https://github.com/parklab/refinery-platform/pull/1438
