### ISSUE TITLE
Incorrect number of samples displayed in the sample browser during import

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1241]
Commit: ec43d5ba6d2f6cd5efcd583c9f420c11a4d5f548

### Steps to reproduce
Import http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/E-GEOD-23694/e-geod-23694.txt (check "Data File Permanent")

### Observed behavior
Only one of two samples in the data set is displayed in the sample browser while the files are still being imported.

### Expected behavior
All samples should be displayed even while samples are still being imported with appropriate icons to indicate their status.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by ngehlenborg** [comment]
This is most likely an issue with Solr. We should get the overall Solr import status and only show the file browser when Solr is done indexing all nodes in the data set.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XMAozKYg&#x2F;296-fix-data-set-view-issues-during-import"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> fix data set view issues during import</a>

**Comment by jkmarx** [comment]
@hackdna I could not recreate this issue. Pull request https://github.com/parklab/refinery-platform/pull/1421 doubles the weight time. Will you please check to see if it's sufficient? You can even just change the code in your current branch to test it out. Thanks.

**Comment by hackdna** [comment]
OK, I can't reproduce this either in a local VM or on AWS now. I've even tried clicking on the manual redirect link before automatic redirect happened. So, I don't think we even need to increase the timeout. Please update the pull request and I'll close this issue.
