### ISSUE TITLE
Data set name is not displayed correctly in the launch pad

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1242]
Commit: ec43d5ba6d2f6cd5efcd583c9f420c11a4d5f548

### Steps to reproduce
1. Import http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/E-GEOD-23694/e-geod-23694.txt
1. Navigate to the launch pad

### Observed behavior
Data set is listed as "Untitled data set" in the launch pad (data set name is displayed correctly in the data set browser).

### Expected behavior
Data set name should be displayed correctly in the launch pad.

**Comment by jkmarx** [comment]
<img width="462" alt="screen shot 2016-07-15 at 1 01 53 pm" src="https://cloud.githubusercontent.com/assets/9956764/16882306/62bcf81a-4a8c-11e6-8fc5-a85d6aa15e25.png">

Locally, I could not reproduce the error with this data set, but noticed it did occur with another dataset earlier this week.

**Comment by jkmarx** [comment]
@hackdna Was this error on https://beta.stemcellcommons.org/#/ ?

**Comment by hackdna** [comment]
No, https://test.stemcellcommons.org

**Comment by jkmarx** [comment]
Request PayLoad
```------WebKitFormBoundarymaTHKoK47qpocN3e
Content-Disposition: form-data; name="file"; filename="e-geod-23694.txt"
Content-Type: text/plain


------WebKitFormBoundarymaTHKoK47qpocN3e
Content-Disposition: form-data; name="title"

e-geod-23694
------WebKitFormBoundarymaTHKoK47qpocN3e
Content-Disposition: form-data; name="source_column_index"

0
------WebKitFormBoundarymaTHKoK47qpocN3e
Content-Disposition: form-data; name="data_file_column"

0
------WebKitFormBoundarymaTHKoK47qpocN3e
Content-Disposition: form-data; name="delimiter"

tab
------WebKitFormBoundarymaTHKoK47qpocN3e--```

**Comment by jkmarx** [comment]
Lauchpad uses title field. The title field is not being assign correctly on the Test Site. I'd think this was a back end issue, since the title field is not being assigned correctly.

In the file browser, it utilizes name instead of title.
**Locally:**
```{
accession: null,
accession_source: null,
creation_date: "2016-07-15T13:00:40.845468",
date: "2016-07-15T13:00:40.863234",
description: "",
file_count: 2,
file_size: 0,
id: 26,
is_owner: true,
is_shared: false,
modification_date: "2016-07-15T13:00:41.077060",
name: "e-geod-23694",
owner: "5377caec-0e4f-4de5-9db5-3214b6ef0857",
pre_isa_archive: "425dbcef-c186-4c2e-890b-937c23c99ec8",
public: false,
resource_uri: "/api/v1/data_sets/ba1959c8-db56-45ac-b3b5-20969ce1a2fc/",
share_list: null,
slug: "None",
summary: "",
title: "e-geod-23694",
uuid: "ba1959c8-db56-45ac-b3b5-20969ce1a2fc",
version: 1
},```
**On Test Site**
```{
accession: null,
accession_source: null,
creation_date: "2016-07-15T14:06:20.745209",
date: "2016-07-15T15:34:58.648927",
description: "",
file_count: 0,
file_size: 0,
id: 4,
is_owner: true,
is_shared: false,
modification_date: "2016-07-15T14:06:20.745243",
name: "e-geod-23694",
owner: "e0c7ffbc-9836-449e-93c3-801fe9862f7e",
public: false,
resource_uri: "/api/v1/data_sets/69f9bccf-5084-47c3-be51-e3028c23c7dd/",
share_list: null,
slug: null,
summary: "",
title: "Untitled data set",
uuid: "69f9bccf-5084-47c3-be51-e3028c23c7dd",
version: 4
}```

**Comment by jkmarx** [comment]
@hackdna @ngehlenborg Double checked with the correct commit, locally and could not reproduce the issue in dev or prod modes.

**Comment by hackdna** [comment]
Can you reproduce it on the test site? If yes, you'd need to debug there.

**Comment by ngehlenborg** [comment]
@flekschas: Can you comment on why there might be differences between titles and names? (see @jkmarx comment above).

**Comment by flekschas** [comment]
@ngehlenborg: The name should be composed of the data set id, a hyphen, and the title. I think I've split the two in order to save some space as the data set id are used internally only if I am not mistaken.

The title and id fields are extracted during the import process. Maybe something goes wrong there? Otherwise it would be interesting to know if the name is _untiteled_ after a search query has been issued as well.

**Comment by jkmarx** [comment]
@flekschas  On the test site, the title remain as "Untitled data set" even after a search query. Please note, in the launch pad, the names are correct...it's the title field which is being shown and is incorrect.

**Comment by flekschas** [comment]
@jkmarx Yeah I guess it's a backend issue too. Something must have gone wrong during the import process.

**Comment by jkmarx** [comment]
Locally using the Mov10 file the untitled data set issue occurs ```2016-07-19 15:57:28 ERROR    core.models:237 save() - DataSet with slug: None already exists!```
