### ISSUE TITLE
Duplicate About in header and file browser tab

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1245]
In the data set 2 browser, the navigation tab has an about name. The abouts tab merged the data set details and sharing information.

Perhaps, one of the names should be updated?

**Comment by jkmarx** [comment]
@ngehlenborg Did you have thoughts on this question? Should we rename the About in the data-set-browser?

**Comment by ngehlenborg** [comment]
Yes, let's rename it into "Details".

**Comment by jkmarx** [comment]
I'm going to repurpose this question issue, into an action issue.
 - [ ] Update abouts label into Details.
- [ ] Rename angular files
