### ISSUE TITLE
Data Set Preview -- Sharing Modal Needs more text

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1246]
Data Set Preview --> Sharing 

<img width="633" alt="screen shot 2016-07-14 at 4 20 42 pm" src="https://cloud.githubusercontent.com/assets/9956764/16854458/f545f316-49de-11e6-912e-169ded1fba81.png">

- [x] The modal should have more info about sharing and groups.
- [x] Link to create a group

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by jkmarx** [comment]
@hackdna @ngehlenborg @sjhosui  What additional text did we want to add?

**Comment by hackdna** [comment]
I'd change "Read-only" to "Access" and "Edit" to "Modify". I'd also group the permission columns closer together under a (sub-)heading "Data set permissions" and provide a help balloon for at least the "Modify" column describing what it enables (e.g., running analyses?).

**Comment by ngehlenborg** [comment]
@jkmarx, here is my suggestion (include this above the table):

---
Select which of the groups that you are a member of should have access to this data set. You can assign either _Read-only_ or _Edit_ access. 

  * _Read-only_ access allows other group members to view the data set and the results of all analyses executed on the data. 
  * _Edit_ access additionally allows other group members to run analyses on the data that will become part of the data set.

You can revoke access by selecting _None_.

Note that by sharing this data set with the "Public" group, __anyone who visits the site will be able to view this data set__. 

---

**Comment by ngehlenborg** [comment]
Didn't see that Ilya posted before me. Revised my comment above. I think we can rename "Edit" to "Modify" but I would leave "Read-Only" as is ("access" can mean a lot).

**Comment by jkmarx** [comment]
Thanks!

**Comment by jkmarx** [comment]
@ngehlenborg @sjhosui ![screen shot 2016-09-29 at 11 03 49 am](https://cloud.githubusercontent.com/assets/9956764/18959558/9f5d4f34-8634-11e6-9939-d27870b393cd.png)

**Comment by ngehlenborg** [comment]
Looks good but is there any way to separate the header ("Permission Editor") from the rest with a horizontal line all across the modal?

**Comment by jkmarx** [comment]
<img width="606" alt="screen shot 2016-09-29 at 1 37 47 pm" src="https://cloud.githubusercontent.com/assets/9956764/18965147/f2c7f588-8649-11e6-84d1-e9799853e443.png">
