### ISSUE TITLE
Workflow input names are not unique error during workflow import

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1265]
Commit: 29745d057ba2ee5e4da65c05e74f3ee31915be1d

### Steps to reproduce
1. Install https://toolshed.g2.bx.psu.edu/view/stemcellcommons/chipseq_workflows/f9ffbe563402 and import one of the workflows into Galaxy 16.04.
1. Import Galaxy workflows into Refinery
1. Change a parameter of one of the tools
1. Re-import Galaxy workflows into Refinery

### Observed behavior
Workflow is imported on the first try but fails to re-import after modification with the following error message:
```
Unable to import workflow 'TF ChIP-Seq analysis using MACS2: hg19' due to the following issues:
Workflow input names are not unique: input1, input_file, exp_file, input_file, input_file, singlePaired, singlePaired, source, source, infile_control, input_control_file
```

### Expected behavior
Workflow should import successfully.

See also #268, #280 and #778.

**Comment by hackdna** [comment]
Refinery expects all the steps in a workflow to have empty `"inputs"` - except workflow input steps (to identify workflow inputs). This is not the case for workflows in Galaxy 16.04.

**Comment by ngehlenborg** [comment]
Does this only occur upon re-import?

**Comment by hackdna** [comment]
Yes, this occurs when a workflow edited and saved in Galaxy 16.04 is re-imported into Refinery.
