### ISSUE TITLE
DataSet2 - Node Group Selection

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1273]
Can we get rid of the Node Group above the filter and keep the functionality of save/reset as part of the Analysis and IGV? Otherwise, I can remove the save/reset from underneath the Launch Analysis NodeGroup selection.

Analyze
<img width="453" alt="screen shot 2016-07-26 at 2 04 14 pm" src="https://cloud.githubusercontent.com/assets/9956764/17149593/fa8bbd56-5339-11e6-8c53-2620bf15fe38.png">

- [ ] Update Partial
- [ ] Fix event bug when node group updates to Current Selection when a selection is made.

**Comment by ngehlenborg** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1216518/17151088/5c1acd04-5340-11e6-8f9a-1f8223a15745.png)
