### ISSUE TITLE
Add support for BCL files and .fq extension

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1280]
- [x] Add file type and extension to file_store fixtures for Illumina basecall files.
More details: https://beta.stemcellcommons.org/admin/file_store/filetype/39/ and https://beta.stemcellcommons.org/admin/file_store/fileextension/38/

- [x] We also need to support the `.fq` extension and associate it with the FastQ FileType

 - [ ] Also, for gzip'ed and tar'ed + gzip'ed versions of the BCL files. We should also think about providing automatic support for compressed versions of all file types.

**Comment by scottx611x** [comment]
@hackdna: Do you mean that we would want to move away from having these duplicate entries in our fixture (`fastq` & `fastq.gz`) and just keep track of all the base filetypes/extensions but be able to detect whether they are compressed or not?

In a very basic sense I'm envisioning something like:

```
f = FileStoreItem.objects.create(extension = 'fastq.gz')
compression_types = ['gz', tgz', 'zip']

if f.extension.split('.')[-1] in compression_types:
    f.compressed = True
    f.save()
```

Then we could just display the FileType like so based on the value of the `compressed` flag.
`compressed = False` ->
`<FileType: FastQ>`

`compressed = True` ->
`<FileType: FastQ | Compression: Gzip>`

**Comment by ngehlenborg** [comment]
Can we separate the creation of a different way of handling compressed files from this issue and close this? @scottx611x please create a new issue for compression (not flagged wth `important`) and refer to this one.
