### ISSUE TITLE
Pin Javascript dependencies to exact versions

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1288]
Currently, Javascript dependencies allow silent upgrades of patch and minor versions. We should pin the versions to avoid issues like #1283.

We should look into using [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap).
http://jonnyreeves.co.uk/2016/npm-shrinkwrap-sucks/

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2xU1ZIw3&#x2F;57-1288"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 1288</a>

**Comment by jkmarx** [comment]
Additional material: https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/ , http://javascript.tutorialhorizon.com/2015/03/21/what-is-npm-shrinkwrap-and-when-is-it-needed/

**Comment by hackdna** [comment]
Thanks, npm shrinkwrap sounds interesting. What are the tradeoffs of using it vs just pinning the versions in package.json? What changes would require in our deployment process? Also, the articles are from 2012 and 2015 - are there any newer alternatives?

**Comment by jkmarx** [comment]
Currently, all of our node modules are devDependencies. ```Since npm shrinkwrap is intended to lock down your dependencies for production use, devDependencies will not be included unless you explicitly set the --dev flag when you run npm shrinkwrap. If installed devDependencies are excluded, then npm will print a warning. If you want them to be installed with your module by default, please consider adding them to dependencies instead.```

**Comment by jkmarx** [comment]
Bower does not have a strinkwrap option. https://github.com/bower/bower/issues/505    Currently, we do pin down all of our bower modules but we could still run into the dependencies -> dependencies issue. It may be worthwhile to add some of the dependencies.

**Comment by jkmarx** [comment]
https://github.com/bower/bower/milestone/5

**Comment by jkmarx** [comment]
http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies
