### ISSUE TITLE
Metadata table preview does not persist

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1291]
Commit: 6336f5926b11d46235b5a15ab4a4dc774e9fd492

### Steps to reproduce
1. Open a tabular file in the metadata import form (`/data_set_manager/import/`)
1. Switch to the data file upload form (`/data_set_manager/import/#/upload/`)

### Observed behavior
Metadata import form is reset and has no content

### Expected behavior
Metadata import form should still contain all the entries (tabular file, column selections, etc)

**Comment by jkmarx** [comment]
@hackdna Is this error on the test site?

**Comment by ngehlenborg** [comment]
Yes, it is on the test site. I was able to reproduce this.

**Comment by jkmarx** [comment]
https://beta.stemcellcommons.org/data_set_manager/import/   ??

**Comment by ngehlenborg** [comment]
@jkmarx: http://test.stemcellcommons.org/data_set_manager/import/

**Comment by jkmarx** [comment]
@hackdna @ngehlenborg  Is this really a critical bug? Persisting data from this tab switch seems more of an enhancement. I'm unsure why someone would upload a file and then switch to the data upload file form.

**Comment by ngehlenborg** [comment]
Definitely very important, maybe not critical. People should be able to add their meta data, then upload files, and switch back and forth between the two, as that is part of the same process. It used to work in the old UI.

**Comment by hackdna** [comment]
Rule #1: do not lose user data. This is a bug that was uncovered when doing user testing (with an actual user), so needs to be fixed ASAP.

**Comment by flekschas** [comment]
@nils This is more a feature than a bug (at least implementation-wise). When switching between tabs you load a different controller and the old controller's state is lost. One way to achieve persistency is to implement a state service with the only purpose of saving the metadata table. Another way could be to utilize _RefineryImportWrapperCtrl_ which is the parent controller of both tab-specific controllers and simply store the data there.

**Comment by hackdna** [comment]
Having two tabs was confusing for the user too. We should probably convert the data file upload tab to a pop up or overlay. This is what AWS implements for uploads to S3.

**Comment by jkmarx** [comment]
@hackdna I propose we move this to next and discuss it as part of the ui meeting tomorrow. A new milestone starts on Tues, so it can be resolved then.

**Comment by jkmarx** [comment]
We are holding off on creating services until after the file browser is in testing mode. Meanwhile, an alert will pop up when a user has tabular file in preview.

**Comment by jkmarx** [comment]
Added alert https://github.com/parklab/refinery-platform/commit/55e20eeebec00e5e617923a36f844bee4c2e027f
