### ISSUE TITLE
Impossible to upload more than one data file

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1292]
Commit: 6336f5926b11d46235b5a15ab4a4dc774e9fd492

### Steps to reproduce
1. Upload a data file using the data file upload form
1. Add another file and click either the corresponding "Start" button or the common "Start upload" button

### Observed behavior
File is not uploaded, BAD REQUEST error message displayed in the browser. Error logged in the browser console:
```
POST http://192.168.50.50/data_set_manager/import/chunked-upload/ 400 (BAD REQUEST)
Error uploading file: BAD REQUEST - error
```
and in the Apache log:
```
192.168.50.1 - - [02/Aug/2016:18:04:52 -0400] "POST /data_set_manager/import/chunked-upload/ HTTP/1.1" 400 260 "http://192.168.50.50/data_set_manager/import/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
```

### Expected behavior
File is uploaded, no errors displayed.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by ngehlenborg** [comment]
@hackdna and @jkmarx: I tried to reproduce this on test.stemcellcommons.org but don't see the error described above.

**Comment by jkmarx** [comment]
Locally, I didn't have any issues.

**Comment by hackdna** [comment]
I am able to reproduce this reliably. What size are your files?

**Comment by jkmarx** [comment]
@hackdna Please include the files you used to steamline things a bit.

**Comment by hackdna** [comment]
@jkmarx please answer the question

**Comment by jkmarx** [comment]
@hackdna 134 bytes, 3kb, 7kb

**Comment by hackdna** [comment]
Thanks. You need to use actual data files like: http://data.cloud.refinery-platform.org/?prefix=data/sample-data/E-GEOD-23694/

**Comment by jkmarx** [comment]
The failures have the same error you posted above.

<img width="1412" alt="screen shot 2016-08-03 at 11 04 02 am" src="https://cloud.githubusercontent.com/assets/9956764/17370445/112f3642-596a-11e6-9240-d90e58f48c95.png">
<img width="1427" alt="screen shot 2016-08-03 at 11 01 06 am" src="https://cloud.githubusercontent.com/assets/9956764/17370444/112deeae-596a-11e6-936f-ed4866399ba1.png">
<img width="1409" alt="screen shot 2016-08-03 at 10 58 20 am" src="https://cloud.githubusercontent.com/assets/9956764/17370443/11268308-596a-11e6-966d-412f499a6f4e.png">

**Comment by ngehlenborg** [comment]
I get the same problem when I try to upload both files "at once", i.e. I added both at the same time and used the global "Start upload" button.

**Comment by hackdna** [comment]
It looks like the files below the [chunk size](https://github.com/parklab/refinery-platform/blob/2982a0ebd78db01bbb679647622fd601dda27173/refinery/ui/source/js/data-set-import/settings.js#L11) are unaffected.

**Comment by jkmarx** [comment]
@hackdna FYI, I tested with Fritz's latest.

**Comment by ngehlenborg** [comment]
![screen shot 2016-08-03 at 11 29 42 am](https://cloud.githubusercontent.com/assets/1216518/17371400/b416522a-596d-11e6-9695-e9e0758fd7e3.png)

I second the suspicion that this has to do with the chuck size. After the first file, subsequent files fail once they reach the chunk size.

**Comment by jkmarx** [comment]
@hackdna Let me look and see what's happening on the front end. I'm not familiar with the code so give me extra time to get familiar with it.

**Comment by ngehlenborg** [comment]
![screen shot 2016-08-03 at 11 35 46 am](https://cloud.githubusercontent.com/assets/1216518/17371613/8244534a-596e-11e6-9969-c5ff4959c943.png)

Once a file greater than the chunk size is uploaded, subsequent uploads fail, even if they are smaller than the chunk size.

**Comment by jkmarx** [comment]
@ngehlenborg See my first set of images above.

**Comment by hackdna** [comment]
There's a description of the chunked upload process here: https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads

**Comment by jkmarx** [comment]
failed request payload
```------WebKitFormBoundarynMpvXaopj5SfATB2
Content-Disposition: form-data; name="upload_id"

27ca8bf2b4224215899e66969df1ce84
------WebKitFormBoundarynMpvXaopj5SfATB2
Content-Disposition: form-data; name="files[]"; filename="SRR065547.fastq"
Content-Type: application/octet-stream


------WebKitFormBoundarynMpvXaopj5SfATB2———```

accepted request payload
```------WebKitFormBoundaryj7I8kdB8NTh6Dkgj
Content-Disposition: form-data; name="upload_id"

27ca8bf2b4224215899e66969df1ce84
------WebKitFormBoundaryj7I8kdB8NTh6Dkgj
Content-Disposition: form-data; name="upload_id"

27ca8bf2b4224215899e66969df1ce84
------WebKitFormBoundaryj7I8kdB8NTh6Dkgj
Content-Disposition: form-data; name="files[]"; filename="SRR065546.fastq"
Content-Type: application/octet-stream


------WebKitFormBoundaryj7I8kdB8NTh6Dkgj--```

**Comment by jkmarx** [comment]
Error response: '{"detail": "Upload has already been marked as \"complete\""}'

**Comment by hackdna** [comment]
OK, this indicates there is a mixup (re-use?) of upload IDs.

**Comment by jkmarx** [comment]
@hackdna Confirmed, the upload_id is not getting updated.

**Comment by jkmarx** [comment]
Seems issue maybe with
 ```
var uploadAlways = function () {
    formData.splice(1);
  };
```

 ```
var uploadAlways = function () {
    formData = formData.splice(1);
  };
```
Bug is how slice is being used. 
In javascript, "The slice() method returns a shallow copy of a portion of an array into a new array object. "

**Comment by jkmarx** [comment]
@hackdna I am going to do a bit more manual testing and will push the fix.

**Comment by jkmarx** [comment]
<img width="1418" alt="screen shot 2016-08-03 at 3 53 35 pm" src="https://cloud.githubusercontent.com/assets/9956764/17379926/85547fdc-5992-11e6-9c8f-447e7d6c498b.png">

**Comment by jkmarx** [comment]
There is still an issue with upload large files back to back, which is why I closed the previous pull request.

**Comment by jkmarx** [comment]
When upload sequential data files, the second data file chunk upload api request occurred (and failed with the same id) before the first chunk upload completed api request was sent.
