### ISSUE TITLE
Affiliation not saved during account creation

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1303]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Create an account, and be sure to include an affiliation

### Observed behavior
- After it's approved, and you log in, there is no affiliation

### Expected behavior
- The affiliation should be preserved along with the other user-supplied data

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;91hKi2NP&#x2F;305-account-registrations"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> account registrations</a>
