### ISSUE TITLE
Users should not be able to remove themselves from "Public" group

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1304]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Click "Collaboration" at the top
- In the "Groups" pane, click the gear beside "Public"
- Click "Leave"

### Observed behavior
Once this is done, the user will no longer have access to public datasets

### Expected behavior
Not sure? An error? or no gear beside "Public"?
(Before diving into this, confirm that we're modelling this appropriately... Maybe groups should only be used for restrictions, and a public dataset just has no groups? That might run into other problems, though.)

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>
