### ISSUE TITLE
"Group Editor" dialog is missing cancel button

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1305]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Click "Collaboration" at the top
- In the "Groups" pane, click the gear beside "Public" (Or beside another group: The ability to edit the public group might be removed. See #1304)
- You'll get a dialog that looks like this:
![screen shot 2016-08-08 at 11 37 13 am](https://cloud.githubusercontent.com/assets/730388/17485994/2754bd74-5d5d-11e6-8fc9-8844b64e43df.png)

### Observed behavior
There is no cancel button, though you can hit escape, or click in the background.

### Expected behavior
There is a cancel button.

**Comment by jkmarx** [comment]
@mccalluc Did you try clicking on the background?

**Comment by mccalluc** [comment]
D'oh. I had seen another dialog with a cancel, so I has expecting it here. Perhaps close this?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by jkmarx** [comment]
I'll add an X on the upper right corner.
