### ISSUE TITLE
Firefox: "Search" placeholder positioned too low

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1306]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- On Firefox, bring up the launch pad

### Observed behavior
- the "Search" placeholder is positioned such that the lower halves of the letters are invisible. 
![screen shot 2016-08-08 at 11 55 41 am](https://cloud.githubusercontent.com/assets/730388/17486740/ef3cf8e0-5d5f-11e6-905a-03d753563707.png)

### Expected behavior
- Should render the same as on Chrome.
(But my real question is whether this is even worth reporting? Maybe the policy is to not even bother with UI quirks on FF, as long as the basic functionality is there? Similarly, are we interested at all in awkward responsive UI issues in narrow windows / mobile?)

**Comment by mccalluc** [comment]
As of 30c8f758de66f6438ec2436bc52a790e971f3470, the UI on FF here has gotten a little worse:

<img width="137" alt="screen shot 2016-09-15 at 8 50 09 am" src="https://cloud.githubusercontent.com/assets/730388/18550370/7bd18788-7b21-11e6-9547-5bc194cec48b.png">

The magnifying glass is now positioned too high, as well.

**Comment by scottx611x** [comment]
@mccalluc Probably related to #1399

**Comment by scottx611x** [comment]
Closed per #1407

**Comment by scottx611x** [comment]
#1407 fixed this issue in Chrome and Safari, but re-opening as the issue persists in `Firefox 49` on `Ubuntu 16.04 LTS and OS X 10.11`
