### ISSUE TITLE
stalls if required fields on import not given

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1308]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Select any csv to upload. (It doesn't matter what.)
- Do not fill in any other fields

### Observed behavior
The whole dialog greys out, and there's a blinking dot, but nothing else happens.

### Expected behavior
There should be better input validation: Perhaps some highlighting of the required fields which are blank, or whatever idiom is best in this framework.

![screen shot 2016-08-08 at 1 31 17 pm](https://cloud.githubusercontent.com/assets/730388/17489547/7d10a6ce-5d6c-11e6-9b17-5d7e210ef514.png)

**Comment by ngehlenborg** [comment]
Did you select a source index column or data file column?

**Comment by mccalluc** [comment]
I've retitled: The problem is that we are not validating for the two required fields. When I specify "a" for both, I can get to the next screen.

**Comment by jkmarx** [comment]
@ngehlenborg @mccalluc With the data set import pull request #1345 , there's a default selection and no blank spaces. This should be resolved.

**Comment by jkmarx** [comment]
Need to add form validation for the required fields. I thought this was already implemented, so my mistake.
