### ISSUE TITLE
"Permission Editor" "Save" does not close modal

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1311]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Go to a data set this is shared with you
- Click Share
- Click Save

### Observed behavior
Nothing happens

### Expected behavior
- either an error message
- or it should take effect
- or if it's a permissions issue, I should not have gotten this far?

**Comment by ngehlenborg** [comment]
You should not be allowed to share a data set that has been shared with you (i.e., you are not the owner).

**Comment by mccalluc** [comment]
For reference, this error is in the JS console when I try to save:
```
Object { data: "", status: 401, headers: dd/<(), config: Object, statusText: "UNAUTHORIZED" }
```

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by jkmarx** [comment]
- [ ] disable sharing link if not owner
