### ISSUE TITLE
UI suggests Data set files can be reordered, but they can't

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1313]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- Pick a data set
- Go to the File Browser
- Click and drag the three bars on the left side of the grid

### Observed behavior
Nothing happens. (In contrast, analyses can be reordered with drag and drop.)

### Expected behavior
Either they should be reordered, or we should get rid of the drag target.

**Comment by ngehlenborg** [comment]
@jkmarx: I agree with @mccalluc - we should get rid of this in file browser v2.

**Comment by jkmarx** [comment]
This issue is resolved in the data set 2 browser. The drag/drop capabilities are used with the paired input workflows.
