### ISSUE TITLE
Saved filter selector should be reset when "reset" is clicked

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1314]
Commit: 33de42c5dcd1e22fe17e4
### Steps to reproduce
1. Bring up the files tab for a data set
2. Select some subset using the filters
3. Save the subset
4. Click reset
### Observed behavior

The name of the saved subset remains in selector above
### Expected behavior

Since we have removed those filters, the selector should be reset, probably to "current selection". You could imagine coming back to your screen after stepping away and being confused by the inconsistency.

**Comment by jkmarx** [comment]
This is not an issue in the data set 2 browser. The node group and selection gets reset.
