### ISSUE TITLE
Data sets filter not available when not logged in

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1316]
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
1. Log out
2. Click the filter icon under Data Sets

### Observed behavior
The box expands a few pixels, but there's nothing there

### Expected behavior
Maybe the filter icon just should not be shown, if there are no options under it when not logged in?

![screen shot 2016-08-08 at 5 45 15 pm](https://cloud.githubusercontent.com/assets/730388/17497454/ed021a76-5d8f-11e6-96c2-4937e7b14695.png)

**Comment by ngehlenborg** [comment]
@flekschas: Can we easily deactivate the filter menu when the user is not logged in? Right now the filters only work for users that are logged in (although that might change in the future).

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2q6R8R6c&#x2F;315-fix-data-set-browsing-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> fix data set browsing bugs</a>
