### ISSUE TITLE
Data Import Update Text Order

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1321]
- [x] Reorder tab and comma separation fields (tab, comma, other)
- [x] Create sections in metadata configuration, see below

### Required
Title
Sample identifier (renamed from Source index column)
Data file
Organism (renamed from Species)
### Advanced
Auxiliary file
Base path
Annotation file
Genome build
Make file permanent (download files from remote source)
### Publishing
URL shortcut
Make data public

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by jkmarx** [comment]
@ngehlenborg Comments on html?
<img width="1413" alt="screen shot 2016-08-09 at 2 08 19 pm" src="https://cloud.githubusercontent.com/assets/9956764/17528752/9f172c48-5e3e-11e6-8424-85523b709848.png">

**Comment by ngehlenborg** [comment]
Very nice. The description below the "Metadata Import Configurations" text should go. Make the required fields bold or add asterisk to indicate that they are required. Maybe rename "Metadata Import Configurations" to "Import Settings" and move "Publishing" section above "Advanced".  @sjhosui - any thoughts?

**Comment by sjhosui** [comment]
Nice progress, thanks. I agree with Nils' suggestions.

**Comment by jkmarx** [comment]
<img width="1400" alt="screen shot 2016-08-09 at 2 59 10 pm" src="https://cloud.githubusercontent.com/assets/9956764/17529598/ee090fda-5e41-11e6-8dff-87a5c1b8accf.png">

**Comment by ngehlenborg** [comment]
Almost! Can you change "Abbreviation" to "URL Shortcut"?

**Comment by ngehlenborg** [comment]
Btw, did you make "tab" the default selection?

**Comment by jkmarx** [comment]
Yes and it's first. There wasn't much to it, but I can show you a screenshot if you like.
