### ISSUE TITLE
Data Import Add Link to Metadata sample

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1322]
- [x] Add text linking to metadata example
- [x] Add file to project
- ~~[ ] Add metadata example to wiki~~

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by jkmarx** [comment]
@sjhosui @ngehlenborg Is there an example in the wiki already?

**Comment by ngehlenborg** [comment]
@jkmarx: Here is the example file (as discussed with @sjhosui): 
[refinery-sample-metadata.txt](https://github.com/parklab/refinery-platform/files/411054/refinery-sample-metadata.txt)

You can rename the extension to `.tab` (I was not able to attach the file here with that extension, Github only accepts `.txt`).

**Comment by jkmarx** [comment]
@ngehlenborg @sjhosui Please comment/suggest changes.
<img width="572" alt="screen shot 2016-08-11 at 11 58 37 am" src="https://cloud.githubusercontent.com/assets/9956764/17595415/0464a8aa-5fbb-11e6-9a5e-006ace89c7d2.png">

**Comment by ngehlenborg** [comment]
I am not sure if the lightning icon is the best choice. We sometimes use it to indicate that something is missing (e.g. a file is not available in the file browser). Can we come of with a universal "example" icon? How about http://fontawesome.io/icon/info-circle/?


Please change the text to "Download an example of a meta data tabular file."

**Comment by sjhosui** [comment]
Agree with the change in icon to the information icon, or alternatively, the download icon. Can we simplify the text further to "Download an example meta data tabular file"?

**Comment by jkmarx** [comment]
@ngehlenborg @sjhosui I think the file download is more explicit, but can switch to the info if y'all prefer. 
<img width="546" alt="screen shot 2016-08-11 at 1 37 42 pm" src="https://cloud.githubusercontent.com/assets/9956764/17598486/cc960a50-5fc8-11e6-84f3-6115468b982f.png">
