### ISSUE TITLE
Redundant error messages when given email is invalid

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1332]
Commit: 87dd57b212516739ebe7ccb48617e3554e9e40a7

### Steps to reproduce
1. Collaboration -> Members -> +
2. Type "asdf" as the email
3. Click "Send Invite"

### Observed behavior
- For a moment, there is a input validation popup, 
- and then at the same time there is another error modal that overlaps the first modal
- and then the validation popup disappears a second later: It's not on screen long enough to be read.

<img width="545" alt="screen shot 2016-08-10 at 11 12 02 am" src="https://cloud.githubusercontent.com/assets/730388/17559473/5e69c4c2-5eec-11e6-9209-87449a2552ca.png">

### Expected behavior
Either
- When validation fails, the form can't be submitted
- or, the error modal provides the information the validation popup provides now?

(Note: if you just cancel, you also get the validation popup for an instant: Doesn't get in the way, but awkward in the same way, and a fix might have both in mind.)

See also: #1333

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>
