### ISSUE TITLE
"Invite New Member" with bad email / hit return / no error

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1333]
Commit: 87dd57b212516739ebe7ccb48617e3554e9e40a7

### Steps to reproduce
1. Collaboration -> Members -> +
2. Type "asdf" as the email
3. Hit return

### Observed behavior
- For an instant, there is a validation popup, but then both it and the modal disappear.

### Expected behavior
- Error messages should stay on screen until user clears them
- Hitting return should do the same thing as clicking a "Send Invite"

See also: #1332

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by jkmarx** [comment]
<img width="601" alt="screen shot 2016-09-29 at 4 59 37 pm" src="https://cloud.githubusercontent.com/assets/9956764/18972195/325daca8-8666-11e6-8dd3-3de24be447c7.png">

**Comment by hackdna** [comment]
Per our [style guide](https://github.com/parklab/refinery-platform/wiki/coding-style-guide#miscellaneous): "Use IANA-managed Reserved Domains in documentation and tests (example.com and example.org)." For example: username@example.org.

Also, what are the rules used to determine if an email address has the correct format?

**Comment by jkmarx** [comment]
https://docs.angularjs.org/api/ng/input/input%5Bemail%5D

**Comment by hackdna** [comment]
This allows email addresses in the form "user@example" (https://github.com/angular/angular.js/issues/5899) which is [technically valid](https://en.wikipedia.org/wiki/Email_address#Syntax) but is that the the behavior we want?
