### ISSUE TITLE
Data Import - Reorganize Tab and Content

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1336]
- [x] Move optional raw data upload beneath options but before ISA-tab upload
- [x] Move the optional raw data upload into the tabular metadata form.
- ~~[ ] Upload raw data form first -> the tabular metadata form -> redirect to file browser~~
- [x] Move ISA-tab upload to a new tab

- [x] Rename tabs, Tabular Metadata and ISA-Tab Metadata
- [x] Change download text to tabular metadata file
- [x] Update required pre-select to [1] datafile and [2] for species
- [x] Update section names to Provide Metadata file, Configure Metadata Import, and Optional: Upload Data Files
- [x] Make clear button more pronounced
- [x] Remove (e.g .csv, .tsv, .txt)
- [x] Radio button lines horizontally
- [x] Change color of buttons in the data upload section to default (gray).
- [x] Deactivate the blue "Start Import" button until any data file has been uploaded (we should check for running ones only - those that have been added but for which the user never started the upload should maybe be ignored since there is currently no way to remove a file once it has been added).
- [x] Renaming the "Start Import" button into "Upload Data Set"
- [x] Add alert when people start uploading datasets when files are still queued.

**Comment by jkmarx** [comment]
@ngehlenborg @sjhosui 

<img width="565" alt="screen shot 2016-08-11 at 3 49 31 pm" src="https://cloud.githubusercontent.com/assets/9956764/17602580/42f080a6-5fdb-11e6-8bad-0ca8da7eaf8a.png">
<img width="628" alt="screen shot 2016-08-11 at 3 49 25 pm" src="https://cloud.githubusercontent.com/assets/9956764/17602581/42fd8f44-5fdb-11e6-856b-ddb981741fba.png">

**Comment by jkmarx** [comment]
There are ui issues when users are trying to do both, upload tabular files and upload data files.

**Comment by ngehlenborg** [comment]
Can you clarify the UI issues that you are running into?

**Comment by jkmarx** [comment]
User is uploading both data files and an isa-tab file. After isatab file completes there's a redirect, which can occur during the data file upload.

**Comment by jkmarx** [comment]
With the two tabs, we still have the issue with the persistent data.

**Comment by ngehlenborg** [comment]
I think this can mostly be addressed by warning people about navigating away from the tab/page while they upload or preview a file. There should be an alert with a warning “You have unsaved changes on this tab. You will lose any entered information unless you finish your upload.” (or something like that).

**Comment by jkmarx** [comment]
@ngehlenborg Do we want users to be able to upload data files and metadata files at the same time?

**Comment by ngehlenborg** [comment]
Yes, but not ISA-tab and data at the same time for now.

**Comment by jkmarx** [comment]
So then we'll need to get rid of the automatic redirect after a tabular file upload.

**Comment by jkmarx** [comment]
@ngehlenborg Please confirm, for the data file upload we will remove the start import and cancel import buttons. The data uploads will occur after the start import button is pressed and then the tabular metadata.
<img width="1419" alt="screen shot 2016-08-12 at 1 06 44 pm" src="https://cloud.githubusercontent.com/assets/9956764/17630519/acc600de-608d-11e6-8b16-1f868b8fe8a3.png">

**Comment by jkmarx** [comment]
Or after a user adds files, we can grey out the start import until all the files are uploaded.

**Comment by ngehlenborg** [comment]
1. Change color of buttons in the data upload section to default (gray).
 1. Deactivate the blue "Start Import" button until any data file has been uploaded (we should check for running ones only - those that have been added but for which the user never started the upload should maybe be ignored since there is currently no way to _remove_ a file once it has been added).
 1. I suggest renaming the "Start Import" button into "Upload Data Set"

**Comment by jkmarx** [comment]
<img width="809" alt="screen shot 2016-08-15 at 10 13 47 am" src="https://cloud.githubusercontent.com/assets/9956764/17667020/fde4438c-62d0-11e6-9149-9995f3eba512.png">

**Comment by ngehlenborg** [comment]
Great! I like the read "x".

**Comment by jkmarx** [comment]
<img width="1173" alt="screen shot 2016-08-15 at 10 16 28 am" src="https://cloud.githubusercontent.com/assets/9956764/17667133/9787bb36-62d1-11e6-9d1f-e63a0bfea805.png">

**Comment by jkmarx** [comment]
@ngehlenborg I went back and changed it to orange, since all the cancel buttons on the page are orange. Thoughts?

**Comment by ngehlenborg** [comment]
Orange is fine, although I am not sure if all the cancel buttons need to be orange. What do you think @jkmarx?

**Comment by jkmarx** [comment]
@ngehlenborg @sjhosui Please notice the warning next to the Upload Dataset Button. Is this sufficient? 
<img width="1259" alt="screen shot 2016-08-15 at 3 25 53 pm" src="https://cloud.githubusercontent.com/assets/9956764/17676507/e118b3c4-62fc-11e6-8824-f9fc37feb25f.png">

### Button is inactive during any uploads.
<img width="1393" alt="screen shot 2016-08-15 at 3 26 38 pm" src="https://cloud.githubusercontent.com/assets/9956764/17676512/e498b4a4-62fc-11e6-8f4c-abc8da4ede92.png">

<img width="1387" alt="screen shot 2016-08-15 at 3 27 52 pm" src="https://cloud.githubusercontent.com/assets/9956764/17676515/e8afe9ae-62fc-11e6-8ab6-d7fdc82f4c61.png">
