### ISSUE TITLE
Separate selectors for UI state and actions could be confusing

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1339]
Commit: 87dd57b212516739ebe7ccb48617e3554e9e40a7 

### Steps to reproduce
1. Bring up the Files tab and click visualize.

<img width="332" alt="screen shot 2016-08-12 at 1 31 27 pm" src="https://cloud.githubusercontent.com/assets/730388/17631395/ea373b6e-6091-11e6-8d26-8e704a625acf.png">

### Observed behavior
I'm concerned that having these two parallel selectors could be confusing. The currently selected files are not the files that the action will be taken on.

### Expected behavior
Could the visualization always be done on the active set? ie, the behavior you get if "Current Selection" is selected on the left, except we just wouldn't show the selector on the left.

**Comment by jkmarx** [comment]
This issue is resolved in the data set 2 browser layout update. Pull request #1413
