### ISSUE TITLE
System Administrator email missing

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1340]
Commit: 87dd57b212516739ebe7ccb48617e3554e9e40a7

### Steps to reproduce
1. Go to https://test.stemcellcommons.org/not-a-page

### Observed behavior
"If you think you reached this page in error, then please contact your System Administrator.", with `href="mailto:?Subject=Refinery%20Error"`

### Expected behavior
Either require the email as part of the configuration... or, perhaps simpler, leave it to the user to figure out who to contact, and remove this link (and check if anything else uses it). One less thing to worry about.

**Comment by mccalluc** [comment]
Error in template, we think. Take the first one. (It's a list.)

**Comment by hackdna** [comment]
Note that ADMINS setting is a tuple: https://docs.djangoproject.com/en/1.7/ref/settings/#admins
