### ISSUE TITLE
Set selector should change on save

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1341]
Commit: 87dd57b
### Steps to reproduce
1. From data_sets2, click save
2. Enter a name
### Observed behavior

The selector above does not change
### Expected behavior

Analogous to saving a document, if the selected named set above changed to match, that would be nice: It's a confirmation to the user that something has changed. Or you could construe it as a bug that the named set selected there does not always agree with what you have selected on screen: It's only changes that are noted.

**Comment by jkmarx** [comment]
@mccalluc @ngehlenborg  I didn't realize we were debugging the dataset 2 browser.

**Comment by ngehlenborg** [comment]
We probably didn't mention to @mccalluc that it is still under heavy development?

**Comment by mccalluc** [comment]
Sorry: I started to file a bug on data_sets1, which has some even weirder behaviors, and thought to check data_sets2, but I shouldn't have gotten distracted by this in the first place.
