### ISSUE TITLE
FASTAs + Cytoband -> S3?

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1344]
IGV.js needs FASTA files (and ideally FASTA indexes). I don't think this is hard, but it will take some time so I wanted to confirm that this approach seems good. If it does, I'll probably wrap it up in a script that can be run per organism.

- [ ] Identify organisms, or actually the genome assemblies of interest: Can I take the list that comes up in the UI as the target? D. melanogaster (dm3), S. pombe (spombe_1.55), C. elegans (ce6), H. sapiens (hg19), D. rerio (danRer7), M. musculus (mm9). If we have a system, I don't think adding to this list should be hard.
- [ ] Genome not available error: Are there strong feelings about how any errors would be presented? Right now, I'd just do whatever is easiest, and I don't know whether that would mean a popup in the IGV, or whether we catch it when validating the input...
- [ ] We get the FASTA files from [UCSC](http://hgdownload.cse.ucsc.edu/goldenPath/danRer6/bigZips/), where it looks like the chromosomes are already concatenated, and directories are named with the convention we're already using? 
- [ ] Run [faidx](http://www.htslib.org/doc/faidx.html) on FASTA files.
- [ ] Move FASTA and FASTA index to S3
- [ ] If this can be wrapped up as a script, where should it go in the project? 

Looked at getting FASTA from NIH, but more questions about their data:
- [ ] Figure out what the correspondence is between our assembly identifiers and the information on ftp://ftp.ncbi.nih.gov/genomes/D_rerio/README_CURRENT_RELEASE, as an example: "danRer7" is not on that page. If we wanted anything other than the latest assembly, where would I find that at NCBI?
- [ ] Download and concatenate FASTA files for organism of interest. ftp://ftp.ncbi.nih.gov/genomes/D_rerio/Assembled_chromosomes/seq/ (Hoping that the directory structures are parallel for different organisms, but I'm not sure of that.)

and

- [ ] Cytoband: For hg, [UCSC](http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/) has cytoBand.txt.gz and cytoBandIdeo.txt.gz. One just seems to have more detail than the other? Does it matter which we take?

End goal is https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=data.cloud.refinery-platform.org&prefix=data/igv-reference/danRer7/ with danRer7.fasta and danRer7.fai

**Comment by mccalluc** [comment]
Not all the data I want is where I was hoping to find it:
- dm3: http://hgdownload.cse.ucsc.edu/goldenPath/dm3/bigZips/
  - genome in 2bit format
  - cytoband in http://hgdownload.cse.ucsc.edu/goldenPath/dm3/database/
- spombe_1.55: no pombe listed under yeasts
- ce6: http://hgdownload.cse.ucsc.edu/goldenPath/ce6/bigZips/
  - genome in 2bit format
  - no cytoband
- hg19: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/
  - genome in 2bit format
  - cytoband in http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/
- danRer7: 
  - genome in fasta
  - cytoBandIdeo.txt.gz but no plain cytoband
- mm9: http://hgdownload.cse.ucsc.edu/goldenPath/mm9/bigZips/
  - genome in 2bit format
  - cytoband in http://hgdownload.cse.ucsc.edu/goldenPath/mm9/database/

**Comment by drj11** [comment]
Your general approach seems reasonable.

Sorry about the data.

Bear in mind that this is somewhat site specific. Different installations my want different organisms/assemblies and they may want to get them from different places. So (as always) exercise best judgement and do something reasonable; and, make sure it's document so that people that want to do less common things can still do it.

**Comment by mccalluc** [comment]
ok, I checked in a script to my branch that does most of the work. Outstanding questions:
- If there isn't a cytoband, what then? 
  - Tweak IGV.js to make it fail more gently?
  - Put stub files on S3 so at least there isn't a 404?
  - Have metadata somewhere that tells us not to expect a cytoband?
- Where should it pull from? Right now, it's a hard-coded S3, but if other users might be hosting their reference data in other places, where do we configure that?

**Comment by ngehlenborg** [comment]
@mccalluc: I created a new issue (#1348) - does that help with your thinking about this? One thing that #1348 would not address is how to deal with a lack of cytoband information in IGV.js. It would be nice if we could make it fail gently because this is often not even needed.

For now you can focus on human (hg19) and mouse (mm10). I expect that all required data for those genome builds is available.

**Comment by mccalluc** [comment]
I think the original questions I had in mind here are resolved: We've got the reference data, and can source it in a replicable way.
