### ISSUE TITLE
Get a range of sample data for IGV.js?

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1347]
I need a range of data to check IGV.js. File types (https://github.com/igvteam/igv.js/wiki/Tracks):
- [x] annotation: BED
  - <img width="282" alt="screen shot 2016-08-19 at 3 26 47 pm" src="https://cloud.githubusercontent.com/assets/730388/17821806/8e3e17d4-6621-11e6-9ea5-0b7317ae681e.png">
- [x] annotation: GFF
  - <img width="237" alt="screen shot 2016-08-19 at 4 46 00 pm" src="https://cloud.githubusercontent.com/assets/730388/17823826/9cbf3224-662c-11e6-90fa-e5b28fc46278.png">
  - This is GFF3: Others may fail silently. Do we need to try to sniff GFF2?
- [x] wig: WIG 
  - <img width="267" alt="screen shot 2016-08-19 at 2 47 23 pm" src="https://cloud.githubusercontent.com/assets/730388/17820680/fcb02186-661b-11e6-99d7-5b3f50a7e616.png">
- [x] wig: bigWig
  - <img width="241" alt="screen shot 2016-08-19 at 2 18 22 pm" src="https://cloud.githubusercontent.com/assets/730388/17819841/f032266a-6617-11e6-97ec-af68f539c724.png">
- [x] wig: bedGraph
  - <img width="310" alt="screen shot 2016-08-19 at 3 46 04 pm" src="https://cloud.githubusercontent.com/assets/730388/17822280/3e0fa234-6624-11e6-868f-5c8dbb723fd4.png">
- [ ] alignment: BAM
  - Requires BAI. See discussion below.
- [x] variant: VCF
  - <img width="253" alt="screen shot 2016-08-19 at 4 03 54 pm" src="https://cloud.githubusercontent.com/assets/730388/17822738/b7845f5e-6626-11e6-973e-5390be75d77f.png">
  - ... but the format is complicated enough that this is probably not testing much.
- [x] seg: SEG
  - <img width="340" alt="screen shot 2016-08-19 at 4 21 06 pm" src="https://cloud.githubusercontent.com/assets/730388/17823191/46870bb4-6629-11e6-9b0f-0181990f76e4.png">

I would also like
- [ ] to see the species/genome come with the data: I've been selecting it manually up to this point.
- [ ] to clarify what genomes need to be supported, and what the behavior should be if not supported.
- [ ] to clarify desired behavior if multiple tracks are selected: Does user need to be able to control order?

**Comment by ngehlenborg** [comment]
If you haven't seen this, it will be useful: http://software.broadinstitute.org/software/igv/FileFormats

Regarding wig: bigWig and bedGraph can be generated from based on a wig file (https://genome.ucsc.edu/goldenpath/help/bigWig.html).

@sjhosui - I am thinking we should get some standard genome annotations in GFF format (@mccalluc: do you know which version they support? there are multiple for GFF). For WIG and BED we could get ChIP-Seq data with peak calls. BAM and VCF could be 1000 Genomes and/or some cancer genomics data. I think TCGA also has some SEG files. Or do you think we can get all data types for say GM12878 or K562 (@mccalluc: these are human cell lines used by ENCODE:  https://www.genome.gov/26524238/encode-project-common-cell-types/)

**Comment by ngehlenborg** [comment]
Let's try to collect some sample data file from ENCODE and make a tabular meta data file that uses attributes roughly equivalent with the ones on the ENCODE website:

https://www.encodeproject.org/matrix/?type=Experiment&replicates.library.biosample.donor.organism.scientific_name=Homo+sapiens&files.file_type=bam&files.file_type=bigWig&files.file_type=gff+gff3&files.file_type=vcf&replicates.library.biosample.biosample_type=immortalized+cell+line&x.limit=&assembly=hg19

**Comment by mccalluc** [comment]
If you try to visualize just a .bam file, there will be a 404: it looks for a .bam.bai in addition to the file you explicitly list. Possible fixes:
- Make sure the .bam.bai is always available? But if we're pointing at external URLs we don't really control the situation, so ...
- Check for the file on the server, but inserting an extra round trip really slows down first-byte delivery, or
- Check for the file on the client, either before launching IGV, or figure out how to override their unhelpful error message.

**Comment by scottx611x** [comment]
@mccalluc Chuck, I'm currently working on the functionality to address the above^^^

**Comment by sjhosui** [comment]
I like the idea. For the Stem Cell Commons, I'd like to see data for the hESC samples from ENCODE.

**Comment by mccalluc** [comment]
The original scope of this is satisfied.
