### ISSUE TITLE
Waving help in banner is distracting after a while

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1393]
Commit: fca97c904be407c6619608e13437f25a9fc9e979 

### Steps to reproduce
1. FF 47.0.1
2. In the banner

### Observed behavior
1. It never seems to stop waving, even after I have completed the tutorials

### Expected behavior
Perhaps the animation should stop after it is clicked on once?

**Comment by scottx611x** [comment]
@mccalluc This behavior persists for a users first login. If you logout and log back in you should see the movement go away

**Comment by mccalluc** [comment]
That's probably sufficient? I'll close.
