### ISSUE TITLE
Strange completion percentage

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1394]
Commit: fca97c9
### Steps to reproduce
1.  FF 47.0.1
2. but I do not have a reproducer

### Observed behavior
1. On first clicking the gear for recent analyses in the upper right I saw:

<img width="458" alt="screen shot 2016-09-09 at 11 01 27 am" src="https://cloud.githubusercontent.com/assets/730388/18392021/32078c3a-767e-11e6-9343-2588e73f9303.png">
2. A few seconds later:

<img width="462" alt="screen shot 2016-09-09 at 11 02 14 am" src="https://cloud.githubusercontent.com/assets/730388/18392064/5ecb0b20-767e-11e6-8908-bbd9640a9219.png">
3. A minute later:

<img width="463" alt="screen shot 2016-09-09 at 11 08 04 am" src="https://cloud.githubusercontent.com/assets/730388/18392084/69ed9a36-767e-11e6-9c32-09b1a37f294e.png">

### Expected behavior
Completion should start at 0% and go up. Perhaps the denominator isn't be calculated correctly at the start?

**Comment by ngehlenborg** [comment]
Number issue (5000%) is new but the formatting is related to #1317.
