### ISSUE TITLE
Shortcut not validated for being alphanumeric + "_"

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1395]
Commit: fca97c904be407c6619608e13437f25a9fc9e979

### Steps to reproduce
1. Upload data
2. In the public shortcut field, include an invalid character

### Observed behavior
1. No error: The bad string seems to have been saved:

<img width="115" alt="screen shot 2016-09-09 at 11 38 30 am" src="https://cloud.githubusercontent.com/assets/730388/18393053/0b41058c-7682-11e6-8fa3-cb764ea90f24.png">

### Expected behavior
1. Input validation error: The user may not continue until it is corrected.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>
