### ISSUE TITLE
Providing a shortcut URL implies public?

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1396]
Commit: fca97c904be407c6619608e13437f25a9fc9e979

### Steps to reproduce
1. Upload data
2. Specify a shortcut url
3 *but* do not check public

### Observed behavior
1. The data set is public

### Expected behavior
This might be as designed. Beside the checkbox there's a warning: "Use this feature with care"... perhaps just place the warning at the top of the section to make clear that it applies to both? Or just get rid of the checkbox? To make it public you give it a public name.

**Comment by ngehlenborg** [comment]
This should not make the data set public. Can you confirm that it indeed happens? If so, please label as important bug.

**Comment by ngehlenborg** [comment]
We should add "Providing a shortcut does not make the data set public." to the help text.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cos9jM49&#x2F;304-data-set-sharing-collaboration"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> data set sharing &#x2F; collaboration</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GoXu66WF&#x2F;295-improve-data-set-import-form"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> improve data set import form</a>

**Comment by mccalluc** [comment]
Unable to replicate. I may have been confused to begin with, or it may have been fixed.
