### ISSUE TITLE
Ontology Explorer doesn't work from dashboard when logged in?

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1402]
* Specific code commit: 30c8f758de66f6438ec2436bc52a790e971f3470
* Version of the web browser and OS: FF 42.0.1 / Chrome 52.0.2743.116
* Environment where the error occured: test.stemcellcommons.org: 

### Steps to reproduce
Please list all the actions and the input data used:

1. Without logging in, click explore on the homepage.
1. An Ontology Explorer is revealed on the right.
1. Login, and click explore on the homepage.

### Observed behavior
* No ontology explorer when logged in

### Expected behavior
* Expect at least as much functionality as when not logged in.

<img width="462" alt="screen shot 2016-09-15 at 9 12 12 am" src="https://cloud.githubusercontent.com/assets/730388/18551132/344cc6da-7b25-11e6-8966-f7ee353f0049.png">

**Comment by scottx611x** [comment]
@mccalluc This is probably due to your user not existing at the time of the ontoloy/annotations install. 

Although, with this being said, we should probably update neo4j whenever a new user is added.

**Comment by scottx611x** [comment]
This has been addressed as of commit: df17f703ed6fd786acafca9ba272053e5583dcdc
