### ISSUE TITLE
Delete Sphinx docs directory

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#1431]
`/docs` is hopelessly outdated. Let's remove it.

**Comment by hackdna** [comment]
Duplicate of #1240

**Comment by ngehlenborg** [comment]
Thnks for pointing out the duplicate. @mccalluc - this should be straightforward, we just go to make sure that none of the build and deployment steps are accessing files in this directory.

**Comment by hackdna** [comment]
@ngehlenborg can we close this since there is already an existing issue?

**Comment by ngehlenborg** [comment]
I think we can close this, right @mccalluc?

**Comment by hackdna** [comment]
Also, #304 and #482.

**Comment by ngehlenborg** [comment]
Addressed by https://github.com/parklab/refinery-platform/pull/1438
