### ISSUE TITLE
Modification Date UI Bug - Test Site

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1457]
* Specific code commit: e483ddfd9981b8f7b4f3930254482638913dba21
* Version of the web browser and OS: Chrome 53.0, Mac 10.11.4
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org/

### Steps to reproduce
Please list all the actions and the input data used:

1. Sort current data set by modification date

### Observed behavior
<img width="456" alt="screen shot 2016-10-07 at 4 32 36 pm" src="https://cloud.githubusercontent.com/assets/9956764/19204676/3937ee3e-8cac-11e6-8302-9f69220370fd.png">

### Expected behavior
Error message, perhaps N/A with tooltip no modification date

**Comment by scottx611x** [comment]
This is fixed as of commit: da2b4199996fb0f07e482bb2530f2c92cac21ca0
