### ISSUE TITLE
different species applied to same url not respected

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1464]
* Specific code commit: fad81a20e6ce1334cde6c3350a1bf89fa4b82a81 
* Version of the web browser and OS: FF 42.0.1
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Upload [same-file-different-species.txt](https://github.com/parklab/refinery-platform/files/524757/same-file-different-species.txt)
2. Map the fields appropriately

### Observed behavior
* In file browser 1, all three rows have "human" as their species

### Expected behavior
* Each row should have a different species

**Comment by mccalluc** [comment]
@ngehlenborg was simply not able to upload the file at all using Chrome, but I am not able to replicate: The behavior on Chrome doesn't seem significantly different from the behavior on FF.

**Comment by ngehlenborg** [comment]
Now that I see your example, I realize that this is intentional. Since this is the same file, it really should not be allowed to have different species assigned to it.
