### ISSUE TITLE
Dashboard Filter & Sorting Bug

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1469]
* Specific code commit: 7969dc1ab9d4f7c4af852095e4f32e6554931208 
* Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org/#/

Related to #1468 
### Steps to reproduce
Please list all the actions and the input data used:

1.  Select Owner Filter
2. Apply sorting

### Observed behavior
<img width="471" alt="screen shot 2016-10-13 at 12 03 54 pm" src="https://cloud.githubusercontent.com/assets/9956764/19356847/2e4a7650-913d-11e6-81fe-828c888cf9b9.png">
<img width="474" alt="screen shot 2016-10-13 at 12 04 12 pm" src="https://cloud.githubusercontent.com/assets/9956764/19356853/31732d9a-913d-11e6-8d1f-20c10690f4a0.png">

### Expected behavior
Either filters get deselected or filters remain applies after sorting

**Comment by jkmarx** [comment]
@flekschas When both are selected, are the filters suppose to be Public AND Own or Public OR own?

**Comment by flekschas** [comment]
@jkmarx It's always AND. The filters just send a parameter to the API backend. Not sure what's happening regarding the bug. I'd check the actual API request, the API response and the UI response.

**Comment by jkmarx** [comment]
See Issue #1468

**Comment by jkmarx** [comment]
@flekschas Did this functionality work at some point? I see the data set filter and sorting api requests are handled separately.
