### ISSUE TITLE
Dashboard: Data Cart Selection Bug

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1471]
Specific code commit: 7969dc1
Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1.  Click the calendar icon next to the modification date

### Observed behavior
Data set is favorited (star is selected).

### Expected behavior
Should only be able to favorite by selecting the star

**Comment by scottx611x** [comment]
@jmarx I can only reproduce this by clicking the actual Calendar icon, not the modification date itself.
`Firefox 49 Ubuntu 16.04 LTS`

**Comment by jkmarx** [comment]
@scottx611x Thanks, you're correct.
