### ISSUE TITLE
Tutorial Bug, launching from about page

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1472]
Specific code commit: 7969dc1
Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1.  From the about page, select launchpad tutorial
2. Wait for page to finish loading

** Also occurs from statistics page

### Observed behavior
<img width="1109" alt="screen shot 2016-10-13 at 1 49 31 pm" src="https://cloud.githubusercontent.com/assets/9956764/19360286/e4f73cf4-914b-11e6-90b4-7626797d5744.png">
<img width="1199" alt="screen shot 2016-10-13 at 1 49 24 pm" src="https://cloud.githubusercontent.com/assets/9956764/19360285/e4f18df4-914b-11e6-8302-9cd9d867b622.png">

### Expected behavior
Tutorial to work correctly

**Comment by scottx611x** [comment]
@jkmarx: I cannot reprocue this issue in `Firefox 49; Ubuntu 16.04 LTS` on test.stemcellcommons.org

**Comment by jkmarx** [comment]
@scottx611x I can only reproduce it with the dev console open...and not consistently.   I'll close it, since it's not an issue otherwise.
