### ISSUE TITLE
Tabular Meta Data File - Cancelation 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1475]
Specific code commit: 7969dc1
Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org/#/
### Steps to reproduce

Please list all the actions and the input data used:
1. Upload a tabular meta data file
2. Add some large data files
3. During the MD5 calculations, cancel upload
### Observed behavior

<img width="1385" alt="screen shot 2016-10-13 at 2 43 27 pm" src="https://cloud.githubusercontent.com/assets/9956764/19362322/565c8d2e-9154-11e6-98c6-bad2efc622c5.png">
### Expected behavior

Once cancel upload event occurs, the md5 bloop should go away.

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MD5 calculations for data file uploads should run sequentially](https://trello.com/c/zUsPpXB3/333-md5-calculations-for-data-file-uploads-should-run-sequentially)
