### ISSUE TITLE
Remove running Analysis cog animation from LaunchPad filter

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1476]
* Specific code commit: 7969dc1ab9d4f7c4af852095e4f32e6554931208
* Version of the web browser and OS:  `Firefox 49; Ubuntu 16.04 LTS`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. Perform one or more Analyses
2. Click on the Filter icon in the top right of the Analyses column on the LaunchPad

### Observed behavior
![oct-13-2016 14-47-08](https://cloud.githubusercontent.com/assets/5629547/19362358/739d83d4-9154-11e6-9309-4c23c9cdcc82.gif)

### Expected behavior
For the cog not to be spinning

**Comment by jkmarx** [comment]
#1488 Resolves this issue.
