### ISSUE TITLE
Problem loading remotely located bed file into web-based IGV

### ISSUE THREAD

**Issue by sjhosui** [parklab/refinery-platform#1487]
- Version of the web browser and OS: Chrome version 54.0.2840.59 
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): test.stemcellcommons.org
### Steps to reproduce

Please list all the actions and the input data used:
1. Navigate to https://test.stemcellcommons.org/data_sets/4d7f9959-80bc-4927-b918-69c16fd6a43c
2. Select several bed files (incl. http://stemcellcommons.org/sites/default/files/chipseq/11610/CDX2%20ChIP-seq%20in%20differentiated%20cells%20+%20Caco2%20cell%20input%20DNA.bed)
3. Select the "Visualize" tab
4. Select "Current Selection"
5. Select "Homo sapiens (hg19)" for the species
6. Click the "Web-based IGV" button
### Observed behavior

Produces error stating that files cannot be accessed.
![screen shot 2016-10-17 at 10 42 34 pm](https://cloud.githubusercontent.com/assets/697229/19462648/61e2d48a-94bc-11e6-8b32-f90ca862e750.png)
### Expected behavior
- Should display the bed files in Web-based IGV. These files are accessible via the browser and can be viewed in standalone IGV

**Comment by scottx611x** [comment]
Relevant console errors (Seems like another `Mixed Content` issue):

```
igv-1.0.1.js:15760Mixed Content: The page at 'https://test.stemcellcommons.org/visualize/genome/?node_ids=0dbf0d3d-6f11-4…df2&node_ids=1e170c96-59fc-4621-a6de-924d60df9ea3&species=H.+sapiens+(hg19)' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://stemcellcommons.org/sites/default/files/chipseq/11610/GATA6%20ChIP-seq%20in%20differentiated%20cells%20+%20Caco2%20cell%20input%20DNA.bed.idx'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ igv-1.0.1.js:15760
igv-1.0.1.js:15760 XMLHttpRequest cannot load http://stemcellcommons.org/sites/default/files/chipseq/11610/GATA6%20ChIP-seq%20in%20differentiated%20cells%20+%20Caco2%20cell%20input%20DNA.bed.idx. Failed to start loading.(anonymous function) @ igv-1.0.1.js:15760
igv-1.0.1.js:15760 Mixed Content: The page at 'https://test.stemcellcommons.org/visualize/genome/?node_ids=0dbf0d3d-6f11-4…df2&node_ids=1e170c96-59fc-4621-a6de-924d60df9ea3&species=H.+sapiens+(hg19)' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://stemcellcommons.org/sites/default/files/chipseq/11610/HNF4A%20ChIP-seq%20in%20differentiated%20cells%20+%20Caco2%20cell%20input%20DNA.bed.idx'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ igv-1.0.1.js:15760
igv-1.0.1.js:15760 XMLHttpRequest cannot load http://stemcellcommons.org/sites/default/files/chipseq/11610/HNF4A%20ChIP-seq%20in%20differentiated%20cells%20+%20Caco2%20cell%20input%20DNA.bed.idx. Failed to start loading.
```

**Comment by scottx611x** [comment]
See: #1435 and #1484

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IGV.js cannot visualize files that are served over HTTP](https://trello.com/c/L0k9NCtP/326-igv-js-cannot-visualize-files-that-are-served-over-http)

**Comment by mccalluc** [comment]
Closing as a duplicate. Trying to view HTTP data when the site is running HTTPS is the primary case in #1435.
