### ISSUE TITLE
Dashboard - Sharing Modal Bug

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1518]
* Specific code commit: e81a3d9f9f7304506ba10e7753638b5ebc5fc705 
* Version of the web browser and OS: Version of the web browser and OS: Chrome Version 54.0.2840.71
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test site, https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. Open a data set preview
2. Edit sharing permission
3. Select cancel
4. Reopen the sharing

### Observed behavior
Sharing permissions did not revert

### Expected behavior
Sharing permissions should have reverts to pre-edits.

**Comment by ngehlenborg** [comment]
I agree, it appears that the "Save" and "Cancel" buttons have no  influence on the sharing settings.

**Comment by jkmarx** [comment]
@ngehlenborg Are we okay with replacing the save and cancel button with a close button?

**Comment by jkmarx** [comment]
Actually the issue isn't with the save and cancel, it's with the data being displayed. For example, modify permissions and don't save. Refresh page, notice the permissions did not save.
