### ISSUE TITLE
Data Set 1 - Launch Web Based IGV

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#1520]
* Specific code commit: e81a3d9f9f7304506ba10e7753638b5ebc5fc705
* Version of the web browser and OS: Chrome 43, Mac 10.11.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. In data set 1 browser, choose a filter (default, all files should be selected)
2. Visualize - Select select species
3. Launch web based IGV

### Observed behavior
URL is missing node ids
<img width="1412" alt="screen shot 2016-11-14 at 10 08 42 am" src="https://cloud.githubusercontent.com/assets/9956764/20269832/d1c26a44-aa52-11e6-96e5-7f8b76e5a542.png">

### Expected behavior
All selected nodes should be in url

**Comment by ngehlenborg** [comment]
Ok, this is odd. I believe this used to work. I am pretty confident that I even demoed this at some point.
