### ISSUE TITLE
*[4]* change how analysis status is displayed in launch pad

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#242]
This should be based on the new progress indicator UI elements to be developed for the "global" progress indicator.
Tasks:
- [x] test analysis status before creating dynamic checks
- [ ] show progress for all three 3 phases: distinguish with different icons next to percent sign: upload, cog wheels, download

Pivotal Tracker story 40822761 (Nils Gehlenborg - Dec 6, 2012)

**Comment by jkmarx** [comment]
Consolidate analysis monitioring issues: https://github.com/parklab/refinery-platform/issues/553
