### ISSUE TITLE
create "node detail" view with file download option in sample selection interface

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#243]
Tasks:
- [x] GET API for Node
- [x] download link
- [x] generate table with attributes
- [ ] view in IGV link

Pivotal Tracker story 40907297 (Nils Gehlenborg - Dec 9, 2012)

**Comment by jkmarx** [comment]
@ngehlenborg The only this outstanding is "view in IGV link".  Is this still relevant?

**Comment by ngehlenborg** [comment]
Can be closed, this will be picked up again in the context of File Browser 2.
