### ISSUE TITLE
Update to Celery 3.x

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#248]
[Celery 3.1 with Django, django-celery, RabbitMQ and MacPorts](http://chriskief.com/2013/11/15/celery-3-1-with-django-django-celery-rabbitmq-and-macports/) - migration from v2 to v3

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WNRkOU7V&#x2F;175-analysis-backend-rewrite"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Analysis backend rewrite</a>
