### ISSUE TITLE
implement "red button" script to set all jobs to error state in Galaxy

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#261]
Tasks:
- [ ] extend Galaxy connection model with more information about Galaxy DB
- [ ] create form to get Galaxy DB user and password
- [ ] update all job states to "error"

Pivotal Tracker story 41355083 (Nils Gehlenborg - Dec 17, 2012)

**Comment by jkmarx** [comment]
Related to #295 .
