### ISSUE TITLE
Analysis monitoring checks analysis status before a history is created in Galaxy.

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#282]
Example log message:

models execution_status: Unable to get progress for history 'None' of analysis 'Test workflow 2013-06-27 @ 17:11:15'

execution_status() is called from analysis_status() view by javascript

Pivotal Tracker story 52548389 (Ilya Sytchev - Jun 28, 2013)

**Comment by jkmarx** [comment]
I'm having difficulty reproducing this issue. I've tried just running analysis and also stopping galaxy before and during the analysis.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WNRkOU7V&#x2F;175-analysis-system-rewrite"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Analysis system rewrite</a>

**Comment by hackdna** [comment]
Fixed in ec4310d
