### ISSUE TITLE
Upload data analysis workflows to the Galaxy toolshed.

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#290]
SPP workflow with different reference genomes
Tasks:
- [ ] upload workflows to the test toolshed
- [ ] publish workflows in the main toolshed

Pivotal Tracker story 47242765 (Ilya Sytchev - Apr 1, 2013)

**Comment by ngehlenborg** [comment]
Taken care off for existing workflows. Ongoing issue not related to development.
