### ISSUE TITLE
support canceling of analyses

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#295]
Tasks:
- [ ] get advice from Galaxy team on how to cancel running workflows in Galaxy
- [x] 12h create cancel button to set analysis to "cancelled" state and send email to admin with information about which history and data set need to be terminated
- [ ] talk to LabKey about how they cancel analyses

Pivotal Tracker story 46996657 (Nils Gehlenborg - Mar 27, 2013)

**Comment by ngehlenborg** [comment]
@hackdna: if I understood you correctly, this is now working - by deleting the history in Galaxy we are stopping all running jobs. Correct?

**Comment by hackdna** [comment]
yes: c2f2e351
