### ISSUE TITLE
*[20]* improve progress indicators

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#296]
Tasks:
- [ ] *4h* no longer show "progress" page after analysis is launched and show confirmation dialog that analysis had started
- [ ] *16h* create a "menu" like compact progress indicator that is globally accessible

Pivotal Tracker story 46993653 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
Consolidate analysis monitoring issues: https://github.com/parklab/refinery-platform/issues/553
