### ISSUE TITLE
cancel analysis if error state returned by Galaxy (based on overall history state)

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#297]
Tasks:
- [ ] *12h* remove analysis from analysis manager
- [ ] *0h* do not create any new nodes in data set

Pivotal Tracker story 46990661 (Nils Gehlenborg - Mar 27, 2013)

**Comment by ngehlenborg** [comment]
Create a "failing" test workflow and investigate Refinery behavior.

**Comment by jkmarx** [comment]
Consolidate to analysis backend issue: https://github.com/parklab/refinery-platform/issues/554
