### ISSUE TITLE
*[8]* correct notifications about error states

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#298]
Tasks:
- [ ] *4h* state handling: add paused state and treat it like the error state
- [ ] *4h* show error state in progress UI

Pivotal Tracker story 46990539 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
Was this issue for analyses? @ngehlenborg

**Comment by ngehlenborg** [comment]
This is obsolete. Closing.
