### ISSUE TITLE
*[4]* stop requiring page reloads in sample selection interface

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#301]
Tasks:
- [ ] 4h changing the permanent attribute order in a data set
- [ ] 0h remove link to analysis history on progress indicator page

Pivotal Tracker story 46989155 (Nils Gehlenborg - Mar 27, 2013)

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
This issue is covered by #906

**Comment by ngehlenborg** [comment]
Closing since obsolete.
