### ISSUE TITLE
explore advantages (and disadvantages) of using a model to manage file types

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#305]
Right now files with an extension that is not registered as a (hard-corded) file type will have an UNKNOWN file type, which is ok in principle but since file types depend on the tools used in workflows it is probably not the best solution to hard-code them. A model would allow workflow engine managers and admins to create file types for their workflows. Since file types eventually will also be used to check whether a particular file can be fed into a given workflow or viewer, knowing the file type might become crucial and file type UNKNOWN would be a serious problem.

Pivotal Tracker story 47211551 (Nils Gehlenborg - Apr 1, 2013)

**Comment by hackdna** [comment]
also, consider the use case when *.fastq.gz is detected as a "gz" file

**Comment by ngehlenborg** [comment]
@scottx611x: This is related to #250.

**Comment by ngehlenborg** [comment]
@scottx611x: can you please check if this has been addressed by your recent changes?

**Comment by scottx611x** [comment]
Closing this as the functionality described has been provided as of commit: e68e59990836460ab859dcd65f2e71cd45bc6d01

**Comment by hackdna** [comment]
File extensions are not being loaded automatically along with the file types.

**Comment by scottx611x** [comment]
`FileExtensions` and `FileTypes` are loaded properly from a clean instance as of commit: 1a6f52ba35380f717c151585cab7e9c545f4e6d7

If anyone runs into issues, a manual command can be provided to load this data.
