### ISSUE TITLE
Find a way to "freeze" node sets

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#307]
Pivotal Tracker story 46768389 (Nils Gehlenborg - Mar 23, 2013)

**Comment by jkmarx** [comment]
Will someone provide more details on this issue?

**Comment by jkmarx** [comment]
@ngehlenborg Will someone provide more details on this issue?

**Comment by ngehlenborg** [comment]
This issue describes the downside of using Solr queries to store node sets rather than a list of nodes. This would will be addressed by #1038. Closing.
