### ISSUE TITLE
Update data set total file size after data set changes

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#309]
Pivotal Tracker story 46768371 (Nils Gehlenborg - Mar 23, 2013)

**Comment by jkmarx** [comment]
Where is the data set total file size shown? I didn't see it in the dataset view.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>
