### ISSUE TITLE
Add functionality to keep galaxy workflows, libraries, and histories

### ISSUE THREAD

**Issue by rpark37** [parklab/refinery-platform#324]
Add functionality to allow users to select if they want to keep workflows, histories, and libraries in galaxy 

Pivotal Tracker story 41838001 (Richard Park - Jan 2, 2013)

**Comment by ngehlenborg** [comment]
It might be better to implement this via a global setting that the admin can turn on and off rather than exposing this to the end user.

**Comment by ngehlenborg** [comment]
We should have a global setting with 3 possible states: `DELETE_ALWAYS`, `DELETE_SUCCESS`, `DELETE_NEVER`.

**Comment by hackdna** [comment]
This logic should be added to [`galaxy_cleanup()`](https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L1063).

Django setting should be `REFINERY_ANALYSIS_CLEANUP` with possible values of `'always'`, `'on_success'` or `'never'` with `'on_success'` as default.

**Comment by ngehlenborg** [comment]
Maybe we want to add `GALAXY` to the setting name to make it clearer, e.g. `REFINERY_ANALYSIS_GALAXY_CLEANUP`?

**Comment by hackdna** [comment]
OK, then maybe `REFINERY_GALAXY_ANALYSIS_CLEANUP` to keep it consistent with the other project specific settings like `REFINERY_DATA_IMPORT_DIR`?

**Comment by ngehlenborg** [comment]
:+1:
