### ISSUE TITLE
find a way to document javascript

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#327]
Ideally this should integrated with the Sphinx documentation.

Pivotal Tracker story 41428773 (Nils Gehlenborg - Dec 18, 2012)

**Comment by ngehlenborg** [comment]
@flekschas and @jkmarx: What are you using to document your code?

**Comment by flekschas** [comment]
I am using [JSDocs](http://usejsdoc.org/). Angular uses an extended version called [ngDocs](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation). Might be more specific to Angular but JSDocs can be used universally.

Some examples:
https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/src/js/commons/services/ui-scroll-source.js
https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/src/js/commons/router/url-router.js

I try to distinguish between documentation and comments using the scheme below:

```
/**
 * Documentation
 */

/*
 * Multi line comment
 */

// One line comment
```

**Comment by ngehlenborg** [comment]
See also http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/

**Comment by ngehlenborg** [comment]
Let's use jsdoc. @jkmarx: Could you please add this to the coding style guide?

**Comment by jkmarx** [comment]
Added jsdoc link to the code style guide, under javascript.
