### ISSUE TITLE
"datafile" field in FileStoreItem cannot be documented automatically

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#328]
The "datafile" field in FileStoreItem cannot be documented automatically. This should be addressed. All other fields in the model are being auto-documented.

Pivotal Tracker story 41425665 (Nils Gehlenborg - Dec 18, 2012)

**Comment by scottx611x** [comment]
@ngehlenborg Can we close this?

**Comment by ngehlenborg** [comment]
Yes!

**Comment by scottx611x** [comment]
Closing as non-relevant anymore.

See https://github.com/parklab/refinery-platform/pull/1438 for the removal of sphinx documentation
