### ISSUE TITLE
Bring unit tests for file store up to date

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#339]
Create unit tests for the existing functionality of file store.  Involves refactoring of the file store.

Pivotal Tracker story 32560963 (Ilya Sytchev - Jul 10, 2012)

**Comment by ngehlenborg** [comment]
@hackdna: what is the status on this?

**Comment by hackdna** [comment]
I haven't had a chance to do any significant refactoring in a long time. To measure unit test coverage progress objectively we should start using something like [coverage.py](http://coverage.readthedocs.org/).

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9eRJNiHy&#x2F;9-339"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #339</a>

**Comment by jkmarx** [comment]
Issue closed because we are adding support of cloud object store which requires refactoring of current code along with new unit tests.
