### ISSUE TITLE
create Tastypie API for gene annotation

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#348]
Pivotal Tracker story 35637027 (Nils Gehlenborg - Sep 6, 2012)

**Comment by jkmarx** [comment]
Should we remove or update this issue since we are transitioning away from Tasty Pie?

**Comment by jkmarx** [comment]
@ngehlenborg Should we remove or update this issue since we are transitioning away from Tasty Pie to Django Rest?

**Comment by ngehlenborg** [comment]
This is no longer relevant. Closing.
