### ISSUE TITLE
provide option to keep Galaxy history if workflow fails

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#357]
When there is an error during workflow execution the history should not be deleted in order to perform diagnostics. This should be an optional switch (we might not always do this in production, but at least during development we need the option to keep histories).

Pivotal Tracker story 32709265 (Nils Gehlenborg - Jul 12, 2012)

**Comment by ngehlenborg** [comment]
Has been implemented via a Django setting in `config.json`. @scottx611x - can you reference the variable and close?

**Comment by scottx611x** [comment]
Implemented here: https://github.com/parklab/refinery-platform/blob/develop/refinery/config/config.json.erb#L106
