### ISSUE TITLE
external tool status for celery unstable even though celery is running fine

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#377]
I observed that the external tool status for celery is switching back and forth between SUCCESS and FAILURE every few seconds (3 - 5 seconds wall clock time), even though the application is running fine.

The task statuses are all looking ok, too:

![screen shot 2014-03-03 at 7 30 02 am](https://f.cloud.github.com/assets/1216518/2309279/a054142c-a2cf-11e3-8569-ffbcfade1d59.png)

How can this happen?

This was observed on the VM after restarting all tools and running the node_relationship_ui_feature branch (even though I doubt that there is any difference to the develop branch with regards to the external tool status monitoring).

**Comment by ngehlenborg** [comment]
I am still observing this problem occasionally. We should look into using the supervisord API (http://supervisord.org/api.html) to see if we can replace the current backend with calls to supervisord. It seems pretty straightforward.

@hackdna: Do you think that supervisord is an appropriate approach for running services in production? And would be still be using supervisord when running on AWS?

**Comment by hackdna** [comment]
Supervisord can be used in production. However, application architecture will change on AWS (different services running on different EC2 instances), so we'll be probably using something like http://aws.amazon.com/cloudwatch/.

**Comment by ngehlenborg** [comment]
Thanks @hackdna. We could implement a backend for CloudWatch once we move. I suggest we try to connect directly to supervisord for now and pass the information on to the client through our own API. If someone decides to deploy without supervisord, they need to handle monitoring themselves or use the existing backend. supervisord should be a lot more reliable than our current solution and will also be less of a strain on resources.

**Comment by hackdna** [comment]
Yes, it'd be nice to have a monitoring API in Refinery that could work with different backends but I think there are more important tasks to tackle in the short to medium term.

**Comment by ngehlenborg** [comment]
Closed by removal of ExternalToolStatus backend in e3d48712c4c1fcf87f3e5aa2cc7eec22245b0d04.
