### ISSUE TITLE
Catch-All Projects are created without an owner

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#402]
Over time, I can see several Catch-All Projects accumulate both on localhost (regular user accounts) and dev VM (LDAP user accounts).

**Comment by AntonXue** [comment]
From the shell, if I run something like ```user.userprofile.catch_all_project```, the appropriate Catch-All Project shows up. Is this something that's happening occasionally to only a few Catch-All Projects?

**Comment by ngehlenborg** [comment]
@hackdna: can you clarify what you mean by "accumulate"? According to the code, all catch-all projects are assigned an owner when they are created. Catch-all projects are only created once the user logs in for the first time.

**Comment by hackdna** [comment]
I have seen several that look like this: `Catch-All Project - (no owner assigned) -`. I've deleted most of them but there is still one left on refinery-dev and refinery-prod.

**Comment by ngehlenborg** [comment]
I am unable to reproduce this. Closing for now.
