### ISSUE TITLE
Analysis results are added to saved input selections

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#414]
#### Steps to reproduce
1. select a single-input workflow
2. save an input selection with one sample
3. run the workflow
4. re-run analysis using the saved input selection

#### Observed results
Analysis results from the first run are added to the saved input selection, so the second analysis runs with those results as inputs in addition to the original input selection.

#### Expected results
Saved input selection should not be modified without user's input.  Subsequent analyses should run on the original sample selection only.

**Comment by ngehlenborg** [comment]
Currently this is a feature - we can discuss if this should be changed to stable lists (via node ids).

**Comment by ngehlenborg** [comment]
This will go away with the new `NodeGroup`s - correct @jkmarx?

**Comment by jkmarx** [comment]
Yes, which is why I put it in the current milestone.
