### ISSUE TITLE
Show the name(s) of currently running tool(s) when displaying analysis progress

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#425]
ID(s) of the running tool(s) can be obtained from Galaxy jobs API (e.g., /api/jobs?history_id=4b187121143038ff&state=running) which is encapsulated in bioblend.galaxy.jobs.JobsClient.get_jobs(). Sample JSON output:
```
[
  {
    create_time: "2014-07-09T20:43:59.114975",
    exit_code: null,
    id: "fd767e8b7355e21a",
    model_class: "Job",
    state: "running",
    tool_id: "testtoolshed.g2.bx.psu.edu/repos/hackdna/refinery_test/refinery_test_1-1/0.1",
    update_time: "2014-07-09T20:44:19.879747"
  }
]
```
Tool name can be obtained from the tools API (e.g., /api/tools/testtoolshed.g2.bx.psu.edu/repos/hackdna/refinery_test/refinery_test_1-1/0.1) which is encapsulated in bioblend.galaxy.tools.ToolClient.show_tool(). Sample JSON output:
```
{
  description: "for testing Galaxy workflow execution from Refinery",
  id: "testtoolshed.g2.bx.psu.edu/repos/hackdna/refinery_test/refinery_test_1-1/0.1",
  model_class: "Tool",
  name: "Refinery test tool 1-1",
  panel_section_id: "test_tools",
  panel_section_name: "Test tools",
  version: "0.1"
}
```

**Comment by jkmarx** [comment]
Consolidate to analysis backend issue: https://github.com/parklab/refinery-platform/issues/554
