### ISSUE TITLE
Avoid duplicating fields if they are annotated as both a characteristic and a factor

### ISSUE THREAD

**Issue by sjhosui** [parklab/refinery-platform#446]
In many instances, a characteristic will be duplicated as a factor to indicate that that characteristic is a distinguishing feature of the study. The parser and file selection browser identify this as two separate fields and it ends up being duplicated in the facets and table.

**Comment by jkmarx** [comment]
Can someone provide a dataset in which this error occurs?

**Comment by scottx611x** [comment]
@jkmarx See `Organism Part` here:
https://refinery-dev.stemcellcommons.org/data_sets/fe8e90f3-0a83-477e-bc8a-db0b838b7938/#/files/browse

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
In the data set 2 browser, the duplicate column fields are removed for the data set grid generation. In the attributes utilities, the duplicate attributes are still shown. Commit 9f34c88cb7ec02144eb52ea43bde1de5b4ac2008

**Comment by jkmarx** [comment]
Ref #849 Resolved by #1562
