### ISSUE TITLE
Eliminate Celery chords from analysis_manager

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#448]

**Comment by ngehlenborg** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WNRkOU7V&#x2F;175-analysis-system-rewrite"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Analysis system rewrite</a>

**Comment by hackdna** [comment]
Testing Trello integration

**Comment by hackdna** [comment]
Resolved in 2d82a6a
