### ISSUE TITLE
Improve analysis progress monitoring UI

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#450]
If analysis input files are already available locally in the file store, the analysis preprocessing file "upload" progress bar turns green in seconds. On the other hand, actual upload into Galaxy is running for several minutes while execution progress bar shows no progress (since history is empty until a couple of files are uploaded into a library).

Analysis stages should be labeled better and progress indicators should be more dynamic.

**Comment by jkmarx** [comment]
Consolidate analysis monitoring issues: https://github.com/parklab/refinery-platform/issues/553
