### ISSUE TITLE
Update external Javascript packages to the latest stable versions

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#452]
Listed in bower.json and package.json.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6I9Xsb1o&#x2F;13-452"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #452</a>

**Comment by jkmarx** [comment]
Ref #1288

**Comment by jkmarx** [comment]
Closing issue, because it's reoccurring. We'll leave a trello card open.
