### ISSUE TITLE
Provenance graph not displayed for newly imported datasets

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#458]
### Steps to reproduce ###
1. Import a dataset (e.g. http://stemcellcommons.org/sites/default/files/isa/isa_12373_926332.zip) via /data_set_manager/import/isa-tab-form/.
2. Select Provenance from Display dropdown.

### Observed results ###
No provenance graph displayed. Errors in the browser developer console:
`Uncaught ReferenceError: analysisView is not defined`
`Uncaught TypeError: Cannot read property 'getDocumentList' of null`

### Expected results ###
Provenance graph displayed. No errors in the browser developer console.

**Comment by sluger** [comment]
After setting up a new and clean VM, I could import http://stemcellcommons.org/node/11610 and http://stemcellcommons.org/node/13880 as well as load the initial provenance graph visualization. http://stemcellcommons.org/node/14911 hangs in the ISA-Tab Import.
Unfortunately, I don't have access to download http://stemcellcommons.org/node/13270 as it is private.
