### ISSUE TITLE
click + ctrl shortcuts in provenance visualization not working in Chrome on the Mac

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#460]
Holding the ctrl key while clicking opens the context menu. Can we switch the modifier key for all shortcuts that involve ctrl?

**Comment by ngehlenborg** [comment]
@sluger: are those shortcuts still in use?

**Comment by sluger** [comment]
For the time being i have deactivated all keyboard shortcuts as they are not required for interaction.
