### ISSUE TITLE
change FASTQC workflow to produce ZIP archive output

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#471]
The workflow should produce a ZIP file rather than a collection of images and HTML files so that the results can be more easily imported back into Refinery.

**Comment by hackdna** [comment]
[FastQC tool] (https://toolshed.g2.bx.psu.edu/view/devteam/fastqc) outputs the report as HTML datatype which is compressed into a single zip file by Galaxy on the fly.
