### ISSUE TITLE
Superuser not recognized by admin login

### ISSUE THREAD

**Issue by laperlej** [parklab/refinery-platform#475]
Hi,

I am interested in using refinery-platform for my project but encountered quite a few problems trying to get it to work.

First of all I would like to mention as a side note that the VM has a problem with it's ruby version. Some gems require Ruby version >= 1.9.3 to install but the VM runs 1.8.7. However, I was able to successfully install from the zip that was available on dec 4 from http://www.refinery-platform.org on linux mint.

The main problem I have is that while I can start the VM and install everything successfully I cannot login on 192.168.50.50/admin with the superuser I create. In fact, there doesn't seem to be any relationship between the django user model I can access from ./manage.py on the VM and the login system.

I was wondering if anyone knew a way to have the login system recognize my superuser.

Thank you for your help.

**Comment by hackdna** [comment]
Hi,

The default admin user is created from a [fixture] (https://github.com/parklab/refinery-platform/blob/develop/refinery/core/fixtures/superuser.json) during syncdb. Username: admin, password refinery. We'll update the docs to reflect this.
