### ISSUE TITLE
Samples in public datasets are not displayed for unauthenticated users

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#478]
### Steps to reproduce
1. Assign read permission for a data set to the Public group using Django admin UI.
2. Access the data set without logging in to Refinery (example URL: /data_sets/ec1b6d08-1606-4e92-a02d-d7d5c34a1c17/)

### Observed results
Samples are not displayed. Browser console and refinery.log file show HTTP 401 error:
```"GET /api/v1/analysis/?format=json&limit=0&order_by=creation_date&data_set__uuid=ec1b6d08-1606-4e92-a02d-d7d5c34a1c17&csrfmiddlewaretoken=UFtuRpvsGEmKkqYI4agLBl1Cl2ahYpsh HTTP/1.1" 401```

### Expected results
Samples should be displayed.

**Comment by ngehlenborg** [comment]
We need to prevent the analysis API from choking on trying to serve private analyses to unauthenticated users.

**Comment by hackdna** [comment]
Note: AnonymousUser must be a member of Public group
