### ISSUE TITLE
Deleting analyses within the django admin interface should not delete them permanently.

### ISSUE THREAD

**Issue by sluger** [parklab/refinery-platform#480]
When deleting analyses from the django admin interface, analyses are deleted permanently from the database, whereas the corresponding nodes still show up.

I suggest to flag those analyses as "deleted" and keep them. Analyses and nodes could be excluded by this flag within the refinery platform.

**Comment by hackdna** [comment]
I'd suggest implementing this functionality directly in Refinery.

**Comment by ngehlenborg** [comment]
To be addressed by "hide" analysis feature.

**Comment by jkmarx** [comment]
@scottx611x Is this issue still relevant?

**Comment by scottx611x** [comment]
@jkmarx No we have deletion checks in place now

**Comment by jkmarx** [comment]
See above.
