### ISSUE TITLE
Convert documentation from reStructuredText to Markdown

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#482]
Read The Docs supports Markdown via MkDocs (http://www.mkdocs.org/)
http://docs.readthedocs.org/en/latest/getting_started.html

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jtuvuuPD&#x2F;14-482"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #482</a>

**Comment by jkmarx** [comment]
Currently, used to document code in django (in some places).

**Comment by ngehlenborg** [comment]
Addressed by https://github.com/parklab/refinery-platform/pull/1438.
