### ISSUE TITLE
TypeError on landing page in sharing.js

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#487]
There is an error in browser console when loading the landing page while not logged in:
```TypeError: Cannot read property 'innerText' of null
    at new <anonymous> (sharing.js:4)```

**Comment by ngehlenborg** [comment]
We need to figure out authentication and Django session information in Angular.

**Comment by hackdna** [comment]
Here's a very simple way to get Django username into the template (this value could be assigned to a JavaScript variable): http://stackoverflow.com/a/22892200

**Comment by hackdna** [comment]
Looks like the best practice is to use ```user.is_authenticated``` API call instead of accessing ```user.id``` to check if the user has been authenticated: https://docs.djangoproject.com/en/1.5/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated

**Comment by hackdna** [comment]
a new TypeError on landing page (running 6980c45):
```TypeError: Cannot read property 'getElementsByTagName' of null
    at new <anonymous> (sharing.js:8)```
