### ISSUE TITLE
Missing refinerySharingController error on the landing page

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#488]
Browser console shows:
```Error: [ng:areq] Argument 'refinerySharingController' is not a function, got undefined```

**Comment by AntonXue** [comment]
I did a pull of develop, and can't seem to be able to replicate this error - my landing page has no errors on the console. Could you please tell me how you managed to do it?

Do you think running grunt might help fix the problem?

**Comment by AntonXue** [comment]
Nevermind, I just managed to replicate it, will try to fix now.

**Comment by AntonXue** [comment]
Just involved adding this line

https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/src/js/refinery.js#L12
