### ISSUE TITLE
Evaluate Django REST Framework as a replacement for Tastypie

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#491]

**Comment by ngehlenborg** [comment]
-[] Can we update incrementally?
-[] What about permissions? (guardian)
-[] API keys supported?

**Comment by hackdna** [comment]
Django was funded to integrate key parts of the Django REST Framework request/response code: https://www.djangoproject.com/weblog/2015/dec/11/django-awarded-moss-grant/

**Comment by scottx611x** [comment]
__LINKS:__
* http://toastdriven.com/blog/2014/may/23/state-tastypie/
* https://www.reddit.com/r/django/comments/2gsk5w/i_just_jumped_ship_from_tastypie_to/
* https://www.djangopackages.com/grids/g/api/
* http://stackoverflow.com/questions/8430579/django-restful-api-django-piston-vs-django-tastypie

__PROS:__

| __TastyPie__        | __Django REST Framework__         | 
| ------------- |:-------------:|
| comprehensive and well documented    | HTML browse-able self-describing APIs. (EG, see the (tutorial API)[http://restframework.herokuapp.com/] |
| building an API is incredibly easy     | built on top of Django's class based views      | 
| More powerful filter control out-of-the-box: http://stackoverflow.com/a/16915474 | In stable production     |
| like playing with pure Python while using the Django ORM | has surpassed TP in usage as  seen here: https://www.djangopackages.com/grids/g/api/      |
| supports OAuth 1.0a out of the box | excellent documentation     |
|   |   (nice browsable interface)[http://restframework.herokuapp.com/]   |

__CONS:__

| __TastyPie__       | __Django REST  Framework__        | 
| ------------- |:-------------:|
| proprietary class-based views implementation     | newest release (3.3) drops support for Django 1.5,  1.6, and 1.7|
| Release still not 1.0+      |   steeper learning curve     | 
| relatively slow pace of development recently |  more boilerplate code and setup required that is not strictly needed for many simple use cases  |
| Travis CI hasn't been passing in months |       |
| Incompatibility with Django 1.7? |      |

===

__EXAMPLES OF BOTH:__

__TastyPie:__

```python
# myapp/api.py
from tastypie.resources import ModelResource
from myapp.models import User

class UserResource(ModelResource):
    class Meta:
        queryset = User.objects.all()
        resource_name = 'user

# myapp/urls.py
from django.conf.urls import url, include
from myapp.api import UserResource

user_resource = UserResource()

urlpatterns = [
    url(r'^blog/', include('myapp.urls')),
    url(r'^api/', include(user_resource.urls)),
]

# api endpoint
`curl -H "Accept: application/json" http://127.0.0.1:8000/api/user/`
```

===

__Django REST Framework:__

```python

# myapp/serializers.py
from django.contrib.auth.models import User
from rest_framework import serializers


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'groups')

# myapp/views.py
from django.contrib.auth.models import User
from rest_framework import viewsets
from tutorial.quickstart.serializers import UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

# myapp/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from tutorial.quickstart import views

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

# api endpoint
`curl -H "Accept: application/json" http://127.0.0.1:8000/api/user/`
```
