### ISSUE TITLE
upgrade to FontAwesome 4.x.x

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#493]

**Comment by flekschas** [comment]
If we don't need all of FontAwesome Icons I would recommend picking the ones used and create a custom icon font using https://icomoon.io/app. This greatly helps to reduce the file size.

**Comment by flekschas** [comment]
Looking at the current use of icon font:
grep -rl "icon-" . | xargs cat | perl -wnlE 'say for /icon-[a-zA-Z0-9]+/g' >> ./fontAwesome-use.txt

**Comment by jkmarx** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4

**Comment by jkmarx** [comment]
It may be worthwhile to wait until we have updated the UI before creating a custom library. Maybe create a separate issue, so we don't forget.
