### ISSUE TITLE
upgrade to Bootstrap 3.x.x

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#494]
- [x] Complete http://getbootstrap.com/migration/
- [x] Update less variables names
- [x] Update css styling for base template
- [x] Update css styling for other components
- [x] Update javascript syntax for new classes
- [x] Manually test (see wiki)

**Comment by jkmarx** [comment]
http://getbootstrap.com/migration/

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c9RdRyno&#x2F;176-bootstrap3-upgrade"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Bootstrap3 Upgrade</a>

**Comment by jkmarx** [comment]
Issue can close after https://github.com/parklab/refinery-platform/issues/782 and https://github.com/parklab/refinery-platform/issues/777 closes.
