### ISSUE TITLE
improve how text is trimmed in dataset file table

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#497]
Currently long text is trimmed and the trimmed text is replaced with an ellipsis. The full text is shown when the user hovers over the ellipsis. This is not a good solution because (1) the full text cannot be copied and (2) the full text is sometimes very long and does not fit well into the tool tip.

A better solution would be to allow the user to expand the trimmed text in the table cell by clicking the ellipsis. There should also be an option to return the text to the trimmed state.

**Comment by jkmarx** [comment]
Commit af87d8f97fb83e3799456fae2d7e52c9d696705c, Add toggling for showing and hiding trimmed text.
