### ISSUE TITLE
Execution of workflows on multiple input files produces 200MB+ files in media directory

### ISSUE THREAD

**Issue by sluger** [parklab/refinery-platform#503]
Steps to reproduce:
1. Within the dataset table view, switch to Analyze tab, select a workflow (e.g. 5 steps...) and assign multiple input files to it.
2. Start the analysis.

Observed result:
On ubuntu 14.04 with galaxy-central-hbc, the preprocessing of files as well as the execution takes unusually long and may produce 200MB+ files within the media directory.

Expected result:
Quick execution with galaxy while the file size remains normal within the boundaries of an usual <1MB file.

**Comment by sluger** [comment]
Today i ran into some issues again after I executed about ten analyses with the same dataset file as root. It went all fine for this branch until i executed an analysis containing two different dataset files as input with the 5 steps workflow.

**Comment by ngehlenborg** [comment]
Can you tell us which input files you used?

**Comment by sluger** [comment]
Data Set File Type Test: File Type Test

At first I created a graph beginning with the HMM_ES_K36.bed and as I mentioned above about ten analyses went fine. Then I made a single analysis with the remaining two input files which took about 10 minutes in preprocessing and execution.

**Comment by ngehlenborg** [comment]
What you are observing is the expected result. If you are running the workflow on ```NP.K4.wig```, it will get imported into Refinery from the remote URL and since ```NP.K4.wig``` has 258.4 MB, the analysis will take longer (the other two files in that test data set are 1 MB or less) and the outputs of all test tools run on that file will be around 258.4 MB as well.
