### ISSUE TITLE
Can't register new user.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#527]
The registration form doesn't work. Nothing happens when the form is submitted, i.e. the _register_ button is clicked. I don't see any errors in the browser console nor is anything logged in `refinery.log`.

**Comment by ngehlenborg** [comment]
This is a conflict between Angular and Django forms (and also affects other forms). I don't have more information at this point.

**Comment by flekschas** [comment]
Oh I just figured out there is simply no action defined:

From `templates/registration/registration_form.html`:
```<form method="post" action="" class="wide" id="registration-form">```

**Comment by ngehlenborg** [comment]
Yes, and that is fine for standard Django forms. When I last looked into this, there was no simple workaround (note that this form is provided by the django-registration package, which I don't want to edit).

**Comment by flekschas** [comment]
But where should the form send the POST request to? I've pointed it to `/accounts/register/` and the submit button works. E-Mail validation works. Unfortunately, I get the following error:

```NotImplementedError at /accounts/register/```

Could it be that this is simply not implemented?

**Comment by ngehlenborg** [comment]
This form is provided and handled by the django-registration package (https://django-registration.readthedocs.org/en/latest/index.html) and works fine unless Angular is included. Angular seems to be deactivating forms without an action.

**Comment by flekschas** [comment]
I registered a new user and picked up the activation link from the email but when I open the link it says the activation is not possible:
> Account not activated
> Sorry, it didn't work. Either your activation link was incorrect, or the activation key for your account has expired; activation keys are only valid for 7 days after registration.
I checked the mail header and the email is being send in 4 hours. Could it be that the time shift causes this error?

**Comment by flekschas** [comment]
Okay the weird thing is I can still log in even though Refinery told me the account is not active. (I checked the
