### ISSUE TITLE
labels are trimmed in provenance graph

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#537]
Node labels are trimmed in the provenance graph visualization for no apparent reason.

![screen shot 2015-06-25 at 2 35 20 pm](https://cloud.githubusercontent.com/assets/1216518/8362549/96f8b8d2-1b47-11e5-9f7f-605c92b867d7.png)

**Comment by sluger** [comment]
The clipping is necessary as the length of labels is arbitrary as well as another node including a label could potentially be layouted directly right to those nodes shown in the figure above. The layout does not conform to a grid, where every node contains a row and a column index. With a grid, one could look for nodes placed right to the label in context and then hide those node labels to prevent overlapping based on the text length. 

I'm not certain if a simple solution could be implemented. A first guess would be to scan successor nodes for their x and y coords. Based on the label length, a certain region right to the node would than have their node labels hidden to prevent overlapping.

**Comment by ngehlenborg** [comment]
We won't be able to come up with an effective solution quickly, so I would suggest to keep the trimming as is, but indicate trimmed labels with an ellipsis (expansion button with arrow is optional and probably not required in this context):

![screen shot 2015-07-23 at 9 02 27 am](https://cloud.githubusercontent.com/assets/1216518/8850943/09743e30-311a-11e5-8db5-c4a6fb1dae43.png)

**Comment by sluger** [comment]
Labels are now trimmed with 3 dots following the displayed substring. Seamless applies to mousewheel zoom, fit to window and mouseover as well as mouseout actions.

![image](https://cloud.githubusercontent.com/assets/5220584/9439441/55463d02-4a67-11e5-958c-67190edf3bef.png)
