### ISSUE TITLE
names should be shown for all nodes in provenance graph

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#538]
Non-imported nodes (files and other, in particular sample, assay and data transformation nodes) should be labeled with their corresponding name.

**Comment by ngehlenborg** [comment]
Trim names to meaningful substring.

**Comment by sluger** [comment]
![trimming-dt-nodes](https://cloud.githubusercontent.com/assets/5220584/8549225/ee6a3e5c-24c9-11e5-8885-b6c352398fe4.png)

**Comment by ngehlenborg** [comment]
Excellent!
