### ISSUE TITLE
OwnableResource's get_owner() checks for add_ permission

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#540]
OwnableResource's get_owner() returns the first user which has `add_*` permission. (See [lines 201-203](https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L201-L203)) This probably works fine since I assume that the uploaded gets assigned this permission first but when the order of users having `add_*` permission changes the owner can't be determined anymore. It may be more safe to check for `share_*` permission. In fact, this is already being done for the data sets API. (See [lines 121-123](https://github.com/parklab/refinery-platform/blob/develop/refinery/core/api.py#L120-L123))

**Comment by AntonXue** [comment]
Part of a bigger problem about permission sharing that was discussed in a meeting on June 26, 2015. Closed for now.
