### ISSUE TITLE
link to analysis results broken in dashboard

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#550]
The URL pattern of the links from the project panel look like this:

`.../data_sets/analysis/<analysis_uuid>`

But they should look like this:

`.../data_sets/<data_set_uuid>/analysis/<analysis_uuid>`

**Comment by flekschas** [comment]
The data set uuid is not found. I'll fix this.

**Comment by flekschas** [comment]
The analysis API doesn't return the data set uuid any more.

**Comment by ngehlenborg** [comment]
Is that a recent change?
