### ISSUE TITLE
launchpad display issue in Safari

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#556]
__Reproduce__
Open https://refinery-dev.stemcellcommons.org/#/ (or launchpad in general) in Safari

__Observed Behavior__
![screen shot 2015-07-09 at 11 33 39 am](https://cloud.githubusercontent.com/assets/1216518/8599481/c33a82da-262e-11e5-9901-876d6c6a8230.png)

__Expected Behavior__
![screen shot 2015-07-09 at 11 33 44 am](https://cloud.githubusercontent.com/assets/1216518/8599483/c9cceeee-262e-11e5-8530-e78d04b4ff11.png)

**Comment by flekschas** [comment]
Please use production settings.
1. `fab vm conf:prod`
2. `http://192.168.50.50/`

**Comment by flekschas** [comment]
Safari needs special ve

**Comment by hackdna** [comment]
We could also make `grunt compile` the default for all conf modes.

**Comment by flekschas** [comment]
I would strongly encourage to do this since `grunt build` only makes sense in combination with `grunt watch`. I could add a new settings mode called gruntwatch (similar to djdt), which is the only mode that calls `grunt build`.

**Comment by hackdna** [comment]
Lets discuss the best approach at the next dev meeting.
