### ISSUE TITLE
video at vimeo is private

### ISSUE THREAD

**Issue by ellis** [parklab/refinery-platform#558]
Under "Talks and Presentations" at http://www.refinery-platform.org/, the video link at the bottom of the list is not accessible. When I click on the link, a "Private Video" page is shown.  Could you please make the video public (or perhaps remove the link, I suppose)?

**Comment by ngehlenborg** [comment]
Thanks for pointing this out. This is a conference video and is not under our control but I'm trying to have it made public again.

**Comment by ellis** [comment]
Thanks

**Comment by ngehlenborg** [comment]
The video has been made public again.

**Comment by ellis** [comment]
Thanks, Nils, watching now!
