### ISSUE TITLE
abstract in launchpad data set preview is broken

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#560]
__Reproduce__
Open abstract view of data set with associated publication.

__Observed Result__
![screen shot 2015-07-13 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/1216518/8660569/b21f65ca-297f-11e5-8a73-75a73d2ade9e.png)

__Expected Result__
The abstract.

**Comment by flekschas** [comment]
Found the error. For some reason the Django middleware doesn't decode XML to JSON anymore.
