### ISSUE TITLE
Galaxy Database File Cleanup, Post Analysis

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#567]
After completing an analysis, galaxy should remove/delete database files related to analysis.

**Comment by ngehlenborg** [comment]
Check Galaxy wiki for information about how to clean up a Galaxy instance. The solution to the problem might be running a Galaxy utility script and no need to change anything in Refinery.

**Comment by ngehlenborg** [comment]
Please document in the developer wiki.

**Comment by scottx611x** [comment]
Closing because this functionality is already provided to us through Galaxy.
__See:__ [Refinery Wiki Link](https://github.com/parklab/refinery-platform/wiki/Purging-Galaxy-Data)
