### ISSUE TITLE
Command line ISATab import creates only soft link to the original file.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#571]
When importing an isatab archive Refinery will soft link the archive instead of copying. This can cause trouble when archives are accessed via the synced folder since it can happen that the original files on the host machine get moved, renamed or deleted. Consequently the files can't be found anymore because the symlink will be broken.

I think the files should better be copied to avoid any problems.

**Related**: [#526](https://github.com/parklab/refinery-platform/issues/526#issuecomment-122137369)

**Comment by ngehlenborg** [comment]
Fixed in cb5cfc4.
