### ISSUE TITLE
dataset keyword search broken

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#572]
__Reproduce__
Enter a single letter into the search box. 

__Observed Behavior__
"No Data Sets Found" is displayed. Reload is required to get data set list back (deleting search query does not help).

__Expected Behavior__
No search should be executed until at least 3 letters have been entered.

**Comment by flekschas** [comment]
Only public data sets seem to be broken.

**Comment by flekschas** [comment]
Should be fixed with commit d108c71. Search works normal for me.
