### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined when searching for data sets

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#576]
Commit 73b3052

## Step to reproduce
1. Import several zebrafish data sets
1. Login to the site with the same account that was used to import the data sets
1. Type "zebra" into the data set search box on the landing page

## Observed results
No data sets are displayed and `TypeError: Cannot read property 'indexOf' of undefined` is shown in the browser console.
![screenshot](https://cloud.githubusercontent.com/assets/452575/8808234/6386091a-2faf-11e5-9aae-e4ebf18f159e.png)

## Expected results
Matching data sets are displayed, no errors shown in the browser console.

**Comment by flekschas** [comment]
This is bug comes up when no `access` properties for Solr docs are available.

**Comment by flekschas** [comment]
@hackdna Please test again if the error is gone. I can't test this since my data sets are all properly indexed.

**Comment by hackdna** [comment]
You can easily test this if you assign the read permission the Public group to a data set. The result is that those data sets are not returned during search. I'm now changing the data set sharing management command to do re-indexing.

**Comment by flekschas** [comment]
So have you tested the latest code?

**Comment by hackdna** [comment]
Yes, see above.

**Comment by flekschas** [comment]
I've tested it and can't find any errors.
