### ISSUE TITLE
add angularjs-humanize library

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#577]
https://github.com/saymedia/angularjs-humanize

**Comment by ngehlenborg** [comment]
An alternative library via @hackdna: https://libraries.io/bower/angular-humanize. Lacks support for dates.

**Comment by hackdna** [comment]
We need to use the exact version numbers for external libraries instead of the "latest" to avoid unexpected backward incompatible changes.

**Comment by AntonXue** [comment]
Okay, I'll update this in the next commit.
