### ISSUE TITLE
grunt watch is failing when run outside VM

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#579]
__Reproduce__
Run `grunt watch` in `ui` directory outside VM.

__Expected Behavior__
grunt waits for changes in `delta task` stage.

__Observed Behavior__
grunt gets stuck in a loop and keeps on printing the following message:
```javascript
Running "delta" task
Waiting...
Warning: EMFILE, too many open files ‘bower_components’
```

Running `bower prune` or deleting the `bower_components` directory followed by `bower install` do not have any effect.

**Comment by ngehlenborg** [comment]
This might be due to too many open files on my machine: https://github.com/yeoman/yeoman/issues/517

Do we have to watch the `bower_components` directory? There are current around 800 files in there.

**Comment by flekschas** [comment]
Now, only vendor files specified in `config.json` are being watched, dramatically reducing the total number of watched files.
