### ISSUE TITLE
permission editor shows manager groups

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#581]
Manager groups should not be shown in permissions editor for data sets.

![screen shot 2015-07-22 at 5 38 23 pm](https://cloud.githubusercontent.com/assets/1216518/8838153/b377a098-3098-11e5-81ba-7988319f8e39.png)

**Comment by flekschas** [comment]
It's probably better to adjust the sharing api instead of filtering in the front end, which would not be safe either.
