### ISSUE TITLE
Update Javascript Filenames and Directory to meet Code Style Guide

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#583]
- [x] Update ui/src to ui/source

- [x] In the feature directory, keep all relevant files (partials, controllers, directives, services, etc).

- [x] Update filenames, use hyphens for filenames. (example-file-name.js)

- [x] Update filenames, use . notation for file types or other identifies which are not the actual name. (example-file-name.spec.js)

- [x] Update filenames, refrain from using the .tpls.html notation instead use .html.

**Comment by jkmarx** [comment]
@AntonXue Will you help out with the renaming/organization of your ui/*.js & ui/*.html files?

**Comment by AntonXue** [comment]
Sure!

**Comment by jkmarx** [comment]
Will you please update the provenance related files to meet the js guidelines above? I think only 3 apply to you. It can be closed afterwards.

**Comment by sluger** [comment]
I also encapsulated the provvis into its own feature dir.
See https://github.com/parklab/refinery-platform/commit/59f72aa58ce235147f21d55c54a321761fcb50ba
