### ISSUE TITLE
Unknown provider: analysesOffsetFilterProvider <- analysesOffsetFilter

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#587]
Commit 7480cf2.
## Steps to reproduce
View any data set, e.g. http://192.168.50.50:8000/data_sets/2fe200ba-57dc-4e9b-9421-dd137e57fa2d/

## Observed results
Error in browser console:
`Error: [$injector:unpr] Unknown provider: analysesOffsetFilterProvider <- analysesOffsetFilter`

## Expected results
No error in browser console

**Comment by jkmarx** [comment]
e605364221d613e1cb226834164a27699efe8d0a
