### ISSUE TITLE
Replace simplejson Python module

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#589]
Simplejson was deprecated from [Django](https://docs.djangoproject.com/en/1.8/releases/1.5/#simplejson-deprecation). This will reduce number of dependencies and potentially [increase processing speed](https://medium.com/@jyotiska/json-vs-simplejson-vs-ujson-a115a63a9e26).

We should probably just use [json](https://docs.python.org/2/library/json.html) module from the Python standard library.

**Comment by ngehlenborg** [comment]
There is also https://pypi.python.org/pypi/ujson.

**Comment by flekschas** [comment]
Here's a comparison of ujson against other libs: https://github.com/esnme/ultrajson#benchmarks
And another benchmark: http://blog.dataweave.in/post/87589606893/json-vs-simplejson-vs-ultrajson

UltraJSON seems superior.

**Comment by hackdna** [comment]
We should also consider compatibility with Django, maturity and popularity of the project (as a proxy for future support) in addition to performance.

**Comment by scottx611x** [comment]
Closing according to: https://docs.djangoproject.com/fr/1.5/releases/1.5/#system-version-of-simplejson-no-longer-used

`simplejson` is deprecated as of `Django 1.5` and use of Python's stdlib `json` module is reccomended

**Comment by hackdna** [comment]
I still find a lot of references to simplejson in the codebase (17f94e5).

**Comment by scottx611x** [comment]
@hackdna Just double checked, there are six occurrences within comments. Everything else is in celery logs.

**Comment by scottx611x** [comment]
Closing with 0c6ef29

**Comment by flekschas** [comment]
A quick question: having had a look at ujson again. Would it make sense to keep that in the backlog for the future? It outperforms the standard library under all condition and often significantly.

**Comment by hackdna** [comment]
We'll keep it mind if we see any performance problems related to JSON manipulation.

**Comment by hackdna** [comment]
@scottx611x: PyCharm found 50 occurrences of simplejson.
![screenshot 2016-02-11 13 44 50](https://cloud.githubusercontent.com/assets/452575/12986530/c4380b84-d0c5-11e5-9cf6-178e92a19785.png)

**Comment by scottx611x** [comment]
Using cc2648ee906dd5ecb8b910d2f482eeb919f47dd3

![screen shot 2016-02-11 at 1 50 44 pm](https://cloud.githubusercontent.com/assets/5629547/12986661/7dd38104-d0c6-11e5-8618-1c1715634814.png)

**Comment by scottx611x** [comment]
Closed with a4eb092d34a7ab8683e0c6b62bef0e549a80ae5c
