### ISSUE TITLE
Table view header issue

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#593]
### Steps to Recreate Issue
In the dataview, click on the analyses tab. After the page loads, click the file tab. The data table view will render like this image: 
<img width="1195" alt="screen shot 2015-08-12 at 12 00 22 pm" src="https://cloud.githubusercontent.com/assets/9956764/9229331/98b1d1e0-40ea-11e5-8f75-7cf99cb5e167.png">

### Details
 1) This has been occurring for sometime and may occur from other navigation pattens.

### Expected results
<img width="1245" alt="screen shot 2015-08-12 at 12 08 27 pm" src="https://cloud.githubusercontent.com/assets/9956764/9229384/e07fdab2-40ea-11e5-8a9e-394faa4b51cd.png">
.

**Comment by ngehlenborg** [comment]
__Reproduce__
One way to break the table header is to switch to the _provenance_ or _matrix_ view and change the window size. This event is not registered by the table header and when returning to the _table_ view, the header will be misaligned.

__Observed__
![screen shot 2015-08-26 at 6 41 35 pm](https://cloud.githubusercontent.com/assets/1216518/9508264/1d23dce2-4c22-11e5-8705-c446cbd4abf8.png)

__Expected__
(after page reload)
![screen shot 2015-08-26 at 6 42 17 pm](https://cloud.githubusercontent.com/assets/1216518/9508272/34aab9a8-4c22-11e5-954e-0a6d61203582.png)

**Comment by ngehlenborg** [comment]
Addendum to https://github.com/parklab/refinery-platform/issues/593#issuecomment-135197987:

Making the window smaller when viewing the _provenance_ tab and returning to the _table_ view results in the view originally described by @jkmarx:

![screen shot 2015-08-26 at 6 45 55 pm](https://cloud.githubusercontent.com/assets/1216518/9508330/b6314fa0-4c22-11e5-99d1-cb5060626db8.png)

**Comment by flekschas** [comment]
I think this is a general issue when changing tabs. It could be that the tab's content is displayed simultaneously for a short time, causing trouble with the table header plugin.

**Comment by ngehlenborg** [comment]
Unable to reproduce the problem with the latest code. Thanks for the fix!
