### ISSUE TITLE
humanized time stamps don't work in Safari

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#595]
__Reproduce__
View the analysis tab on the data set page for any data set that has analyses using Safari (tested with Version 8.0.7 (10600.7.12))

__Observed__
![screen shot 2015-08-13 at 4 14 55 pm](https://cloud.githubusercontent.com/assets/1216518/9260569/840154ea-41d6-11e5-9468-61690c341208.png)

__Expected__
![screen shot 2015-08-13 at 4 14 37 pm](https://cloud.githubusercontent.com/assets/1216518/9260578/8e5a9294-41d6-11e5-9cea-c7c8d20ee08a.png)

**Comment by ngehlenborg** [comment]
I tested this using fab vm conf:gdev|dev|prod. Same result for all.

**Comment by jkmarx** [comment]
Humanize requires a specific format for relative time which is not compatible with safari. http://stackoverflow.com/questions/23440515/date-parsenew-date-nan-in-safari
