### ISSUE TITLE
dataset "BCL11A cistrome in mouse erythroleukemia (MEL) cells" exists twice in SCC

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#597]
__Reproduce__
Search for "BCL11A cistrome in mouse erythroleukemia (MEL) cells" on the dev-vm.

__Observed__
Two data sets are found. It appears that there are two ISA archives for this investigation: `isa_15576_819296_6.zip` and `isa_15576_893881_5.zip`. Note the difference in the part after `isa_15576`. 

__Expected__
Only one data set for this investigation.

**Comment by ngehlenborg** [comment]
It looks like Stem Cell Commons is using this version of the data set: http://stemcellcommons.org/sites/default/files/isa/isa_15576_893881.zip

**Comment by hackdna** [comment]
Removed isa_15576_819296.zip from shared folders on Google Drive.

**Comment by ngehlenborg** [comment]
That's sufficient.
