### ISSUE TITLE
analysis progress on dataset page is delayed during download phase

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#598]
__Reproduce__
Launch analysis that requires download of a large file into Refinery, e.g. one of the FASTQ files from "BCL11A cistrome in mouse erythroleukemia (MEL) cells".

__Observed__
![screen shot 2015-08-13 at 12 46 42 pm](https://cloud.githubusercontent.com/assets/1216518/9262101/69412afe-41e0-11e5-9901-3d5ef0693588.png)
Notice that the global analysis progress list shows percentage progress for the downloads while the analysis tab for the data set is still showing a wait indicator. In fact, I have never seen the progress bars for the download part on the analysis tab move. If they show up they either say "PENDING" or "SUCCESS".

__Expected__
Progress indicator for download on analysis tab and less delay before progress bars are showing. Alternatively, we could get rid of the progress bars altogether and simply show the percentages and "stage" icons that we are using for the global progress list. Collapse/expand for individual analyses on the analysis tab would become obsolete.

**Comment by ngehlenborg** [comment]
You can import the data set mentioned above directly from here: http://stemcellcommons.org/sites/default/files/isa/isa_15576_893881.zip

**Comment by jkmarx** [comment]
#c467d35dfbf81f57d4233acb78bf4738067b7bb5 fixes this issue. The in-progress stage was mislabeled for preprocessing.
