### ISSUE TITLE
enable data set sort by title/name

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#599]
Data sets should be sortable by title/name in the launch pad.

**Comment by flekschas** [comment]
This required separation of name into title and accession number. At the moment the accession number is manually removed from the list so sorting by name leads to confusing results.

**Comment by ngehlenborg** [comment]
What do you think about displaying the accession number as part of the title for now until we can fully resolve this?

**Comment by flekschas** [comment]
We can surely do this but sorting won't result in what I would expect as a user, since data sets will be sorted by their accession number, which is probably not what we want, do we?

**Comment by ngehlenborg** [comment]
For now we can declare "<accession> <title>" as the "title" and do a sort by title. Once the accession is removed at import time the same functionality will deliver more meaningful results.
