### ISSUE TITLE
resizing of browser window duplicates entries in data set list in the launchpad

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#617]
__Reproduce__
Open launchpad in Chrome and preview a dataset visible in the list. Then change height of the browser window to minimum. Then change height of the browser window to the maximum. 

__Observed__
The previewed data set and several others are now duplicated.
![screen shot 2015-08-19 at 12 09 07 pm](https://cloud.githubusercontent.com/assets/1216518/9362035/545997bc-466c-11e5-9fd1-4493b5a77be7.png)
![screen shot 2015-08-19 at 12 08 37 pm](https://cloud.githubusercontent.com/assets/1216518/9362034/54595b08-466c-11e5-97d4-4e8de6be31cc.png)

__Expected__
No duplication of entries in the data set list.

**Comment by flekschas** [comment]
This issue doesn't depend on resizing the window. I actually find duplicated entries even when just scrolling down and up again.
