### ISSUE TITLE
Success message is shown each time a successful analysis is visited.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#619]
This message seems a little redundant as the icon next to the analysis already says it successfully finished.

![bildschirmfoto 2015-08-19 um 13 42 12](https://cloud.githubusercontent.com/assets/932103/9364056/4d6f81c6-4678-11e5-9c63-c3a446c79dbd.PNG)

**Comment by Golii** [comment]
Jpg

**Comment by flekschas** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OPb9nd2Z&#x2F;102-global-error-handling-and-displaying-for-the-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Global error handling and displaying for the UI.</a>

**Comment by jkmarx** [comment]
@ngehlenborg Should we remove the alerts completely?

**Comment by ngehlenborg** [comment]
Yes, I had thought we had done that already in the context of #1415. Although that issues was written after this one.

**Comment by jkmarx** [comment]
@ngehlenborg No, that code was in reference to the old analysis template. The code for this still lives in the the data_set template. There's a bug in it, which I discovered now. So either I fix the bug or move the code related to the alert.
