### ISSUE TITLE
page numbers for analysis list on analysis tab are 0-based

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#623]
__Reproduce__
Run more than 20 analyses on a single data set and open analysis tab for that data set.

__Observed__
First page is numbered `0`.
![screen shot 2015-08-19 at 9 05 30 pm](https://cloud.githubusercontent.com/assets/1216518/9373274/84594fbc-46b6-11e5-835d-77ce7e112642.png)

__Expected__
First page is numbered `1`.

**Comment by jkmarx** [comment]
We're getting rid of the pagination next week because we're adding progressive loading.

**Comment by ngehlenborg** [comment]
To be resolved via #610. Closing.

**Comment by jkmarx** [comment]
Progressive loading is postpone, so issue it reopened.

**Comment by jkmarx** [comment]
Discovered a bug where the pagination skips the first 20 analyses running.
