### ISSUE TITLE
analysis elapsed time not showing on analysis tab

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#624]
__Reproduce__
Launch an analysis with an input file in the GB range (tested with an input FASTQ file with 995 MB).

__Observed__
Analysis is being executed (after file was downloaded from remote server and workflow execution has launched.
![screen shot 2015-08-19 at 9 05 01 pm](https://cloud.githubusercontent.com/assets/1216518/9373293/d18531fc-46b6-11e5-86ad-f975c5a87d38.png)
(Note: this analysis failed for unknown seconds after this screenshot was taken. The same workflow on the same input file had completed successfully before.)

__Expected__
Elapsed time should be shown as soon as the execution launches or possibly even as soon as the analysis launches. Discuss?

**Comment by jkmarx** [comment]
Wouldn't the elapsed time and start time be the same information?
