### ISSUE TITLE
Delete the corresponding Solr doc when a data set is deleted

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#627]
This should probably be handled in the DataSet post-delete signal handler

[Delete Documents From Solr Index By Query](http://blog.dileno.com/archive/201106/delete-documents-from-solr-index-by-query/)

**Comment by ngehlenborg** [comment]
This should also handle batch delete.

**Comment by hackdna** [comment]
Calling delete() on a QuerySet is most likely executed purely in SQL, and so the delete() methods of individual object instances will not necessarily be called during the process. If you’ve provided a custom delete() method on a model class and want to ensure that it is called, you will need to “manually” delete instances of that model (e.g., by iterating over a QuerySet and calling delete() on each object individually) rather than using the bulk delete() method of a QuerySet. (https://docs.djangoproject.com/en/1.5/topics/db/queries/#deleting-objects).

Alternatively (in case of deletion through the admin UI), you can implement a pre_delete or post_delete signal handler. Here's an example: https://github.com/parklab/refinery-platform/blob/develop/refinery/file_store/models.py#L665
