### ISSUE TITLE
Deleting datasets strategy 

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#632]
How to handle deletion datasets?
- Shall it be possible from the Refinery UI.
- Shall we only provide a `manage.py` task.
- How to handle analyses that ran on a dataset should be delete?
  - What if the dataset was public and someone made an analysis? Can the dataset be really deleted?
- How about two steps deletion?
  1. UI deletion == hide and disable
  2. Backend task for real deletion

**Comment by ngehlenborg** [comment]
I think we should distinguish "deleting" from "hiding". What does deletion entail?

1. Removal of data set instance from database and all referenced data structures: analyses and dependencies, investigation, studies, assays, nodes, etc. 
1. Removal of data set from Solr index
1. Removal of associated files from file store.
1. Removal of access permissions in case of shared data sets.

Anything else?

Hiding is almost as complex:

1. Flag data set as hidden (API should no longer return such data sets).
1. Remove from Solr index.
1. Flag associated analyses as hidden.
1. Remove sharing permissions? Might not be required if all analyses and the data set are flagged as hidden.

**Comment by jkmarx** [comment]
Ref: https://github.com/parklab/refinery-platform/issues/253

**Comment by hackdna** [comment]
My use case: simply delete a dataset plus all related objects (including files on disk) through the web UI.

**Comment by jkmarx** [comment]
Feature was implemented in pull request #1445
