### ISSUE TITLE
change URLs in analysis list in launch pad to point to analyses tab of data set

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#633]
__Observed__
http://192.168.50.50:8000/data_sets/77b5dbad-71f9-4f8e-b63a-26ce3e4cdda9/analysis/68e6b459-56ab-4807-9381-a2bf31bd4c0d

__Expected__
http://192.168.50.50:8000/data_sets/77b5dbad-71f9-4f8e-b63a-26ce3e4cdda9/#/analyses

**Comment by flekschas** [comment]
Do we not want to link to an analysis specific page anymore?

**Comment by ngehlenborg** [comment]
Sorry, this change is only meant to be for analyses that are running.

**Comment by ngehlenborg** [comment]
Additional correction: for running and unknown analyses we want these kind of URLs:
http://192.168.50.50:8000/data_sets/77b5dbad-71f9-4f8e-b63a-26ce3e4cdda9/analysis/68e6b459-56ab-4807-9381-a2bf31bd4c0d/#/analyses/

For successful and failed analyses the URLs should not be changed.

**Comment by flekschas** [comment]
Do you have an unknown analysis? I might be wrong but I think unknown analyses don't have an UUID. I'll change the other URLs accordingly.

**Comment by ngehlenborg** [comment]
Analyses in `UNKNOWN` state also have a UUID.
