### ISSUE TITLE
Analyses tab uses space inefficient.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#637]
The analyses tab displays running analyses very space inefficient. While the columns _elapsed time_ and _end time_ are empty they use up more then 1/3 of the whole width. The actual progress bar is squeezed into the name column even though it could be an own row spanning potentially spanning columns _name_, _start time_, _elasped time_ and _end time_ to not have to suffer from line breaks caused by too little space.

Also the percentage on the progress bar is very hard to read if the analyses in the early stage.

![analyses tab](https://cloud.githubusercontent.com/assets/932103/9482723/16179208-4b65-11e5-810f-745acc7ac3fe.png)

**Comment by jkmarx** [comment]
#a2e09e5063e32a8ebcedc419821ada9f8ff68f96 closed this issue. Please note the commit message references the wrong commit.
