### ISSUE TITLE
The dataset nav feature needs refactoring

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#639]
Currently `data-set-nav/` is a set of different features put all together. It'd be better to separate concerns. 

There are two options in my mind:
1. Create a feature directory for datasets and create separate files for each tab's controller
2. Create feature directories for each tab

Our approach should depend on the complexity of the tabs.

**Comment by ngehlenborg** [comment]
@jkmarx: Has this been taken care off in your recent restructuring?

**Comment by jkmarx** [comment]
No, we need to discuss Fritz's suggestions up above.

**Comment by flekschas** [comment]
I added the ticket just as a reminder to refactor the dataset nav [state file](https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/source/js/data-set-nav/state.js) for example. Currently it contains like 5 or more controllers. So its rather bundled by function then by feature. Anyway, this will probably be taken care of when fully _angularizing_ the dataset page.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;endWE5rx&#x2F;22-639"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #639</a>

**Comment by jkmarx** [comment]
Closing this issue because it isn't necessary. The refactoring of the data set nav is on-going with the data set 2 upgrade. Pull request #1413 began the process. After the data set 2 upgrade is complete, this issue will be resolved by default.
