### ISSUE TITLE
Dataset page shows content of all tabs for fragment of a second while loading.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#640]
Until the states are fully loaded one can see the content of all tabs. See screenshot.

![bildschirmfoto 2015-08-26 um 10 43 03](https://cloud.githubusercontent.com/assets/932103/9496668/79e93a64-4bdf-11e5-8269-d624ee12c08d.PNG)

**Comment by jkmarx** [comment]
http://stackoverflow.com/questions/11249768/angularjs-ng-cloak-ng-show-elements-blink
