### ISSUE TITLE
Started analyses never stop (visually) running when Galaxy is down

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#641]
Reproduce:
1. Start an analyses
2. Shut down Galaxy after the job has been sent to it
3. Restart Refinery, i.e. `vagrant halt && vagrant up`

Expected:
When Galaxy is not available the analyses should be on hold, indicated by a non-rotating icon.

Seen:
Galaxy is not available but the monitoring still reports _running_.

**Comment by jkmarx** [comment]
Does restart Refinery mean restart runserver and restart galaxy?

**Comment by jkmarx** [comment]
Currently the api returns 1 of 5 statuses: 
    SUCCESS_STATUS = "SUCCESS"
    FAILURE_STATUS = "FAILURE"
    RUNNING_STATUS = "RUNNING"
    INITIALIZED_STATUS = "INITIALIZED"
    UNKNOWN_STATUS = "UNKNOWN"  # analysis status from Galaxy is not available

There's no pause or idle state if galaxy is shut down. Is it possible to pause an analysis?

**Comment by jkmarx** [comment]
This issue is waiting for a redesign of the analysis api.

**Comment by jkmarx** [comment]
JM could not reproduce issue.  From the code review discussion, we decided this is no longer an issue with the backend updates.

**Comment by ngehlenborg** [comment]
Great news! :+1:
