### ISSUE TITLE
redirect user to analysis tab after analysis has launched

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#648]
We could either redirect to the analyses tab once the user clicks "Launch Analysis" or we could just close the modal and use some visual indicator on the analyses tab to indicate that a new analysis has launched. 

![screen shot 2015-08-26 at 7 09 40 pm](https://cloud.githubusercontent.com/assets/1216518/9508727/28a3ba48-4c26-11e5-9e0c-0b18d420a08a.png)

This step and dialog are no longer necessary now that we can route directly to the analyses tab:

![screen shot 2015-08-26 at 7 09 48 pm](https://cloud.githubusercontent.com/assets/1216518/9508748/7225b9f0-4c26-11e5-845f-ea874e2602fd.png)

**Comment by ngehlenborg** [comment]
@jkmarx @hackdna @flekschas: What do you think is the best option for this?

**Comment by flekschas** [comment]
I think for now we could redirect to the analyses tab since it give some more direct feedback to new users that the analyses is really running. Now, most users are probably not launching analyses like crazy. Later we could add a checkbox, asking to check if the use does not want to be redirected anymore (Like most browsers allow the user to turn of the dialog "Do you want this browser to be your default browser?").

**Comment by ngehlenborg** [comment]
The choice between analyses tab and continuing to browse could also be handled with a third button.

**Comment by flekschas** [comment]
I like this idea. I am just wondering if two buttons are enough: _OK_ (or a click outside of the modal) simple closes the window and a second button, maybe called _Show analyses_ could open the analyses tab.

**Comment by ngehlenborg** [comment]
It could be something like this:

`Cancel` `Launch and View Analyses` `Launch`

`Launch` would be the default.

**Comment by jkmarx** [comment]
I completely prefer the extra button than an auto redirect to analyses. Another option is to add view analyses button to the confirmation analyses launched popup instead of the launching analyses popup.

**Comment by ngehlenborg** [comment]
We could possibly confirm the launch of the analysis directly on the launch dialog:

1. User clicks launch.
2. A spinner appears and he dialog waits for the API response on the analysis status.
3. Analysis status is displayed in the dialog and buttons change from `Cancel` `Launch` to `Close` `View Analyses`

**Comment by jkmarx** [comment]
I always prefer less pop-ups.

**Comment by hackdna** [comment]
I'm in favor of simple is best in general: less pop-ups, less buttons, less clicks, etc. When designing UI we should think of use cases, so imagine what a biologist would typically want to do to help you guide design decisions.

**Comment by jkmarx** [comment]
To achieve the same modal look, I'll need to abandon bootbox. Their animate: false, still makes the modal flash.
