### ISSUE TITLE
Scrollbar madness on the dataset page

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#649]
When making the window smaller and smaller (e.g. 800px wide) I am getting 3 vertical and 3 horizontal scroll bars.

Expected: 1 scrollbar for each dimension, at most 2.

![3 scrollbars](https://cloud.githubusercontent.com/assets/932103/9530598/df68deb8-4cce-11e5-8a35-341dc731192f.png)

**Comment by jkmarx** [comment]
<img width="928" alt="screen shot 2015-09-16 at 7 23 17 am" src="https://cloud.githubusercontent.com/assets/9956764/9903365/e3f578cc-5c43-11e5-8d89-27ed243ab821.png">

**Comment by flekschas** [comment]
I think this case is not really bad. The browser window is so tiny that you need to have two vertical scroll bars as the left side bar is even higher than the main container. The reason I called my observation _madness_ is because I had three vertical scrollbars even though the main container was tall enough!

**Comment by jkmarx** [comment]
I can't produce the triple madness (probably fixed?) and the double only happens sometimes.

**Comment by jkmarx** [comment]
After manual testing, triple scrollbars could not be reproduced.
