### ISSUE TITLE
Longterm running CSS3 animated spinners cause drop of framerate.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#650]
CSS3 animation is smooth and looks nice but it's computationally expensive (or at least browsers don't handle it well). The average frame rate drops from ~60 fps to ~40 fps in **idle mode**! (See screenshot)

GIF spinners don't look too nice but especially when analyses run for long and the user wants to do other stuff to it might be better to switch the analyses CSS-animated spinners to GIF spinners, helping to keep the UI responsive.

![bildschirmfoto 2015-08-27 um 17 18 38](https://cloud.githubusercontent.com/assets/932103/9533464/4a842b60-4ce0-11e5-859a-1efc1a4e3bf5.PNG)

**Note:** Regarding the screenshot: I switched to the about page after recording the profile.

**Note 2:** On my macbook air having two CSS-animated spinners spin for more than 1 or 2 minutes causes the fans to start running at full speed. This might just be an issue with the small MacBook Air but it's not a good sign.

**Note 3:** SMIL-animated SVGs seem to not influence the frame rate but still cause high CPU usage.

**Comment by jkmarx** [comment]
Commit 5fdef398a795eed871187561ba139b2b09ec8156 closes this issue.
