### ISSUE TITLE
height of panels does not always get updated upon window resize

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#657]
Currently unclear why this is happening.

**Comment by ngehlenborg** [comment]
User reported:
> Bug: the frame doesn't go all the way down to the bottom after I used
Developer Tools which was on the bottom half of the window. See attached
image.

**Comment by flekschas** [comment]
This page doesn't work https://refinery-dev.stemcellcommons.org/data_set_manager/import/

**Comment by ngehlenborg** [comment]
Check if panel is using `jquery-full-height` instead of old `scrollable` class.

**Comment by flekschas** [comment]
The class is actually not the problem. It's most likely a race issue: the resizing is triggered before Angular has successfully loaded the partial DOM.

**Comment by jkmarx** [comment]
The bug shows up if you resize the developer tool window by making its
<img width="1440" alt="screen shot 2015-09-01 at 2 39 00 pm" src="https://cloud.githubusercontent.com/assets/9956764/9613070/3cb90b88-50b7-11e5-8ba6-23103e5ee966.png">
 height lower.

**Comment by flekschas** [comment]
To reproduce it consistently:
1. Go to any dataset page
2. Go to _analyses_
3. Go back to _files_
4. Go to _downloads_

Now the panel's height is fixed forever.

**Comment by ngehlenborg** [comment]
Could it have to do with this construct that is used in the routes in https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/src/js/data-set-nav/data-set-nav-state.js (e.g. in [Line 19](https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/src/js/data-set-nav/data-set-nav-state.js#L19)):

```javascript

        // calls global resizing function implemented in base.html to rescale
        // height of scrollable elements timeout is needed to execute after DOM
        // changes
        if ($window.sizing) {
          $timeout(sizing, 0);
        }

        $($window).trigger('refinery/floatThead/reflow');
```

**Comment by flekschas** [comment]
Found the issue:
`.unbind()` removes all eventlisteners

> In the simplest case, with no arguments, .unbind() removes all handlers attached to the elements

https://github.com/parklab/refinery-platform/blob/ee20b2fd51c8fe80d3a268d17612d6de2d973bc5/refinery/ui/src/js/data-set-nav/data-set-nav-ctrl.js#L33
