### ISSUE TITLE
do not show paginator if there is only one page

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#658]
User reported issue:

> it says " << 1 2 3 4 5 >> " at the bottom of the data set page even
though there is only one page of results.'

**Comment by jkmarx** [comment]
We should make all the pagination look similar. On the analyses tab, we have 
<img width="1116" alt="screen shot 2015-09-10 at 9 16 50 am" src="https://cloud.githubusercontent.com/assets/9956764/9789225/b622840e-579c-11e5-9bf8-095ec2e33ed2.png"> .

We may want to switch it to  << 1 2 3 4 5 ...18 19 20 >>. 
<img width="475" alt="screen shot 2015-09-10 at 9 26 00 am" src="https://cloud.githubusercontent.com/assets/9956764/9789402/fb186adc-579d-11e5-9da6-15e56bc4c635.png">

**Comment by scottx611x** [comment]
**SHOWN**
![screen shot 2015-09-23 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/5629547/10058852/9bf5bee2-6215-11e5-91d8-28916325bf53.png)

**HIDDEN**
![screen shot 2015-09-23 at 4 49 51 pm](https://cloud.githubusercontent.com/assets/5629547/10058853/9f71c35e-6215-11e5-9e46-1b8de6adb5b7.png)

**Comment by ngehlenborg** [comment]
Thanks for addressing this @scottx611x. I caught this a bit late and I think we should discuss this issue in the context of #702. Sometimes it is helpful to show UI components even if they are temporarily deactivated. It allows users to develop a mental model of how the site works and helps them to remember where to find certain features.

**Comment by scottx611x** [comment]
@ngehlenborg not a problem, sounds like a plan.
