### ISSUE TITLE
Enable server side gzipping and caching in Apache

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#662]
mod_deflate can be used for gzipping
mod_expires and mod_headers can be used for proper caching

**Comment by ngehlenborg** [comment]
Fritz's sample config: [_htaccess.txt](https://github.com/parklab/refinery-platform/files/16327/_htaccess.txt)

I am happy to test this on our AWS instance but it would only make sense if we could measure performance before and after. @flekschas or @hackdna: Any thoughts on tools that could help with that?

**Comment by hackdna** [comment]
https://developers.google.com/speed/docs/insights/about

**Comment by hackdna** [comment]
Here's a report: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fec2-54-85-203-7.compute-1.amazonaws.com%2F
Also, I wouldn't enable gzipping on the Vagrant VM because it's a dev environment.

**Comment by flekschas** [comment]
For quickly testing compression performance:
http://checkgzipcompression.com/
Example: http://checkgzipcompression.com/?url=http%3A%2F%2Fcellfinder.org

**Comment by ngehlenborg** [comment]
The AWS instance is already using GZIP compression apparently: 
http://checkgzipcompression.com/?url=http%3A%2F%2Fec2-54-85-203-7.compute-1.amazonaws.com%2F

**Comment by ngehlenborg** [comment]
GZIP works for AWS deployed instances.
