### ISSUE TITLE
How to backup Refinery?

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#663]
As soon as we invite other groups to use Refinery in their lab we should have a backup strategy. Of they do some serious analyses and they got lost because of whatever reasons they will probably stop using Refinery.

**Comment by ngehlenborg** [comment]
The following parts need to be backed up:
- database
- file store

For the database an SQL dump should be sufficient. For the file store a simple backup copy should be sufficient. 

Should we also be backing up our job queues in RabbitMQ?

**Comment by ngehlenborg** [comment]
Local settings need to be backed up as well.

**Comment by scottx611x** [comment]
This closes #663. Added [Backing Up A Refinery Instance](https://github.com/parklab/refinery-platform/wiki/Backing-up-a-Refinery-Instance) to the Wiki.
