### ISSUE TITLE
yvanlebras: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by yvanlebras** [parklab/refinery-platform#666]
Dear Refinery platform project managers and collaborators,

I recently heard about your project and the compatibility with ISA-tab specification plus the possibility to use Galaxy tools and workflows. As I specifically work on virtual research environments based notably on the combination of Galaxy and ISAtools, I'm particularly interested to propose my help for this nice project. 

Don't hesitate to come back to me for further informations.

Best Regards,

Yvan<p><br><blockquote>This issue was created by @yvanlebras via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by ngehlenborg** [comment]
Hi Yvan, thanks a lot for introducing yourself. Please let us know if we can help you get started with Refinery and if you have any specific ideas about what you are planning to do with it.

**Comment by hackdna** [comment]
Hi Yvan, it was good to see you at the GCC. We are looking forward for a pull request with Docker related changes.

**Comment by zfrenchee** [comment]
Hi @yvanlebras . I met with some Refinery admins this morning: Ilya and Scott, and I'm interested in this idea of yours to dockerize refinery. Please let me know if I can be of help at all and please keep me posted on your progress.

**Comment by jkmarx** [comment]
There was no follow-up, closing for now.
