### ISSUE TITLE
Empty selection selectable

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#671]
Reproduce:
1. Go to any data set page
2. Deselect everything
3. Click on _analyze_
4. Choose _current selection_
5. Click _launch analysis_

Expected:
1. Analysis shouldn't be launch-able
2. Not selected datasets shouldn't be draggable to _input_file_ and _exp_file_ in regards to the CHiP-Seq workflows.

**Comment by jkmarx** [comment]
I believe this issue was resolved quite some time ago.
<img width="736" alt="screen shot 2016-04-29 at 5 20 42 pm" src="https://cloud.githubusercontent.com/assets/9956764/14930014/cc2feab8-0e2e-11e6-8224-75532afe9191.png">
