### ISSUE TITLE
Default analysis name shown for (running) analyses

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#676]
Reproduce:
1. Start an analyses using the workflow "TF ChIP-Seq analysis using MACS2: hg19". I used `16355: ChIP-Seq of Oct4 in Human Embryonic stem cells.`.
2. Name it differently
3. Push _Launch analysis_

Excepted:
Custom name should be shown

Observed:
Name is replaced with a newly created default name, i.e. notice that the time stamp is equal to the exact time when pushing the button and not the time when entering the name.

**Comment by jkmarx** [comment]
Was the name incorrect in the analysis list?

**Comment by flekschas** [comment]
It worked fine for the test workflow but not for the mentioned _TF ChIP-Seq analysis using MACS2: hg19_.

**Comment by flekschas** [comment]
I observed this issue on refinery-dev.stemcellcommons.org

**Comment by jkmarx** [comment]
I can reproduce the bug locally with the Test Workflow SPP analog.

**Comment by jkmarx** [comment]
The correct name is making it to the post request, so it's a backend issue.

![screen shot 2015-09-11 at 10 18 05 am](https://cloud.githubusercontent.com/assets/9956764/9817047/aee12d62-586e-11e5-8637-04fc9d81f9c0.png)
