### ISSUE TITLE
It's possible to create a group with no name

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#678]
**Excepted**: A group with an empty name shouldn't be allowed.

**Observed**: A group with an empty name is allowed.

After deleting the group with no name and trying to create it again it says

> This name probably already exists - try a different name.

Create, deleting and re-creating a group with an actual name works fine

**Comment by ngehlenborg** [comment]
- [ ] create form validation check
- [ ] implement checks on backend and return error message from server on why creation failed
