### ISSUE TITLE
Dashboard hovering a previewed dataset search result leads to unexpected coloring.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#681]
![bildschirmfoto 2015-09-11 um 11 12 50](https://cloud.githubusercontent.com/assets/932103/9818345/11191a1a-5876-11e5-8f9b-8aae39f18f60.png)

**Comment by scottx611x** [comment]
@flekschas What is the expected behavior for this issue?

**Comment by flekschas** [comment]
@scottx611x potentially a dark blue. In general something with a higher contrast.
