### ISSUE TITLE
Table header partially overlaps with the first row

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#686]
![bildschirmfoto 2015-09-15 um 12 07 33](https://cloud.githubusercontent.com/assets/932103/9882404/74efd69e-5ba2-11e5-8f4e-480d950ba9d5.png)

Expected: No overlap

Observed: Overlap

Potentially caused by unrecognized line breaks in some headers like "Cell line".

**Comment by flekschas** [comment]
@scottx611x disabling line breaks probably solves this issue but might lead to a higher space consumption. Could you upload screenshot for comparison? I'd suggest discussing which way we want to go. (And then close the issue again :))

**Comment by scottx611x** [comment]
![screen shot 2015-09-21 at 6 41 18 pm](https://cloud.githubusercontent.com/assets/5629547/10007082/9066b8e6-6090-11e5-9036-4f89b4eb9ebb.png)
