### ISSUE TITLE
Change start and end time format after some time.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#687]
On the dataset page's analyses tab: the start and end date is relative, e.g. 20 days ago. This is useful for anything that happened not too long ago but after a week it starts to get complicated, e.g. which day was 59 days ago? I'd switch to an absolute time scale. Also, this would make it easier to find an analyses since the user only needs to remember the start date "Jan 1, 2000", e.g. **one** thing, while the relative time changes every day.

![bildschirmfoto 2015-09-15 um 12 13 02](https://cloud.githubusercontent.com/assets/932103/9882655/cde35e1e-5ba3-11e5-96bb-e082096d65c0.png)

Expected: August 25, 2015

Observed: 20 days ago

**Comment by jkmarx** [comment]
<img width="1229" alt="screen shot 2015-09-15 at 8 39 46 pm" src="https://cloud.githubusercontent.com/assets/9956764/9893737/f5336086-5be9-11e5-92ae-8c93a7c1fba5.png">

We can abandon the humanize library which goes from days to months.

**Comment by flekschas** [comment]
Did anything change?

**Comment by jkmarx** [comment]
No, Nils and I just discussed the current format is fine. The tooltip gives more details.
