### ISSUE TITLE
Preselect "current selection" for running analyses

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#690]
What about preselecting the _current selection_. This would save the average user a click and doesn't increase the clicks for users who want to use a stored selection as they have to select it from the drop down anyway.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
This is resolved with Pull Request #1234
