### ISSUE TITLE
Statistics counts datasets differently

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#691]
At https://refinery-dev.stemcellcommons.org I owe one dataset but the statistics pages say I owe 6.

![bildschirmfoto 2015-09-15 um 13 53 34](https://cloud.githubusercontent.com/assets/932103/9885062/3aed77ee-5bb1-11e5-8135-ccf6f136e8ae.png)

![bildschirmfoto 2015-09-15 um 13 53 48](https://cloud.githubusercontent.com/assets/932103/9885063/3f491aaa-5bb1-11e5-9102-a1a24f2ef9c2.png)

(In my case there are 5 _hidden_ datasets)

**Comment by ngehlenborg** [comment]
The counts on the statistics pages are not per user but per instance.
