### ISSUE TITLE
On Dashboard, Analysis list does not update status

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#693]
### Reproduce

1) Start an analysis (a short one like RFC with test workflow.)
2) Navigate back to dashboard.
### Observed

Even though the analysis completes, the dashboard analyses list shows it as running.
<img width="1311" alt="screen shot 2015-09-15 at 8 51 54 pm" src="https://cloud.githubusercontent.com/assets/9956764/9893924/e9070004-5beb-11e5-9da2-d965eba44070.png">
### Expected

The dashboard analyses list status should update when analyses are complete.

**Comment by jkmarx** [comment]
@ngehlenborg Do you think the users will be using the dashboard in a manner where they require analyses monitoring updates? If not, then I suggest closing the issue. Users can click on the analysis link to monitor progress or view in the global.

**Comment by ngehlenborg** [comment]
Does this update when closing and re-opening the popover? If so, we can close this.

**Comment by jkmarx** [comment]
No, it does not update when closing/re-opening the popover. It only occurs when you exit/return to this view.

**Comment by jkmarx** [comment]
We are closing the issue because the dashboard panels will get a redesign. This will no longer be an issue.
