### ISSUE TITLE
Provenance View: Loading Icon Placement 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#698]
### Reproduce
1) On Dev site, choose a dataset you own
2) Resize window in the horizontal direction only

### Observe
<img width="902" alt="screen shot 2015-09-16 at 11 08 49 am" src="https://cloud.githubusercontent.com/assets/9956764/9908890/b45c8310-5c63-11e5-84fb-bc33cb3e0517.png">

### Expect
The container to resize and the loading icon to be in main view.

**Comment by sluger** [comment]
Appended the image into the navbar container. When loading is complete it is set to `display: none`.

![image](https://cloud.githubusercontent.com/assets/5220584/10141417/b99a5df4-660c-11e5-82c5-dcee5cafd056.png)

**Comment by ngehlenborg** [comment]
Won't that cause the button to jump to the left once the loading is complete?

**Comment by sluger** [comment]
I could add an animated transition.

**Comment by ngehlenborg** [comment]
Is there room on the other side of the buttons?

**Comment by sluger** [comment]
yes, see https://github.com/parklab/refinery-platform/commit/25501cbcaf8d95368c7a0f46232f08f208133ff1
