### ISSUE TITLE
Dataset page: table doesn't build properly on initial load

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#699]
https://refinery-dev.stemcellcommons.org/data_sets/c5a87edc-e4f5-437b-88ba-cf9458812582/#/files/browse

After loading:

![bildschirmfoto 2015-09-16 um 11 26 29](https://cloud.githubusercontent.com/assets/932103/9909348/d1d5e678-5c65-11e5-975a-aa709fabf6a4.png)

After manually resizing the browser window:

![bildschirmfoto 2015-09-16 um 11 27 12](https://cloud.githubusercontent.com/assets/932103/9909372/eafbe4ea-5c65-11e5-9418-8cee14f26cb2.png)

**Comment by scottx611x** [comment]
@flekschas what is the name of the plugin that handles the scrollbar within the dataset table here?

**Comment by scottx611x** [comment]
<h3>Now</h3>
**After loading:**
![screen shot 2015-09-24 at 12 01 07 pm](https://cloud.githubusercontent.com/assets/5629547/10078938/5093327c-62b5-11e5-977f-0ede67b10d63.png)

**(no overlap w/ vertical scrollbar)**
![screen shot 2015-09-24 at 12 02 22 pm](https://cloud.githubusercontent.com/assets/5629547/10078923/3f7c1436-62b5-11e5-97c5-db7a01298841.png)

**Comment by flekschas** [comment]
Thanks for taking care of this issue. Unfortunately I am still having original issue. I assume the issue is that the resizer script gets called to early because after resizing the browser window everything looks fine. The overlap issue is related to OS X settings.

**Comment by scottx611x** [comment]
I believe this issue has been taken care of as of commit: 8a18d1a254e72908eefdcd9f7a6c8f81a47fdb8a

@flekschas could you let me know if you're seeing the expected behavior? Thanks

**Comment by flekschas** [comment]
Still seeing the behavior but it's nothing that keeps users from using the site so we can postpone this issue and it will probably be gone after we implemented everything in AngularJS.

**Comment by ngehlenborg** [comment]
Not really an issue for users. Closing.
