### ISSUE TITLE
Collaboration View: New Group should have cancel

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#700]
### Reproduce
 1) On the dev site, go to collaboration view.
 2) Click on add a group icon

### Observe
<img width="602" alt="screen shot 2015-09-16 at 1 46 48 pm" src="https://cloud.githubusercontent.com/assets/9956764/9913192/9446b152-5c79-11e5-880a-7c8aef43293e.png">

### Expect
To be able to cancel out of add a group modal.

**Comment by flekschas** [comment]
Like in most web applications a click outside of the modal closes it.

**Comment by jkmarx** [comment]
With most of our other modals, there's a cancel button.

**Comment by scottx611x** [comment]
Would this be fine? Or would it be better to have some type of spacing between the buttons?

<img width="581" alt="screen shot 2015-09-16 at 2 50 55 pm" src="https://cloud.githubusercontent.com/assets/5629547/9914945/65ca76fc-5c82-11e5-8858-fd942e17a30e.png">

**Comment by flekschas** [comment]
I might be mistaken but isn't the affirmative button (e.g. _okay_, _submit_, _send_, _create group_) always on the right side while the canceling button is on the left? (At least for the permission modal it's implemented this way)

**Comment by scottx611x** [comment]
@flekschas I couldn't find another modal with the cancel functionality so I'm not sure on that

**Comment by jkmarx** [comment]
On the analysis launch, cancel is on the left and the launch (blue) is on the right.

**Comment by scottx611x** [comment]
@jkmarx cool i'll check it out, Thanks

**Comment by scottx611x** [comment]
This one shows the opposite order... I'm confused as to how I  should implement this now.
<img width="691" alt="screen shot 2015-09-16 at 3 16 51 pm" src="https://cloud.githubusercontent.com/assets/5629547/9915794/f9a5fe6a-5c86-11e5-84dd-f84285a98317.png">

**Comment by scottx611x** [comment]
- [ ] Ordering of action vs cancel buttons
- [ ] Coloring of action buttons

**Comment by drj11** [comment]
slack looks like this: (positive action on right, cancel position to the left of it):

![screenshot from 2015-09-17 15 36 23](https://cloud.githubusercontent.com/assets/1215412/9936060/f80bfb9c-5d51-11e5-9376-c20ff03286ba.png)

**Comment by flekschas** [comment]
Most modals in Mac OS seem to put the active / confirming button on the right (or the top) and the cancel button on the left (or bottom)

![bildschirmfoto 2015-09-17 um 11 05 22](https://cloud.githubusercontent.com/assets/932103/9936913/367102fe-5d2c-11e5-8ff9-f136503e645f.png)

**Comment by drj11** [comment]
@flekschas i love the huge picture. :) I guess that's standard apple HIG, which if I was going to pick just one to follow, I'd pick that one.

**Comment by scottx611x** [comment]
This issue is potentially dependant on #648 now that bootbox.js may be abandoned.

**Comment by ngehlenborg** [comment]
Just add the button, we will revisit UI guidelines later.
