### ISSUE TITLE
Create a human interface standard

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#702]
The goal is to provide a unified user experience.
https://en.wikipedia.org/wiki/Human_interface_guidelines#Examples_of_HIGs
https://en.wikipedia.org/wiki/Principle_of_least_astonishment
https://github.com/parklab/refinery-platform/issues/700

**Comment by jkmarx** [comment]
http://www.usability.gov/

**Comment by ngehlenborg** [comment]
Here are a couple of useful examples and even a meta document:

- http://konigi.com/wiki/user-interface-style-guides/
- http://www.theuxbookmark.com/2010/08/ux-articles-and-research-papers/creative-design/a-monster-list-of-ui-guidelines-style-guides/
- http://www.bbc.co.uk/gel
- http://speckyboy.com/2015/01/15/inspirational-examples-ui-style-guides/

**Comment by hackdna** [comment]
also, consider [user experience (UX)](https://en.wikipedia.org/wiki/User_experience):
[The $300 Million Button](http://www.uie.com/articles/three_hund_million_button/)
[Demystifying UX](http://www.slideshare.net/harvardwww/demystifying-ux-a-toolkit-approach-to-better-cheaper-faster-experience-design)

**Comment by jkmarx** [comment]
https://developer.mozilla.org/en-US/Apps/Design
https://www.mozilla.org/en-US/styleguide/
http://www.smashingmagazine.com/2011/10/free-download-cheat-sheet-for-designing-web-forms/
http://files.smashingmagazine.com/wallpapers/images/form-crib-sheet/full_preview.png

Style Guide Example:
https://www.behance.net/gallery/17866351/Style-Guide-for-an-Enterprise-Web-App
https://developers.google.com/apps-script/add-ons/style

Examples of layouts & other sites: 
http://zurb.com/

**Comment by ngehlenborg** [comment]
https://www.google.com/design/spec/material-design/introduction.html

**Comment by flekschas** [comment]
https://ux.stackexchange.com/questions/28937/where-can-i-find-a-comprehensive-list-of-ui-components

**Comment by jkmarx** [comment]
Styleguides I like: 
https://developer.mozilla.org/en-US/Apps/Design
https://www.lightningdesignsystem.com/design/overview

Based on Bootstrap, basic style-guide which is bootstrap component driven.
http://uspto.github.io/designpatterns/1.x/docs/foundation/colors.html
http://www.monolinea.com/projects/styleguide/

**Comment by hackdna** [comment]
[OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/)

**Comment by hackdna** [comment]
[GNOME Human Interface Guidelines](https://developer.gnome.org/hig/stable/)
[KDE Human Interface Guidelines](https://techbase.kde.org/Projects/Usability/HIG)

**Comment by hackdna** [comment]
[U.S. Digital Services Playbook](https://playbook.cio.gov/)
[18F Guides](https://pages.18f.gov/guides/)

**Comment by ngehlenborg** [comment]
https://playbook.cio.gov/designstandards/

**Comment by ngehlenborg** [comment]
After spending at bit more time looking around, I suggest that we start using the USPTO style guide (https://github.com/uspto/designpatterns) and progressively adapt it to our needs. For writing I suggest that we adapt the Firefox OS copy style guide (https://developer.mozilla.org/en-US/Apps/Design/Copy_styleguide) for our system.

The Salesforce Lightning Design style guide (https://www.lightningdesignsystem.com) should serve as a source of inspiration.

For now we can just use the USPTO style guide website. Eventually we can fork their repo and start modifying the content for our needs (their site is a Jekyll-based project, which integrates nicely with Github pages).
