### ISSUE TITLE
Share some Django settings with AngularJS

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#703]
Some Django settings need to be accessed by Angular (like the Admin Mail). For that we need to develop a strategy how to share the settings between them.

**Comment by scottx611x** [comment]
Maybe utilize a structure like this: 
https://github.com/rdegges/django-skel/tree/master/project_name/settings

Divvy up settings that we want to share globally/migrate away from JSON.

**Comment by scottx611x** [comment]
window.refinerySettings.<VALUE>  -> base template
