### ISSUE TITLE
Dataset page shows model for 500 error multiple times.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#706]
Reproduce: https://refinery-dev.stemcellcommons.org/data_sets/fe9edc18-ae83-4956-b6a5-76cd3ba4f704/#/files/browse

Expected: Modal pops up once

Observed: Modal pops up twice

Notice that the first screen has an almost black background while the second one is clearly a bit transparent.

![bildschirmfoto 2015-09-22 um 09 21 53](https://cloud.githubusercontent.com/assets/932103/10019472/9db67894-610b-11e5-872a-2b63511647dd.png)

![bildschirmfoto 2015-09-22 um 09 22 15](https://cloud.githubusercontent.com/assets/932103/10019475/a1ae81f8-610b-11e5-9e28-876c4e2a39e4.png)

**Comment by scottx611x** [comment]
I just fixed this with my most recent commit! This can be closed.

**Comment by scottx611x** [comment]
Closed by f1e43e0e8ef7b12d3bd19139f8c659463ed17c41
