### ISSUE TITLE
Remove related objects when deleting a data set

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#710]
## Steps to reproduce
1. Import a data set
2. Run an analysis on that data set
3. Delete a data set

## Observed results
The following related objects remain: FileStoreItems, Analyses, Node pairs, Node relationships, Nodesets, Assays, Investigations, Studies, etc.

## Expected results
Related objects should be removed

**Comment by ngehlenborg** [comment]
How did you delete the data set? That's not a feature afaik.

**Comment by hackdna** [comment]
Using Django admin UI.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BAQUtRRE&#x2F;179-removing-related-db-objects"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Removing related Db Objects</a>

**Comment by scottx611x** [comment]
__Functionality after commit:__ a399146ac5f9c45a6bf6f3b377b9691da66cc891

```
DataSet.objects.get(id=18).delete()
2016-01-26 08:55:30 ERROR    core.models:1637 dataset_deletion_check() - Cannot delete DataSet:Test 1: Request for Comments (RFC) Test - admin -  because there is has been one or more Analyses run on it.
```
![screen shot 2016-01-26 at 9 00 30 am](https://cloud.githubusercontent.com/assets/5629547/12582477/656d81ae-c40b-11e5-8d99-f607245fab9c.png)
