### ISSUE TITLE
Remove related objects when deleting a workflow

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#711]
## Steps to reproduce
1. Import a workflow from a Galaxy instance
1. Run analysis using that workflow
1. Delete the workflow

## Observed results
The following related objects remain: Workflow data input maps, Workflow data inputs, Workflow files dls, Workflow input relationships, etc

## Expected results
Related objects should be removed

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BAQUtRRE&#x2F;179-removing-related-objects"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Removing related Objects</a>

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BAQUtRRE&#x2F;179-removing-related-objects"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Removing related Objects</a>

**Comment by scottx611x** [comment]
__Functionality after commit:__ a399146ac5f9c45a6bf6f3b377b9691da66cc891

```
Workflow.objects.get(id=56).delete()
2016-01-26 08:57:09 ERROR    core.models:1605 workflow_deletion_check() - Could not delete Workflow, one or more Analyses have been run using it.
```
![screen shot 2016-01-26 at 9 05 14 am](https://cloud.githubusercontent.com/assets/5629547/12582587/167c2900-c40c-11e5-8094-36d953e6ca9e.png)
