### ISSUE TITLE
User registration activation shows meaningless error

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#712]
Reproduce
1. Register a new user
2. Copy activation link from `log/refinery.log`
3. Open link: "activation expired"
4. Try to log in: "activation expired"
5. Log out and log in again: it's working

Observed
Activation expired (see screen) even though the registration was just a minute ago.
Logging in twice successfully activates the user (even though the warning said that the user needs to activate first)

Expected:
No "activation expired" warning
No _magic_ activation after the user logged in twice.

![bildschirmfoto 2015-09-23 um 11 56 11](https://cloud.githubusercontent.com/assets/932103/10050590/25bfd0ca-61eb-11e5-9500-3ba114b46e33.png)

**Comment by ngehlenborg** [comment]
@scottx611x: read about the Django module that we are using to implement this.
