### ISSUE TITLE
Dataset page paired-input analysis cause extra scrollbar

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#717]
Probably only `window.sizing()` needs to be called because after resizing the browser window the height of the table gets adjusted properly.

![bildschirmfoto 2015-09-24 um 14 26 05](https://cloud.githubusercontent.com/assets/932103/10082551/56ce23fa-62c8-11e5-850d-75a8ef2da858.png)

**Comment by scottx611x** [comment]
get rid of setInterval()

**Comment by scottx611x** [comment]
Cloased by c6223fbdda3840ade32c3d2c1ef4e39f2c96b711
