### ISSUE TITLE
Update ui-select2 to ui-select as ui-select2 is deprecated 

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#719]
See here: https://github.com/angular-ui/ui-select2#annoucement
Bugs won't not be fixed anymore plus we reduce the dependencies. The last version `v0.0.5` is almost 2 years old. We are about 36 releases behind.

UI-Select is the native _angularized_ version of Select2.

https://github.com/angular-ui/ui-select

**Comment by ngehlenborg** [comment]
Is used on the data set page and data import for tab-delimited files.

**Comment by flekschas** [comment]
This depends on migrating the dataset page to AngularJS because the newer version of ui.select is a complete rewrite in Angular, meaning that we cannot use it outside of Angular.

**Comment by jkmarx** [comment]
This issue won't be resolved until after the new dataset browser completely replaces the current one. https://trello.com/c/Hs21FuIF/191-dataset-browser-upgrade-phase-1

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-upgrade-phase-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Upgrade, Phase 1</a>
