### ISSUE TITLE
Node mapper throws error when something other than node is dragged onto it

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#720]
Reproduce:
1. https://refinery-dev.stemcellcommons.org
2. Select own dataset
3. Open Analyze and select a workflow with a paired input
4. Drag something other than a node onto the drop area.

**Error:**
> Parsing error: SyntaxError: Unexpected token hd.handleNodeDrop @ node_mapping.js:3
> node_mapping.js:3 Uncaught TypeError: Cannot read property 'uuid' of null

**Comment by ngehlenborg** [comment]
Related to other paired analysis issues, assigning to @jkmarx.
