### ISSUE TITLE
Layout breaks for paired input analyses

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#721]
Reproduce:
1. Go to http://192.168.50.50:8000/
2. Select a dataset with many files
3. Open the _analyze_ tab and select a workflow with a paired input, e.g. chip-seq
4. Drag something into the drop zone >> data table exceeds the white container
5. Drag a second node with a long text into the other drop zone. On smaller screens this causes a horizontal scroll bar.

![bildschirmfoto 2015-09-25 um 19 00 53](https://cloud.githubusercontent.com/assets/932103/10113919/dfb15a1c-63b7-11e5-9505-f49a905dcc56.png)

The issue described in 4. can be fixed by resizing the browser. This will trigger the floatThead plugin to redraw the table. The other issue described in 5. will remain though.

**Comment by scottx611x** [comment]
Closed by 8a18d1a254e72908eefdcd9f7a6c8f81a47fdb8a Accidentally specified wrong issue number.

**Comment by scottx611x** [comment]
get rid of setInterval()
