### ISSUE TITLE
Admin can't share datasets

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#724]
Reproduce:
1. Log in as the admin
2. Choose a dataset you own
3. Open the preview

Observed:
401 error is thrown, saying that the admin doesn't have access to share owned datasets.

![bildschirmfoto 2015-09-28 um 17 08 36](https://cloud.githubusercontent.com/assets/932103/10148877/12bc0f8a-6604-11e5-85f3-ddf5c7fc83bd.png)

@ngehlenborg Which component corresponds to the sharing feature?

**Comment by scottx611x** [comment]
@flekschas I am not able to reproduce this error using the steps mentioned.

**Comment by scottx611x** [comment]
@flekschas I am not able to reproduce this error with a fresh instance.

**Comment by flekschas** [comment]
@scottx611x Thanks for testing again! I tested it on this new single cell rna instance and things worked fine there. Maybe the issue is related to an old index of mine. If the issue pops up again we could re-open it, for now I guess it's not reproducible.
