### ISSUE TITLE
Cannot open the filter & sort dialog in Firefox

### ISSUE THREAD

**Issue by thinkh** [parklab/refinery-platform#726]
Reproduce:
1. Use Firefox 41 on Windows 7 and open https://refinery-dev.stemcellcommons.org/
2. Single click on the Filter & Sort item in any of the three sections (Data Sources, Analyses, Workflows)
3. The dialog appears for a short time and disappears immediately

Result as animated GIF: 
![refinery_filter_dialog](https://cloud.githubusercontent.com/assets/5851088/10163738/34c81950-66b5-11e5-9e66-2474a6fa06ab.gif)

P.S. In Chrome 45 everything works as expected.

**Comment by flekschas** [comment]
Thanks for the gif, I'll investigate what's going wrong. Does the same thing happen for other filters too?

**Comment by thinkh** [comment]
Superb response time! :+1:
