### ISSUE TITLE
Cannot Upload New Dataset 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#727]
### Reproduce
1) On a local instance of Refinery, click on the dataset upload tab on the dashboard.

### Observed
![screen shot 2015-09-29 at 8 59 39 am](https://cloud.githubusercontent.com/assets/9956764/10164647/b1c51e12-6688-11e5-9532-87087581839e.png)
Also, when I try to upload a isatab archive, it times out.

### Expected
No error and to be able to upload a dataset.

**Comment by flekschas** [comment]
Have you tried importing the isatab using the management command?

**Comment by jkmarx** [comment]
No.
