### ISSUE TITLE
Lauch Pair Analysis -- Rename/Delete Should Have Pointer

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#728]
### Reproduce
1) Go to the dataset view - analyze.
2) Select Test Workflow - SPP Analog
3) Select Current Mapping
4) Put cursor on Rename or Delete Text underneath

### Observed
![nodepair cursor](https://cloud.githubusercontent.com/assets/9956764/10165719/afc71326-668e-11e5-9e85-b334ea1f4aac.gif)

### Expected
Default cursor arrow to change to pointer icon for links.
![screen shot 2015-09-29 at 9 45 40 am](https://cloud.githubusercontent.com/assets/9956764/10165761/e7d3361e-668e-11e5-9001-160509a105a8.png)

**Comment by ngehlenborg** [comment]
The problem is that the actions should not be available for the "Current Mapping".

**Comment by jkmarx** [comment]
Issue was fixed because rename and delete links deactivated properly with closing of issue #733.
