### ISSUE TITLE
Uploading the test isatab archive leads to a Solr error

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#729]
- Upload `file-test-type.zip`
- Throws 500 Solr error

![bildschirmfoto 2015-09-29 um 09 47 43](https://cloud.githubusercontent.com/assets/932103/10166058/50813bc4-6690-11e5-8a08-bca16d81dd66.png)

**Comment by ngehlenborg** [comment]
This might have to do with the "hiding" of "useless" facet. @jkmarx can you look into this?

**Comment by jkmarx** [comment]
So, this commit fixes faulty indexing within the facets and prevents a query if either pivot-matrix facets are undefined.

**Comment by ngehlenborg** [comment]
Great!
