### ISSUE TITLE
Scrollbar madness after isatab import

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#730]
> The scrollbars are back!

Reproduce:
1. Upload an isatab
2. After the import finished and it loads the table I see a scrollbar on the top right for display type and on the left, under the analyses filter.

![bildschirmfoto 2015-09-29 um 09 48 49](https://cloud.githubusercontent.com/assets/932103/10166143/b65f52b4-6690-11e5-9d8d-7e0ab6bc62c4.png)

**Comment by jkmarx** [comment]
@ngehlenborg @hackdna @scottx611x  I cannot reproduce this issue and have never encountered it before. If no one can reproduce it, I'd recommend closing it.

**Comment by jkmarx** [comment]
See above comment.
