### ISSUE TITLE
Pair Analysis - Cannot delete node pair

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#733]
### Reproduce
1) Dev tool open & Local Dev instance
2) Open dataset 15576: BCL11A cistrome in mouse erythroleukemia (MEL) cells and choose analyze
3) Choose Test Workflow: SPP Analog workflow
4) Choose current mapping
5) Drag/Drop a pair of nodes
6) Click the delete text

### Observed
The console will throw a cannot delete error and nodes do not delete.
![screen shot 2015-09-29 at 10 18 30 am](https://cloud.githubusercontent.com/assets/9956764/10166766/76433aee-6693-11e5-9c18-005e31118bd6.png)

### Expected
Error handling or no error.

**Comment by ngehlenborg** [comment]
Related to #728

**Comment by jkmarx** [comment]
http://onehungrymind.com/quick-note-ng-disabled-and-anchor-tags-oh-noes/
