### ISSUE TITLE
Add latest commit hash to site

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#741]
This will aid in debugging which code is being used by a specific instance.
Potentially add this info within the `About` tab.

**Comment by ngehlenborg** [comment]
`git rev-parse HEAD` provides the commit hash. Alternatively we could use `git describe`. We should integrate this into our build process and store the git info either in the settings.json or in a separate file that we can access from both Python and JavaScript.

**Comment by scottx611x** [comment]
@ngehlenborg Sorry, I did not see this comment before I closed this issue, but I ended up using `git rev-parse HEAD` regardless.

**Comment by hackdna** [comment]
Note that if the subprocess call to launch git produces an exception the whole application will fail to start.

**Comment by scottx611x** [comment]
@hackdna Thanks for the heads up. Fixed this in 9dcd4f5a0583a34340928ea954e9e7d8387951d9.

**Comment by scottx611x** [comment]
fix try/except, add `except Exception:`

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;07vPX8p7&#x2F;101-include-build-version-number-in-ui-for-bug-error-reporting"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> include build&#x2F;version number in UI for bug&#x2F;error reporting</a>

**Comment by scottx611x** [comment]
Closed with commit: a100b05182eb01744acda9702a1b35a55abec3eb

**Comment by hackdna** [comment]
Reopening, please see [my comment on your commit](https://github.com/parklab/refinery-platform/commit/a100b05182eb01744acda9702a1b35a55abec3eb#commitcomment-15833087) for details.

**Comment by hackdna** [comment]
Fixed in f48b57f

**Comment by hackdna** [comment]
Running fe77b29. Commit URL is displayed as [git@github.com:parklab/refinery-platform/commit/fe77b29e84accc87221daca0333d9f040c5f5db3](http://192.168.50.50:8000/about/git@github.com:parklab/refinery-platform/commit/fe77b29e84accc87221daca0333d9f040c5f5db3).

**Comment by ngehlenborg** [comment]
Can you describe what you expect?

**Comment by hackdna** [comment]
The link is broken, it should point to Github, for example: https://github.com/parklab/refinery-platform/commit/fe77b29e84accc87221daca0333d9f040c5f5db3. In any case, this is not a priority at the moment.

**Comment by scottx611x** [comment]
@hackdna I'm not going to work on this immediately, but could you tell me what settings configuration you were using for this, as well as anything else that I would need to replicate the issue?

**Comment by drj11** [comment]
the "URL" comes from the git remote whence the git repo was cloned.

See this code in base.py: https://github.com/parklab/refinery-platform/blob/fe77b29e84accc87221daca0333d9f040c5f5db3/refinery/config/settings/base.py#L475

So if you used a git remote of the form `git@github.com...` then the URL will start with that, if you use a git remote of the form `https://github.com...` then it will start like that.

the AWS install uses `https://github.com/parklab/refinery-platform.git` as the remote, so it should get the right URL (haven't tried it, it's broken for other reasons right now. *sigh*).

We can of course translate from `git@github.com:` to `https://github.com/` for github, but for other remotes we cannot in general know what the right translation is.

**Comment by scottx611x** [comment]
@drj Thanks for shedding some light on this!

**Comment by drj11** [comment]
As per my previous comment, it shows the right URL on an AWS install, because of the git remote I use:

![giturl](https://cloud.githubusercontent.com/assets/1215412/12972657/fe9b61c6-d09e-11e5-8d49-e36dfff30181.png)

The hover-over is cute. :panda_face:

**Comment by scottx611x** [comment]
Closing as now we just include the full SHA without a link.
