### ISSUE TITLE
Set up tracking of Angular pages using Google Analytics

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#748]
GA is not tracking requests to URLs that don't reload the page.

Resources:
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
http://stackoverflow.com/questions/18626788/enable-google-analytics-for-single-page-site-with-views
http://www.marcusoft.net/2015/05/how-to-get-google-analytics-to-work-for-your-single-page-application.html
http://luisfarzati.github.io/angulartics/
https://github.com/revolunet/angular-google-analytics

**Comment by flekschas** [comment]
For which resources would you like to set this up? E.g. tracks individual tabs on the dataset page or regard the dataset preview on the launch pad as a separate page?

**Comment by ngehlenborg** [comment]
Let's track every individual URL change.

**Comment by hackdna** [comment]
Clicks on any of the tabs in the data set view are still not registered in GA. Running commit c569c26.

**Comment by flekschas** [comment]
How long did you wanted? I'd need the tracker code and login details for debugging.

**Comment by flekschas** [comment]
Okay I cannot work because my changes were overwritten by: https://github.com/parklab/refinery-platform/commit/4067ad1f66f49395bb21a9a372d12335107f2dee#diff-722a042e7f6a926dcb35c34cd50f42ec

**Comment by flekschas** [comment]
@hackdna Could you try again with commit a8800836279975cb6a9248315d6ad42331ed97c8?

**Comment by flekschas** [comment]
Should work now after the merge hick-up has been solved.

**Comment by hackdna** [comment]
Was this fix tested?

**Comment by flekschas** [comment]
"@hackdna Could you try again with commit a880083?" There is no way to test this because I don't have the login credentials to Google Analytics.

**Comment by hackdna** [comment]
Will do. Please don't close the issues until the fix has been tested.
