### ISSUE TITLE
Order of facets change based selection

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#751]
**Reproduce:**
1. Go to: https://refinery-dev.stemcellcommons.org/data_sets/5cdb64d1-ef23-4523-8540-5a0f39501a9b/#/files/browse
2. Open _File Type_ and _Genotype_ facets
3. Select _N/A + s5 point mutation_
4. The _File Type_ facts are reordered!

**Expected:**
No reordering

**Observed:**
Looks like facets are ordered by their size.

![reorder](https://cloud.githubusercontent.com/assets/932103/10613619/e58393d6-7723-11e5-9728-93a00454391b.gif)

---

Question: To me this is kind of confusing because it's not directly obvious. What do others think?

**Comment by ngehlenborg** [comment]
It is default behavior because the facet values are sorted in descending order.

**Comment by ngehlenborg** [comment]
This could be addressed by providing options to sort and filter facet values, e.g. in the dataset browser redesign. @jkmarx: something to consider.
