### ISSUE TITLE
Replace ng-grid with ui-grid

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#754]
"ng-grid has being rewritten as UI Grid, it's now stable"
http://angular-ui.github.io/ui-grid/

**Comment by jkmarx** [comment]
http://ui-grid.info/docs/#/tutorial/099_upgrading_from_2

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c9RdRyno&#x2F;176-bootstrap3-upgrade"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Bootstrap3 Upgrade</a>

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;d2WDkQFt&#x2F;177-754"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #754</a>

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;d2WDkQFt&#x2F;177-754"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #754</a>
