### ISSUE TITLE
Find a way to delete old installations of tools when upgrading during provision

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#756]
When upgrading third party services like Solr, Neo4J or Owl2Neo4J a new installation is created but the old one remain untouched. In many (all?) cases the source code is separated from configuration so it would be easy to reinstall an old version of needed. For that reason, would it be good to automatically remove old verions?

**Comment by ngehlenborg** [comment]
For standalone packages and applications this is most likely not going to be an issue.
