### ISSUE TITLE
Fetching the sharing status slows down an API call dramatically

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#758]
Background:
My admin has access to ~350 data sets. A single query for 10 datasets used to come at 50-70ms. With the sharing information being fetched the same query takes 500ms on average.

The particular line of code is this https://github.com/parklab/refinery-platform/blob/develop/refinery/core/api.py#L145

**Comment by ngehlenborg** [comment]
We could try to pull `get_groups_with_perms(res)` outside the loop and handle it similar to how we are handling the other two attributes.
