### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#765]
I've tried to update my develop branch (was about a week old) using `fab vm update` and ran unto the following error:

```
[vagrant@127.0.0.1:2222] out: Error in migration: file_store:0005_auto__add_field_filestoreitem_filetype
[vagrant@127.0.0.1:2222] out: IntegrityError: insert or update on table "file_store_filestoreitem" violates foreign key constraint "filetype_id_refs_id_77b79973bce037d0"
[vagrant@127.0.0.1:2222] out: DETAIL:  Key (filetype_id)=(33) is not present in table "file_store_filetype".
```

**Comment by flekschas** [comment]
This solved the issue:

```
./manage.py loaddata file_store/fixtures/initial_data.json
```

**Comment by ngehlenborg** [comment]
I am just trying to update my VM (which had no seen any updates in about a month) and I am running into this exact problem in 5a5580b5b2222607270333f0d0703700a1ef39a0.

**Comment by scottx611x** [comment]
Closed as a non-issue.
A developer starting with a clean instance will not run into this issue. 
This issue only occurs in one-off cases so providing the command: `./manage.py loaddata file_store/fixtures/initial_data.json` to alleviate any occurrences of this is sufficient.
