### ISSUE TITLE
Upgrade Puppet apt module to the latest version

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#774]
Currently used version 1.8.0 is significantly out of date (the latest is 2.3.0 as of Nov 2016): https://forge.puppetlabs.com/puppetlabs/apt

There were significant changes including deprecations in release 2.0.0: https://forge.puppet.com/puppetlabs/apt/2.0.0/changelog

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OejRcN0q&#x2F;15-implement-single-instance-aws-deployment"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> implement single instance AWS deployment</a>

**Comment by drj11** [comment]
Things I've discovered so far:

Updating all of the puppet modules to their latest seems to work okay, but generates a few more deprecation warnings. I'll fix those before committing.

Changing the `Puppetfile` will break any future `librarian-puppet install` unless `Puppetfile.lock` is removed. So that affects the next `vagrant provision` after a change to `Puppetfile`. The `librarian-puppet` documentation http://librarian-puppet.com/ implies that you should version control `Puppetfile.lock`, but that seems a bit weird to me.

**Comment by drj11** [comment]
@hackdna and I just agreed that we'd look and see if version controlling `Puppetfile.lock` is in fact more in line with librarian-puppet best practice.

**Comment by hackdna** [comment]
And if that turn out to be a hassle we could also simply delete `Puppetfile.lock` before running the Puppet provisioner since it is automatically rebuilt from `Puppetfile`.

**Comment by hackdna** [comment]
Delaying this since not required for AWS deployment work

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mkJDIE8b&#x2F;24-774"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #774</a>

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Troubleshoot neo4j key fingerprint mismatch error](https://trello.com/c/P0wawViL/87-troubleshoot-neo4j-key-fingerprint-mismatch-error)

**Comment by hackdna** [comment]
Relevant backward incompatible changes:

apt::key
* key - This parameter was renamed to id.
* key_content - This parameter was renamed to content.
* key_source - This parameter was renamed to source.
* key_server - This parameter was renamed to server.
* key_options - This parameter was renamed to options.

apt::source
* include_src - This parameter was removed. Use include => { 'src' => <bool> } instead. NOTE This now defaults to false.
* include_deb - This parameter was removed. Use include => { 'deb' => <bool> } instead.
required_packages - This parameter was removed. Use package resources for these packages if needed.
* key - This can either be a key id or a hash including key options. If using a hash, key => { 'id' => <id> } must be specified.
* key_server - This parameter was removed. Use key => { 'server' => <server> } instead.
* key_content - This parameter was removed. Use key => { 'content' => <content> } instead.
* key_source - This parameter was removed. Use key => { 'source' => <source> } instead.
trusted_source - This parameter was renamed to allow_unsigned.

**Comment by hackdna** [comment]
```
vagrant@refinery:~$ puppet module upgrade puppetlabs-apt --version 2.3.0 --modulepath=/vagrant/deployment/modules
Notice: Preparing to upgrade 'puppetlabs-apt' ...
Notice: Found 'puppetlabs-apt' (v1.8.0) in /vagrant/deployment/modules ...
Notice: Downloading from https://forge.puppetlabs.com ...
Error: Could not upgrade module 'puppetlabs-apt' (v1.8.0 -> v2.3.0)
  No version of 'puppetlabs-apt' will satisfy dependencies
    You specified 'puppetlabs-apt' (v2.3.0)
    'puppetlabs-nodejs' (v0.7.1) requires 'puppetlabs-apt' (>=0.0.3)
    'puppetlabs-postgresql' (v4.3.0) requires 'puppetlabs-apt' (>=1.8.0 <2.0.0)
    'puppetlabs-rabbitmq' (v5.1.0) requires 'puppetlabs-apt' (>=1.0.0 <2.0.0)
    Use `puppet module upgrade --force` to upgrade this module anyway
```
