### ISSUE TITLE
Provenance View: Bootstrap3 Upgrade

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#777]
## Reproduce
1) Pull from bootstrap3_upgrade branch
2) fab vm conf:gdev or grunt build
3) View locally 

Updates Requires (http://getbootstrap.com/migration/)
- [x] Update layouts row fluid/span to row/col-md https://github.com/parklab/refinery-platform/commit/fe239b31cead65f02d280edb343743a91907b151
- [x] Update button size classes https://github.com/parklab/refinery-platform/commit/40c9328b835f89e986512c452a6efdaf7477b0e9
- [x] Modal classes http://getbootstrap.com/javascript/#modals
- [x] Accordion classes http://getbootstrap.com/javascript/#collapse-example-accordion
- [x] Provenance graph does not load 
- [x] CSS updates

**Comment by jkmarx** [comment]
I made some minor changes a couple of weeks ago (btn and grid classes), please view the blame mode below.
https://github.com/parklab/refinery-platform/blame/bootstrap3_upgrade/refinery/ui/source/js/provvis/partials/provvis-navbar.html

https://github.com/parklab/refinery-platform/blame/bootstrap3_upgrade/refinery/ui/source/js/provvis/partials/provvis-canvas.html

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c9RdRyno&#x2F;176-bootstrap3-upgrade"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Bootstrap3 Upgrade</a>

**Comment by sluger** [comment]
Unfortunately I am stalled as I can't upload ISA-tab archives. See the issue i created: https://github.com/parklab/refinery-platform/issues/784

**Comment by sluger** [comment]
I have completed all my updates with the latest commit: 4b0f34d74ad08a32c53923923bec0f11c99bce92
