### ISSUE TITLE
Dashboard: Bootstrap3_upgrade

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#782]
## Reproduce
1) Pull from bootstrap3_upgrade branch
2) fab vm conf:gdev or grunt build
3) View locally 

Updates Requires (http://getbootstrap.com/migration/)
- [x] Update layouts row fluid/span to row/col-md 
http://getbootstrap.com/css/#grid
https://github.com/parklab/refinery-platform/commit/fe239b31cead65f02d280edb343743a91907b151
- [x] Update button size classes https://github.com/parklab/refinery-platform/commit/40c9328b835f89e986512c452a6efdaf7477b0e9
- [x] Modal classes http://getbootstrap.com/javascript/#modals
- [x] Preview box does not float properly.
![preview-error1](https://cloud.githubusercontent.com/assets/9956764/11406228/5958d1aa-937a-11e5-9507-e90c920924de.gif)

**Comment by flekschas** [comment]
Fixed all visual hiccups by 0ed1717105264d006b4f7fe0c69f90ce0396e5f3.
