### ISSUE TITLE
ISA-tab upload fails in branch bootstrap3_upgrade

### ISSUE THREAD

**Issue by sluger** [parklab/refinery-platform#784]
**Prerequisites**
New and clean local deployment of refinery.
Workflow import success.
Added all permissions to my user and group.
No errors during deployment.

## Steps to reproduce
Log into Refinery locally.
Click Upload.
Upload any ISA archive.
I have tested several archives that were working for me the last year.

## Observed result
"Problem parsing ISA-Tab file"
No errors in console.

## Expected result
Upload successfully.

## Investigation
On `grunt build` i observed the following:
`>> Destination ../static/development/styles/css/font-awesome-ie7.css not written because no source files were found.`

Console log on landing and upload page:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.4.7/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20MetadataTableImportCtrl
    at Error (native)
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:6:416
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:40:409
    at Object.d [as get] (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:38:394)
    at http://192.168.50.50:8000/static/vendor/angular/angular.min.js:40:483
    at d (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:38:394)
    at Object.e [as invoke] (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:39:161)
    at P.instance (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:80:207)
    at K (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:61:190)
    at g (http://192.168.50.50:8000/static/vendor/angular/angular.min.js:54:410)
```

Upload UI seems to have some issues too:
![image](https://cloud.githubusercontent.com/assets/5220584/11420705/24f95838-9430-11e5-997c-497e5f81072f.png)

**Comment by flekschas** [comment]
Have you tested the command line? This would help to figure out if it's a UI or backend issue. See the wiki for instructions: https://github.com/parklab/refinery-platform/wiki/import-isatabs

**Comment by sluger** [comment]
Thanks fritz, the upload was successful through the console.

**Comment by jkmarx** [comment]
It seems to be working fine in the merged develop branch. @sluger If you come across it again in the develop branch, please feel free to reopen. I believe the console errors may have been due to the bower.json which is correct now.
