### ISSUE TITLE
Make sure that config.json is updated during provisioning

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#785]
It seems that `config.json` is not untouched during provisioning even when `config.json.sample` changed. This is problematic as it leads to issues that seem unrelated in the beginning.

E.g. Nils reported:
```
./manage.py collectstatic --clear --noinput
Unknown command: 'collectstatic'
```

While the actual issue was the missing `LIBS_DIR` entry in `config.json`.

Replacing an existing `config.json` might l lead to other issues though. Best would be to merge the two JSON files; adding new entries but retain existing options. I had a quick look and found two command line tools that can merge JSON files:
 - https://stedolan.github.io/jq/ (How to merge: https://stackoverflow.com/questions/19529688/how-to-merge-2-json-file-using-jq)
 - http://trentm.com/json/

**Comment by ngehlenborg** [comment]
@flekschas says it has been fixed. Closing.
