### ISSUE TITLE
Refinery / Bootstrap 3 buttons are hard to see

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#787]
Out buttons have no outline, white background and just a little but of shadow.

I notice that the standard bootstrap 3 button features no shadow but an outline: http://getbootstrap.com/css/#buttons

![bildschirmfoto 2015-11-27 um 15 08 09](https://cloud.githubusercontent.com/assets/932103/11447701/b483f344-9518-11e5-8ccc-cccf9bdecc2a.png)

**Comment by jkmarx** [comment]
<img width="92" alt="screen shot 2015-12-02 at 9 58 33 pm" src="https://cloud.githubusercontent.com/assets/9956764/11550705/488058e6-9940-11e5-96c4-88f10140383f.png">
Shadow buttons, no outline. I'll add the shadow back.
