### ISSUE TITLE
Tabular metadata file upload form is not displayed correctly

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#790]
The form should not appear before a file is selected. Running commit 6eec78c.
![image](https://cloud.githubusercontent.com/assets/5220584/11420705/24f95838-9430-11e5-997c-497e5f81072f.png)

**Comment by hackdna** [comment]
Fixed as of 4c7f34b. However, the following error message is displayed in the browser console when a file is selected:
```
TypeError: f.options.columnDefs.forEach is not a function
    at p.buildColumns (ui-grid.min.js:7)
    at m (ui-grid.min.js:7)
    at Object.fn (angular.js:15775)
    at r.$digest (angular.js:15843)
    at r.$apply (angular.js:16125)
    at FileReader.c.onload (metadata-table-import.js:72)
```

**Comment by hackdna** [comment]
One more issue: initial column width used to be set automatically according to the column header length to make them more readable. Now all the columns are equally narrow and headers are unreadable unless manually resized. The code that performs the calculation is [here](https://github.com/parklab/refinery-platform/blob/develop/refinery/ui/source/js/metadata-table-import.js#L38).

**Comment by jkmarx** [comment]
Since we've reopened this issue, in Firefox only:
<img width="927" alt="screen shot 2015-12-03 at 11 58 32 am" src="https://cloud.githubusercontent.com/assets/9956764/11571181/15005104-99c9-11e5-9b35-1eb4babb0cbf.png">

**Comment by hackdna** [comment]
Thanks for bringing this up. It looks like styling is missing from buttons and drop-downs in Firefox too.

**Comment by jkmarx** [comment]
From the bootstrap components website http://getbootstrap.com/components/ : 
Textual <input>s only

Avoid using <select> elements here as they cannot be fully styled in WebKit browsers.

Avoid using <textarea> elements here as their rows attribute will not be respected in some cases.

**Comment by jkmarx** [comment]
@hackdna This is the default bootstrap3 styling. Chrome has it's own styling which is being applied.
<img width="768" alt="screen shot 2015-12-03 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/9956764/11574930/756070c0-99dc-11e5-806a-8cccb485242b.png">

**Comment by jkmarx** [comment]
@flekschas @hackdna @ngehlenborg I fixed the column situation. If you agree, I'd like to close this issue and write a separate issue for tackling uniform styling between browsers and updating styling to the new style guide http://uspto.github.io/designpatterns/1.x/docs/patterns/fileUpload.html

**Comment by jkmarx** [comment]
No that issue is fixed. 
![screen shot 2015-12-04 at 10 03 48 am](https://cloud.githubusercontent.com/assets/9956764/11592739/5ee24930-9a6e-11e5-8743-ecd4e920f749.png)

**Comment by ngehlenborg** [comment]
I agree with that plan.

**Comment by hackdna** [comment]
Looks good.
