### ISSUE TITLE
Dataset filters not displaying nicely

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#791]
**Reproduce:**

While viewing a Dataset click the dropdown menus on the left side of the page.

**Observed:**

 ![nov 30 2015 11 58](https://cloud.githubusercontent.com/assets/5629547/11481422/70c0123c-976b-11e5-98b4-c87f1873fad5.gif)

- [x] Fix animation above

- [x] Fix animation below (duplicate entry for a sec)

- -- Fix attribute filter which show 0 matching sets (See Issue #811 )

- [x] Fix duplication for selected attributes

- [x] Fix caret for expand/collapse views

**Expected:**

The text-overlapping seen above shouldn't occur.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BAQUtRRE&#x2F;179-removing-related-db-objects"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Removing related Db Objects</a>

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bO2LRwDK&#x2F;181-791-dataset-filter-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #791 Dataset Filter Issues</a>

**Comment by jkmarx** [comment]
<img width="246" alt="screen shot 2015-12-03 at 12 09 07 pm" src="https://cloud.githubusercontent.com/assets/9956764/11567786/c43fbd34-99b6-11e5-954b-533317fdc2f6.png">

<img width="230" alt="screen shot 2015-12-03 at 12 09 15 pm" src="https://cloud.githubusercontent.com/assets/9956764/11567791/c8d431ae-99b6-11e5-99c7-7fb7d4e57bc5.png">

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SRuCboFt&#x2F;188-attribute-analysis-filter"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Attribute&#x2F;Analysis Filter</a>

**Comment by jkmarx** [comment]
![collapsefilter](https://cloud.githubusercontent.com/assets/9956764/11728302/14af5662-9f57-11e5-9e10-704bca2f17e3.gif)
