### ISSUE TITLE
Tabular File Upload Table View

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#795]
### Reproduce
1) Locally, upload a tabular file PCBC-mRNA-fixed (1)

### Observed
On the initial load: 
<img width="1223" alt="screen shot 2015-12-03 at 9 16 49 am" src="https://cloud.githubusercontent.com/assets/9956764/11562912/dc5120ce-999e-11e5-8232-c5f1222c1ca0.png">
After resizing the window:
<img width="1232" alt="screen shot 2015-12-03 at 9 17 02 am" src="https://cloud.githubusercontent.com/assets/9956764/11562918/e4cc39be-999e-11e5-8268-fa38bcbec6bb.png">

### Expected
The second image in initial load.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ak1no1Wb&#x2F;183-795-tabular-file-upload-table-view-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #795 Tabular File Upload Table View Issue</a>

**Comment by jkmarx** [comment]
https://github.com/angular-ui/ui-grid/issues/855

**Comment by jkmarx** [comment]
@hackdna @ngehlenborg I fixed the column situation. If you agree, I'd like to close this issue and write a separate issue for tackling uniform styling between browsers and updating styling to the new style guide http://uspto.github.io/designpatterns/1.x/docs/patterns/fileUpload.html

**Comment by flekschas** [comment]
Does the table look like the second screenshot above? I remembered that before (bootstrap v2) the table was horizontally scrollable, which isn't great but labels were readable. PS: the ticket is already closed ;)

**Comment by jkmarx** [comment]
No that issue is fixed. 
![screen shot 2015-12-04 at 10 03 48 am](https://cloud.githubusercontent.com/assets/9956764/11592739/5ee24930-9a6e-11e5-8743-ecd4e920f749.png)

**Comment by jkmarx** [comment]
Ugh..sorry wrong issue!
