### ISSUE TITLE
Two import buttons are confusing

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#797]
After selecting a tabular file for import the user sees two import button. One two third from the top and the other one at the very end of the page. I clicked a couple of times on the wrong import button because I assume that final actions are at the end of a page.

My question is: is there a need for showing the isatab form when trying to import a tabular file? Hiding it would avoid confusion.

![bildschirmfoto 2015-12-03 um 11 37 50](https://cloud.githubusercontent.com/assets/932103/11566947/b6b49526-99b2-11e5-94cb-e063c5f99595.png)

**Comment by ngehlenborg** [comment]
Let's wrap the options into an accordion control so that only one import option is visible at a time.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Data import UI</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-update-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update data import UI</a>

**Comment by jkmarx** [comment]
Resolved issue with the new data import layout. Ref #1336
