### ISSUE TITLE
Sync Postgres Updates with Solr

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#802]
### Reproduce
1) Locally in the admin interface http://192.168.50.50:8000/admin, delete an analysis. (Please note the uuid and which dataset it belongs to.)
2) Locally in the regular view http://192.168.50.50:8000/#/ , go to the dataset browser
3) Click on the analysis filter

### Observed
Note, all the 0 were previously deleted analyses. The analysis with 1, I just deleted and Solr still maintains the info.
<img width="261" alt="screen shot 2015-12-04 at 2 43 22 pm" src="https://cloud.githubusercontent.com/assets/9956764/11599668/34537108-9a96-11e5-987d-0a669d14e3ed.png">

### Expected
Deleted analyses to not show in the filter.

**Comment by scottx611x** [comment]
Related with #711 #710

**Comment by jkmarx** [comment]
I was able to clean up the old analyses by deleting and reindexing. ```./manage.py rebuild_index --using=data_set_manager --batch-size=25```

**Comment by scottx611x** [comment]
According to @flekschas : "This is probably caused by the fact that Solr's index is not destroyed when running vagrant destroy. To avoid it: either delete the vm completely or rebuild / drop Solr's index."

**Comment by scottx611x** [comment]
@fritz You mentioned that you have performed something along these lines before. Could you point me to that code?

**Comment by flekschas** [comment]
@scottx611x 
Yep for the datasets. For example when you delete a dataset the pre_delete signal will trigger an index update:
1. Signal: https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L601
2. Deletion: https://github.com/parklab/refinery-platform/blob/develop/refinery/core/utils.py#L198-L203

**Comment by hackdna** [comment]
Any considerations for pre_delete vs post_delete?

**Comment by flekschas** [comment]
How do you want to access the dataset option after it was deleted?

**Comment by hackdna** [comment]
So, pre_delete must be used?

**Comment by scottx611x** [comment]
The fix from commit: 1c25ce3 seems to work only 90% of the time. 
Once in a while upon Analysis deletion something remains within Solr.

See:
![screen shot 2015-12-17 at 1 36 32 pm](https://cloud.githubusercontent.com/assets/5629547/11878347/3caaf330-a4c3-11e5-9901-e61de493362a.png)

Currently looking into this
