### ISSUE TITLE
Prepare deployment scripts for use with EBS and RDS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#805]
Continuing the work started in #420.

- [x] Work on amazon with separate `.pp` file https://github.com/parklab/refinery-platform/pull/798
- [x] Split `.pp` files so that most of it is shared, with small blocks for each of Vagrant and AWS #828
- [x] Template `apache.conf` (and share)
- [x] Template `config.json` (note: might all change anyway)

~~- [ ] Separate RDS instance~~ split out into #835
~~- [ ] Separate EBS~~ split into #837

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OejRcN0q&#x2F;15-implement-single-instance-aws-deployment"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> implement single instance AWS deployment</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sBJxolm4&#x2F;195-implement-deployment-to-aws-using-ebs-and-rds"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement deployment to AWS using EBS and RDS</a>

**Comment by hackdna** [comment]
I suggest a few additional changes:

1. move `deployment/modules` outside of the project dir (e.g., to `/tmp/modules`)
1. rename `deployment/refinery-modules` to `deployment/modules`
1. break up `deployment/modules/refinery` into separate modules (e.g., database, virtualenv, webserver, solr, neo4j, ui, etc)
1. move `deployment/.tmp` and `deployment/.librarian` outside of the project dir

Resources:
http://blog.james-carr.org/2014/05/05/effective-puppet-module-management-in-vagrant/
Tell the librarian where to put its modules:
`librarian-puppet config --local path modules-contrib`

**Comment by drj11** [comment]
1. good idea, https://github.com/parklab/refinery-platform/issues/853
2. not sure; it might be confusing because `modules` is where the installed modules usually are.
3. is going to happen anyway. don't think it needs a separate issue
4. good idea, https://github.com/parklab/refinery-platform/issues/854

**Comment by drj11** [comment]
everything remaining to be done is in other issues now. closing.
