### ISSUE TITLE
Dataset sharing API is broken

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#809]
The sharing on the dataset preview doesn't work anymore.

When accessing the sharing API for datasets:

```
http://192.168.50.50:8000/api/v1/data_sets/<UUID>/sharing/?format=json
```

Django is throwing the following error:

```
{"error_message": "'list' object has no attribute 'model'", "traceback": "Traceback (most recent call last):\n\n  File \"/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py\", line 202, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/vagrant/refinery/core/api.py\", line 295, in res_sharing\n    return self.process_get(request, res, **kwargs)\n\n  File \"/vagrant/refinery/core/api.py\", line 217, in process_get\n    mod_res_list = self.transform_res_list(user, [res], request, **kwargs)\n\n  File \"/vagrant/refinery/core/api.py\", line 139, in transform_res_list\n    res_list_unique = res_list.model.__name__\n\nAttributeError: 'list' object has no attribute 'model'\n"}
```

**Comment by flekschas** [comment]
The issue seems to be related to https://github.com/parklab/refinery-platform/blob/develop/refinery/core/api.py#L139.

It looks like this line is related to caching. @scottx611x could you have a look?

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nppQOdjX&#x2F;187-data-import-ui"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Data import UI</a>
