### ISSUE TITLE
Solr Sends back Facets with 0 Counts

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#811]
### Reproduce
1) Locally import or open Data Set 16554: Transcription factor ChIP-seq in expanded human hematopoietic stem and progenitor cells
2) Click on Dataset Browser

### Observed
Under the attribute filter, there are empty facets.
![screen shot 2015-12-07 at 11 38 29 am](https://cloud.githubusercontent.com/assets/9956764/11660895/401bca3a-9d9d-11e5-9d54-e2334d27509b.png)

### Expected
Only facets with nodes.

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SRuCboFt&#x2F;188-attribute-analysis-filter"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Attribute&#x2F;Analysis Filter</a>

**Comment by flekschas** [comment]
After a fresh import I wasn't able to reproduce this error. How about others?

**Comment by jkmarx** [comment]
I'm installing a new instance and will check.

**Comment by jkmarx** [comment]
After starting a new instance, deleting file store, and deleting/reindexing solr the organism part and cell type were cleaned up alone with linger analyses ref #802 
The issue was partly created when I ran vagrant destroy last week through the command line. The command did not completely destroy vagrant (Scott checked through the virtual box gui.) So, we destroyed it through the gui, which worked. Solr needs to be reindexed after running vagrant destroy, which I also did not do last week.

**Comment by scottx611x** [comment]
__Tested with RFC dataset exhibiting this faulty behavior__

__Steps:__
* Delete the dataset via admin interface
* Rebuild solrs index w/ `./manage.py rebuild_index --using=data_set_manager --batch-size=25`
* Reimport the DataSet

__Before:__
![dec 09 2015 09 55](https://cloud.githubusercontent.com/assets/5629547/11689219/e3764e3c-9e5e-11e5-829b-f3c0d971b846.gif)

__After:__
![dec 09 2015 10 18 2](https://cloud.githubusercontent.com/assets/5629547/11689228/edfec94c-9e5e-11e5-9754-9df796e27821.gif)

`0`s seen in the `Type` and `Name` filters are now gone.
__The Steps mentioned above have successfully addressed this issue.__

**Comment by flekschas** [comment]
This is probably caused by the fact that Solr's index is not destroyed when running `vagrant destroy`. To avoid it: either delete the vm completely or rebuild / drop Solr's index.

**Comment by jkmarx** [comment]
@flekschas I agree, should we include it in the wiki somewhere?
