### ISSUE TITLE
Even dataset table rows are transparent 

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#812]
Long facet names not overlayed by the table because it seems like even rows have a transparent background.

![bildschirmfoto 2015-12-08 um 14 42 38](https://cloud.githubusercontent.com/assets/932103/11666391/493bfcbc-9dba-11e5-8bcc-646537dc19d4.png)

**Comment by jkmarx** [comment]
<img width="390" alt="screen shot 2015-12-15 at 12 13 01 pm" src="https://cloud.githubusercontent.com/assets/9956764/11817919/3d648646-a325-11e5-87e9-eda1a09d6266.png">

**Comment by flekschas** [comment]
@jkmarx Sweet!

**Comment by ngehlenborg** [comment]
Better! @jkmarx: But why is the name facet shown at all? Each facet attribute is only associated with one entry in the table.

**Comment by jkmarx** [comment]
@ngehlenborg: We only filtered out attributes with one facet.

**Comment by ngehlenborg** [comment]
The other way around it should be filtered too.
