### ISSUE TITLE
analysis monitoring states not displayed correctly

### ISSUE THREAD

**Issue by ngehlenborg** [parklab/refinery-platform#815]
**Reproduce**
Lauch an analysis with large input files that need to be imported into Galaxy.

**Observed**
Input File Import 
SUCCESS

Execution 
<nothing shown besides and empty box>

Output File Import
PENDING

**Expected**
An explicit state label for "Execution".

States should also be translated into nicer labels, e.g. "Success" and "Pending" rather than using "SUCCESS" and "PENDING".

**Comment by jkmarx** [comment]
Can you put a picture?

**Comment by ngehlenborg** [comment]
Lost the screenshot and when I tried to take it again Execution was already in progress and a percentage was shown on the progress bar.

**Comment by jkmarx** [comment]
Can you specify a dataset? I can do it locally.

**Comment by ngehlenborg** [comment]
Use the file type test and running the WIG file through the 5 step test workflow.

**Comment by ngehlenborg** [comment]
Here is a screenshot. I now see that there is a white "0%" on light gray background in the execution box. Maybe that could be made more visible?

<img width="1434" alt="screen shot 2015-12-09 at 10 25 12 pm" src="https://cloud.githubusercontent.com/assets/1216518/11717814/c3452f6c-9f20-11e5-8946-140cea0dec6d.png">

**Comment by jkmarx** [comment]
Oh okay, that makes more sense. I'll fix it.

**Comment by jkmarx** [comment]
<img width="1117" alt="screen shot 2015-12-11 at 10 49 37 am" src="https://cloud.githubusercontent.com/assets/9956764/11748157/ea37a97c-9ff4-11e5-92a2-53233a6b72c6.png">
<img width="1047" alt="screen shot 2015-12-11 at 10 49 13 am" src="https://cloud.githubusercontent.com/assets/9956764/11748158/ea3e5060-9ff4-11e5-9604-f8f577f5646b.png">

**Comment by ngehlenborg** [comment]
Looking great. Can be closed.

**Comment by jkmarx** [comment]
Commit dcfbaae1ab7aa04bf000a9cc3f90c3141e393c03 referenced above closed this issue.
