### ISSUE TITLE
Add Tooltip for Filedown Icon and Lightening Bolt

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#817]
### Minor Enhancement
1) Locally, go to the dataset view for any dataset.

On the dataset view, tooltips show be added for the file download icon and the lightening rod. 

![screen shot 2015-12-10 at 1 00 25 pm](https://cloud.githubusercontent.com/assets/9956764/11723949/0e1be882-9f3f-11e5-9146-0ec2d39e3762.png)

**Comment by scottx611x** [comment]
The Lightning bolt means that a file has not been imported back into refinery

**Comment by scottx611x** [comment]
Wait for #831

**Comment by jkmarx** [comment]
@scottx611x: What should the tooltip say? File download and file not available?

**Comment by jkmarx** [comment]
Or perhaps, Download file and File has not been imported back into refinery.

**Comment by ngehlenborg** [comment]
"Download File (`<filename>`)" and "File not available for download (`<filename>`)"?

**Comment by jkmarx** [comment]
There's not a neat way to grab the filename in this cell template. Can we just stick with "Download File" and "File not available for download"?

**Comment by ngehlenborg** [comment]
Do you have the file URL available for the tooltip?

**Comment by ngehlenborg** [comment]
My motivation for showing the file name is that due to how the table is laid out, it is often not clear what will be downloaded (the name of the file might not even be included in the table).

**Comment by jkmarx** [comment]
Yes, I can include that for download file.
