### ISSUE TITLE
Statistics API is broken

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#820]
Reproduce:
http://192.168.50.50:8000/api/v1/statistics/?format=json&dataset&workflow&project

Expected:
HTTP 200

Observed:
HTTP 400

Error:
```
{"error": "The object '<core.models.ResourceStatistics object at 0x7f3b6dfbbf50>' has an empty attribute 'size_on_disk' and doesn't allow a default or null value."}
```

**Comment by scottx611x** [comment]
Fixed here: c74c923a07cec67621f7e9662220fc3909eb4c3c
