### ISSUE TITLE
Include JS test coverage in codecov

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#821]
https://github.com/codecov/example-node
http://ariya.ofilabs.com/2015/08/javascript-code-coverage-dashboard-with-codecov-io.html

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8xboEZJU&#x2F;190-add-code-coverage-checks-to-ci"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add code coverage checks to CI</a>

**Comment by flekschas** [comment]
Done 1ab44280a051c0eae9911a3e8a525e2598e1061e. See https://codecov.io/github/parklab/refinery-platform
