### ISSUE TITLE
Notify #general Slack Channel of new migrations automatically

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#823]
Probably achievable through the use of Slack's Webhook integration and Github's API:
https://developer.github.com/webhooks/

**Comment by hackdna** [comment]
It's too late to detect a migration when it has already been committed and pushed.

**Comment by scottx611x** [comment]
@hackdna But isn't the idea behind this to let others know of the change?

**Comment by hackdna** [comment]
Yes, we need to communicate to the team *before* we commit and push a migration. Otherwise, time will be wasted on rolling back an re-applying.
