### ISSUE TITLE
AWS deployment should use RDS

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#835]
The current AWS deployment uses a PostgreSQL database that is on the same instance (as the main web app). Terminating it destroys the database.

Generally, we would like the database to be persisted. So that means a separate database, so we're intending to use RDS.

Persisting the filestore is #837

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sBJxolm4&#x2F;195-implement-deployment-to-aws-using-ebs-and-rds"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement deployment to AWS using EBS and RDS</a>

**Comment by drj11** [comment]
TODOs;
- [ ] allow RDS password to be specified as cloudformation parameter (fixed to `mypassword` currently)
- [ ] share RDS `refinery` user password between puppet/django config and `bin/ensure-postgresql-role`

**Comment by drj11** [comment]
TODO

- [ ] add the Neo4j stuff which was in `config.json.sample` but has gone missing in the new `config.json.erb`
