### ISSUE TITLE
AWS deployment should use a separate EBS volume

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#837]
(Long term is S3 or similar, but the interim solution) is for the AWS deployment to attach an instance to a pre-existing EBS that will persist when the instance is created.

(see #835 for database persistence)

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sBJxolm4&#x2F;195-implement-deployment-to-aws-using-ebs-and-rds"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement deployment to AWS using EBS and RDS</a>

**Comment by drj11** [comment]
- [ ] connect to existing EBS
- [ ] cloudformation template to create EBS
- [ ] attach EBS to instance
- [ ] formation filesystem on EBS
- [ ] mount somewhere (where we do mount it?)
- [ ] configure django to find mounted EBS.

**Comment by hackdna** [comment]
@drj11: Refinery data file storage location (Django setting `MEDIA_ROOT`) is set in [config.json](https://github.com/parklab/refinery-platform/blob/develop/refinery/config/config.json.sample#L44).
