### ISSUE TITLE
Enable tagging of all AWS resources during deployment

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#839]
Tags should be added automatically to all resources in the stack.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html
http://cloud.huit.harvard.edu/financial-management-amazon-web-services-accounts#appendix

Proposed scheme:
owner=drj11
department=dbmi
environment=dev
project=scc
product=refinery
subproduct=galaxy|platform

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sBJxolm4&#x2F;195-implement-deployment-to-aws-using-ebs-and-rds"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement deployment to AWS using EBS and RDS</a>

**Comment by drj11** [comment]
This is now working on a branch (soon to be a PR!). It looks like this:

![tags](https://cloud.githubusercontent.com/assets/1215412/12918494/6145ce42-cf37-11e5-92ea-fc9269de949a.png)

**Comment by hackdna** [comment]
Great. We probably don't need the 'subproduct' tag.

**Comment by drj11** [comment]
can argue about exactly which tags we do/don't need in another issue. Easy to change, just add stuff in `aws-tags` directory. The set of tags is likely to change according to AWS account holder anyway.
