### ISSUE TITLE
Handle Analysis deletion properly

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#840]
- [x] Delete `Investigations` and all related objects associated with an `Analysis`
- [x] Delete the `Analysis` but:
* First, list all Nodes created by said `Analysis` via `Node.analysis_uuid`
    * check if any of these `Nodes` were analyzed further by seeing if there are any `AnalysisNodeconnections` assosciated with the `Node` that have the `direction ==  "input"`
    * if none of the `Nodes` have the `direction ==  "input"` go ahead and delete
- [x] Alternatively, delete the `Analysis` if none of the `Nodes` has an `AnalysisNodeConnection`

![image](https://cloud.githubusercontent.com/assets/5629547/12150563/7aefeaaa-b478-11e5-90b5-cb15186fa9a0.png)

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BAQUtRRE&#x2F;179-removing-related-db-objects"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Removing related Db Objects</a>

**Comment by jkmarx** [comment]
Issue #306

**Comment by scottx611x** [comment]
__Functionality after commit:__ a399146ac5f9c45a6bf6f3b377b9691da66cc891

```
Analysis.objects.get(id=14).delete()
2016-01-26 08:58:25 ERROR    core.models:1682 analysis_deletion_check() - Cannot delete Analysis: Test workflow: 5 steps without branching 2016-1-26@8:53:45 - admin - None provided. because one or  more of it's Nodes have been further analyzed
```
![screen shot 2016-01-26 at 8 59 49 am](https://cloud.githubusercontent.com/assets/5629547/12582451/3498b328-c40b-11e5-819d-8283eabc716f.png)
