### ISSUE TITLE
Celery looses worker when the os runs low on memory

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#842]
When importing larger ISA-Tabs I notice that Celery often looses workers:

```
WorkerLostError: Worker exited prematurely.
```

The problem is clearly related to memory issues as even bash runs out of memory sometimes:

```
bash: fork: Cannot allocate memory
```

I looked at the distribution of memory consumption via `ps aux --sort -rss`:

```
neo4j     1213  1.9 17.1 2135440 523080 ?      Sl   15:23   2:38 /usr/bin/java -cp /var/lib/neo4j/lib/commons-lang3-3.3.2.jar:/var/lib/neo4j/lib/concurrentlinkedhashmap-lru-1.4.2.jar:/var/lib/neo4j/lib/jline-2.12.jar:/var/lib/neo4j/lib/l
vagrant   3614  2.3 16.3 652888 501292 ?       S    15:30   2:57 python /vagrant/refinery/manage.py celeryd -c 4 -Q celery --events
vagrant   2846 19.9 16.1 1476876 492452 ?      Sl   15:23  26:57 java -server -Xss256k -Xms512m -Xmx512m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -X
vagrant   3613  2.0 10.1 461728 309252 ?       R    15:30   2:41 python /vagrant/refinery/manage.py celeryd -c 4 -Q celery --events
vagrant   3615  1.7  9.9 456824 304936 ?       R    15:30   2:15 python /vagrant/refinery/manage.py celeryd -c 4 -Q celery --events
```

Next I checked Celery's log files and it seems that supervisor assumes that the server has crashed because the DB actually closed the connection:

```
[2016-01-08 21:30:51,012: ERROR/MainProcess] Thread 'Supervisor' crashed: DatabaseError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
...
DatabaseError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Finally, the imports successfully keep on running and `WorkerLostError` also happens when memory is still available. After the last crash `free -m` reported:

```
             total       used       free     shared    buffers     cached
Mem:          2985       2510        475        139         22        471
-/+ buffers/cache:       2016        969
Swap:            0          0          0
```

and `ps aux --sort -rss`:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
vagrant   7113  3.1 28.6 1085612 875604 ?      S    17:59   7:39 python /vagrant/refinery/manage.py celeryd -c 4 -Q celery --events
vagrant   2846 20.6 16.5 1480736 506080 ?      Sl   15:23  81:30 java -server -Xss256k -Xms512m -Xmx512m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -X
vagrant   3583  0.4  5.3 371496 162352 ?       Sl   15:30   1:39 python /vagrant/refinery/manage.py celerycam
postgres 11225  5.3  4.6 257548 142024 ?       Ss   21:16   2:16 postgres: vagrant refinery [local] idle in transaction                                                                      
postgres  1052  0.0  4.3 246712 133432 ?       Ss   15:23   0:12 postgres: checkpointer process                                                                                              
postgres  1053  0.0  3.5 246452 108252 ?       Ss   15:23   0:05 postgres: writer process
```

I booted the VM with 3 GB RAM and imported 25 ISA-Tabs of a total size of 2.2 MB.

I believe that while the memory consumption is high, the problem that causes the `WorkerLostError` error must be related to something different because Celery will actually finish executing all tasks without any further problems. Comparing the first and second output of `ps aux --sort -rss` indicates that two of the three Celery processes died. Could the issue be related to having multiple instances running at the same time?

**Comment by flekschas** [comment]
I can confirm that `WorkerLostError` which is caused by `DatabaseError: server closed the connection unexpectedly` is not related to the import size. I can reproduce this error with the MetaboLight ISA-Tab: **MTBLS1**, which is only 176 KB.

[MTBLS1.zip](https://github.com/parklab/refinery-platform/files/83810/MTBLS1.zip)

**Comment by flekschas** [comment]
There must be a memory leak somewhere in our import process for certain ISA-Tabs. Before import that single ISA-Tab mentioned above my VM had about 1.3 GB of free memory. It constantly went down while the memory consumption of Celery went up. Solr's 

Here's another snapshot before executing the import:

```

```

And shortly before the worker got lost when Postgres crashed because of low memory:

```
vagrant   4202 17.5 43.0 1468336 1315632 ?     S    14:33   3:04 python /vagrant/refinery/manage.py celeryd -c 4 -Q celery --events
neo4j     1210  3.5 14.1 2133644 433988 ?      Sl   14:04   1:37 /usr/bin/java -cp /var/lib/neo4j/lib/commons-lang3-3.3.2.jar:/var/lib/neo4j/lib/concurrentlinkedhashmap-lru-1.4.2.jar:/var/lib/neo4j/lib/jline-2.12.jar:/var/lib/neo4j/lib/
vagrant   2965  5.2 13.8 1482988 424724 ?      Sl   14:05   2:23 java -server -Xss256k -Xms512m -Xmx512m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -
postgres  4549 49.4  4.7 257428 145660 ?       Rs   14:40   5:10 postgres: vagrant refinery [local] INSERT                                                                                   
postgres  1050  0.3  4.5 246672 139420 ?       Ss   14:04   0:09 postgres: checkpointer process        
```

I tested in in `DEBUG=TRUE` and `DEBUG=FALSE`.

**Comment by flekschas** [comment]
I was able to solve the `WorkerLostError` by using the `librabbitmq` library. The library is suppose to be more performant than the build in `amqplib` and the setup is simple: `pip install librabbitmq && supervisorctl restart all`. Afterwards Celery's memory usage remained stable at only ~5%.

While nothing is crashing anymore, I notice that something must goes wrong given certain ISA-Tabs. The import process was running for over 90mins until I cancelled it. Postgres was most active with ~50-60% CPU usage after Celery with ~20-30%. Could it be that the import process queries DBs on non-index tables or joins tables on a property that's not properly index?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uPviGMWp&#x2F;199-improve-data-model-of-data-sets"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Improve data model of data sets</a>
