### ISSUE TITLE
Statistics Page Fix CSS Layout

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#850]
There should be spacing between the column wells. 
<img width="1421" alt="screen shot 2016-01-14 at 1 49 47 pm" src="https://cloud.githubusercontent.com/assets/9956764/12334033/b97cc9ac-bac5-11e5-994e-bac93eda9d48.png">

**Comment by scottx611x** [comment]
Fixed with commit: 86f83ff95880f9d6037a9251e148494cc96e045a
![screen shot 2016-02-03 at 3 04 49 pm](https://cloud.githubusercontent.com/assets/5629547/12795347/a0db4d02-ca87-11e5-9a20-2182decd0f07.png)
