### ISSUE TITLE
Fix Current_Commit in production

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#857]
The most recent Github commit hash is available to users on the About page in development mode, but not in production.

__Production:__
![screen shot 2016-01-26 at 11 26 28 am](https://cloud.githubusercontent.com/assets/5629547/12586790/ac838c5a-c41f-11e5-93c1-4c7af63ce988.png)

__Development:__
![screen shot 2016-01-26 at 11 26 13 am](https://cloud.githubusercontent.com/assets/5629547/12586796/b475822e-c41f-11e5-88a8-4d1ee8c0c470.png)

**Comment by hackdna** [comment]
Why not just reopen #741?
