### ISSUE TITLE
On AWS, choice of SSH keys is fixed

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#859]
As @hackdna points out in https://github.com/parklab/refinery-platform/pull/858#issuecomment-175982585: «key pair name is hardcoded to "id_rsa" (should be able to specify on the command line)»

We should be able to specify any key; specifying keys via named AWS key_pairs is one way.

Another way (that I've used in the past) is to specify a list of github users, and have the CloudInit script fetch the public key from github and install it in `~/.ssh/authorized_keys`. (your github public keys are publicly available via the API: for example, see https://api.github.com/users/drj11/keys).

For now, I don't think it's a big issue.

**Comment by drj11** [comment]
in any case, change to use key name `refinery`; first fixed to that, then defaulting to that.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SFCnJTHf&#x2F;218-2016-02-17-cloud-meeting-action-items"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 2016-02-17 Cloud Meeting Action Items</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-deploy-scc-release-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> deploy SCC release on AWS</a>

**Comment by drj11** [comment]
A small part: You can now specify a different Key Pair if desired: https://github.com/parklab/refinery-platform/pull/1102

**Comment by hackdna** [comment]
Could you update the deployment docs with this info?

**Comment by drj11** [comment]
edited https://github.com/parklab/refinery-platform/wiki/AWS-installation to add the config.
