### ISSUE TITLE
Provide Deletion controls for DataSets and Analyses

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#866]
This issue has brought back to the forefront based on our user's feedback. 

- [x] Make sure `deletion_checks` from https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L1994 is still picked up

**Datasets:**
- [x] Delete button w/ confirmation dialog on Launchpad

**Analyses:**
- [x] Delete button w/ confirmation dialog Launchpad

**Workflows: (On hold)**
~~- [ ] Choice of disabling/deleting workflow w/ confirmation dialog~~
~~- [ ] Be able to make disabled ones active again i.e. have them persist in view~~
~~- [ ] Be able to import workflows into galaxy~~

- [x] Properly handle object permissions on FE
- [x] Leverage testing framework introduced by @mccalluc for these intereactions
- [x] Update back-end tests if necessary (Double check existance of tests for deletions of analyses on derived data)

**Example:**

![wf_ui](https://cloud.githubusercontent.com/assets/5629547/12795766/9c93521a-ca89-11e5-84d8-ca0944e5daf1.gif)

**Comment by ngehlenborg** [comment]
An important thing to keep in mind here:  we need to check permissions on all of those objects before deleting them, e.g., only admins should be allowed to delete workflows (or owners of Galaxy instances once we get there). 

For admins "hidden" workflows could be shown on demand in a different style or a separate section of the list.

**Comment by hackdna** [comment]
Users should be able to delete downstream analyses when deleting the corresponding data sets. An appropriate warning/conformation message should be displayed.

**Comment by scottx611x** [comment]
closed per #1445
