### ISSUE TITLE
The AWS EC2 instance root volume (EBS) does not get tagged

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#875]
When using cloudformation to create the `web-refinery` EC2 instance, an associated EBS instance gets created for the root volume. This root EBS does not get tagged with the tags that we specify (see https://github.com/parklab/refinery-platform/issues/839 for tagging).

**Comment by drj11** [comment]
Possible approaches:

- get the instance to tag its root volume (that approach is suggested here and there are implementation hints: http://stackoverflow.com/questions/24026425/is-there-a-way-to-tag-a-root-volume-when-initializing-from-the-cloudformation-te )
- use an instance type that has instance storage and use the instance storage for the root volume (do we have to change AMI for that?)

**Comment by drj11** [comment]
The EC2 instance types that support instance storage are limited and I very much get the impression that they are phasing out instance storage for the general purpose instance types. For example, the `m3` series have instance storage, but not the newer `m4` series.

So we'll have to tag the root volume after the instance starts.

**Comment by drj11** [comment]
For now try using instance storage as an interim.

**Comment by ngehlenborg** [comment]
Closed via #1037.
