### ISSUE TITLE
Analysis Monitoring -- Add flag when backend pauses 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#876]
## Observed
Currently, the front end goes to a default PENDING when the backend (galaxy/celery) pauses.
## Enhancement
Instead, the front end should display current information with a flag indicator. The indicator will inform the backend has paused. (Tooltip or plain text info?)

**Comment by ngehlenborg** [comment]
I think a tool tip linked to the warning indicator is sufficient. 

Maybe use http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/ for the warning?

**Comment by jkmarx** [comment]
@ngehlenborg @hackdna What should the tooltip says? {{stage}} has paused. or API has stalled, please wait for update. or.......?

**Comment by ngehlenborg** [comment]
@hackdna: when this happens, what are possible causes?

**Comment by hackdna** [comment]
Galaxy status update requests fail for whatever reason.

**Comment by ngehlenborg** [comment]
Ok, then the status message should reflect that. What do you think about "Unable to obtain status updates from Galaxy analysis backend?"

**Comment by hackdna** [comment]
Sounds good to me but would it make sense to our (non-technical) users?

**Comment by ngehlenborg** [comment]
What would make sense?

**Comment by hackdna** [comment]
Something like "Galaxy analysis status unknown"? Whatever we choose, we should later ask our users if it makes sense to them.

**Comment by jkmarx** [comment]
#889
