### ISSUE TITLE
Assign a name to Refinery EC2 instance using CloudFormation

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#887]
For easy identification in the AWS console (e.g., refinery-web-stack-name)

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SFCnJTHf&#x2F;218-2016-02-17-cloud-meeting-action-items"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> 2016-02-17 Cloud Meeting Action Items</a>

**Comment by drj11** [comment]
@ilya suggests that to change the name you need to create a tag called name.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>

**Comment by drj11** [comment]
as per http://stackoverflow.com/questions/15260263/name-an-ec2-instance-in-the-cloudformation-template#15629546

**Comment by drj11** [comment]
![awsname](https://cloud.githubusercontent.com/assets/1215412/14673696/617d8e20-06f7-11e6-8769-1921195b8388.png)

Well, that didn't work.

Oh, maybe it needs to be `Name`, not `name` (case sensitive).

**Comment by drj11** [comment]
Edited by hand, `Name` works.
