### ISSUE TITLE
Consolidate AWS deployment configuration files

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#888]
Currently, some values are hardcoded in `10default.yaml` and some are provided in `50local.yaml`. Having a single file is easier than several. It should be initialized from a template like 50local.yaml.template is now. For example, create `aws.yaml.sample` with some default values to be used to create `aws.yaml` (and add `aws.yaml` to `.gitignore` along with other JSON files).

Make sure `SITE_NAME` and `SITE_URL` are not hardcoded.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>

**Comment by hackdna** [comment]
We should also be able to specify EBS data volume size via the consolidated config file (instead of being [hardcoded](https://github.com/parklab/refinery-platform/blob/develop/deployment/stack.py#L144)).

**Comment by hackdna** [comment]
Also, add `REFINERY_URL_SCHEME` setting to the consolidated config file.

**Comment by ngehlenborg** [comment]
Closed via #1130.
