### ISSUE TITLE
Unknown or running analysis page doesn't contain any files

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#893]
Reproduce:
1. start an analysis that turns into unknown by shutting down galaxy (unknown === connection lost)
2. click on that analysis on the dashboard
3. go back to the files tab

observe:
"0 out of XYZ" files selected, i.e. no files shown. logically this makes sense since the analysis didn't produce any new files but it is confusing as there is no indicator as to when a user sees data set analysis files or just the data set's files.
It is possible to display the original files again by expanding the analysis filter and explicitly clicking on N/A.

expected:
Either show all files and highlight analysis related files or add some other kind of indicator that pops out and tells the user that he/she is **only** seeing empty analysis files.

below is a screenshot of an empty data set analysis files tab:
![bildschirmfoto 2016-02-18 um 18 29 47](https://cloud.githubusercontent.com/assets/932103/13161726/9b81c3e4-d66d-11e5-83d8-9861bc0d5765.png)
the only difference to a normal data set file tab is that the URL contains the unknown analysis' UUID.

**Comment by jkmarx** [comment]
This is no longer an issue, since we do not link to the analysis page for failed and unknown analyses.
