### ISSUE TITLE
Analysis Monitor State Does Not Update after Galaxy Pauses

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#894]
### Reproduce
1) Locally, run an analysis, RFC with the test workflow.
2) Once in the galaxyAnalysis stage, shut down galaxy.
3) Check the UI, it should update to the unknown state
4) Restart galaxy

### Observed
The overrall state stays as unknown.
For the uncompleted states, they stay as PENDING even though they are progressing.
After completion, overrall state stays as UNKNOWN.
Individual states do switch to SUCCESS once completed.

### Expected
The overrall state to update to RUNNING and the individual states switch to PROGRESS.
After completion, the overrall should switch to SUCCESS.

**Comment by hackdna** [comment]
Do we actually need the `overall` state? It simply duplicates the information already present in the states of the stages.

**Comment by jkmarx** [comment]
analysis status == analysis monitor overrall,  Currently the analysis status is being used by the front end, and overrall is not. But, analysis status is also not getting updated...which should be resolved if we remove overrall.

**Comment by hackdna** [comment]
Yes, so should we get rid of the analysis status to avoid potential conflicts as described in this ticket?

**Comment by jkmarx** [comment]
Keep analysis status and update it correctly. Get rid of the overrall if you'd prefer.

**Comment by hackdna** [comment]
We know the drawbacks of keeping it. What would be the benefits?

**Comment by jkmarx** [comment]
Overrall is currently not used by the front end.

**Comment by hackdna** [comment]
To summarize the discussion we had this morning: remove status field from the Analysis model, merge AnalysisStatus model into Analysis model, compute overall analysis status on the fly and return as part of the Analysis API.

**Comment by ngehlenborg** [comment]
Plan is to create a v2 API using DRF and to switch the UI once @jkmarx has time to address it.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EP5RcYzl&#x2F;250-avoid-marking-analysis-as-failed-if-galaxy-temporarily-goes-down-during-workflow-execution"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> avoid marking analysis as failed if galaxy temporarily goes down during workflow execution</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-deploy-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> deploy SCC release on AWS</a>

**Comment by scottx611x** [comment]
- [x] Make general overview of potential side effects/ changes that need to be made
- [ ] Try to reproduce the issue
- [ ] Look into exact cause of bug once connection to galaxy is lost and see if there is a better fix
- [ ] Merge of `AnalysisStatus` into `Analysis` model
- [ ] Compute the `overall_status` with a new DRF api based on status of indv. `Analysis` stages
- [ ] Use computed `overall status` to filter out `analyses` through new api

**Comment by scottx611x** [comment]
**Testing this issue in the cloud:**

- [x] Try to run analyses, shutdown galaxy to simulate lost connection, then bring galaxy back up.
- [x] Analyses should not fail, they should stay in the unknown state until galaxy can be reached again.
- [ ] The overall `UNKNOWN` state for the analyses should revert to `PROGRESS` once galaxy can be reached

**Comment by hackdna** [comment]
Yes but I think you only need to update history state to PROGRESS if Galaxy responded and analysis hasn't finished running yet, so that code should go to [line 157](https://github.com/parklab/refinery-platform/blob/develop/refinery/analysis_manager/tasks.py#L157).

**Comment by scottx611x** [comment]
Great @hackdna thanks.

Here's the functionality after the mentioned change:

![may-02-2016 13-24-45](https://cloud.githubusercontent.com/assets/5629547/14961777/74798a3a-1069-11e6-8a51-98bb7e88955f.gif)

**Comment by scottx611x** [comment]
This has been addressed as of commit: 210f465180d59be651406d0087459e45cb45b98e
