### ISSUE TITLE
Create Test Dataset with Multiple Studies and Assays

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#895]
For the data set Ph II updates, the UI enhancements require a test dataset with multiple studies and multiple assays. Ref #299

**Comment by ngehlenborg** [comment]
We can find some at Nature Scientific Data or from the ISA-Tab website (sample data sets).

**Comment by ngehlenborg** [comment]
You might be able to find some here: http://scientificdata.isa-explorer.org

**Comment by jkmarx** [comment]
http://encode-x.med.harvard.edu/data_sets/f6119f1e-77b1-11e2-9326-005056a0073d/

**Comment by ngehlenborg** [comment]
Must have been a misunderstanding - that data set has only 1 assay and 1 study (it was imported from a tab-delimited text file).

**Comment by jkmarx** [comment]
http://www.isa-tools.org/

**Comment by ngehlenborg** [comment]
@jkmarx: Here are example files provided by the ISA-Tab team: http://www.isa-tools.org/format/examples/

**Comment by ngehlenborg** [comment]
I downloaded the following two ISA archives from http://www.isa-tools.org/format/examples:

[BII-S-1_BII-S-2.zip](https://github.com/parklab/refinery-platform/files/215493/BII-S-1_BII-S-2.zip)
[BII-S-3.zip](https://github.com/parklab/refinery-platform/files/215494/BII-S-3.zip)

The first one has two studies with multiple assays each and the second one has one study with multiple assays.
