### ISSUE TITLE
Recreate Data Set Table in Angular

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#897]
- [x] Create route for new data set browser views
- [x] Recreate the data set table in angular with ui-grid
- [ ]~~Add dynamic scrolling wrapper~~ _Moved to separate issue_
- [x] Add assay_uuid to request
- [x] Add selection capabilities
- [x] Unit Test

**Comment by ngehlenborg** [comment]
Going forward, it would be helpful if the table could responsive and switch to a different layout when the available space is narrower than some predefined width (e.g. using an approach like this one: http://codepen.io/geoffyuen/pen/FCBEg)

**Comment by jkmarx** [comment]
http://stackoverflow.com/questions/25635196/is-it-possible-to-make-ng-grid-responsive
Seems doable.

**Comment by jkmarx** [comment]
http://ui-grid.info/docs/#/tutorial/108_hidden_grids
