### ISSUE TITLE
Registration emails link to wrong URL (on AWS at least)

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#900]
As noted here https://github.com/parklab/refinery-platform/pull/899#issuecomment-187725847, the activation URL that appears in registration emails is wrong.

**Comment by drj11** [comment]
Can we discover our own IP address and/or domain?

**Comment by ngehlenborg** [comment]
Should be a variable that the user/admin provides during setup. Needs to be stored in the `Site` model "Domain Name". Currently this is handled via the `init_refinery` management command, which gets the value via a command line argument (via @hackdna). Puppet manifest has IP address and port used for Vagrant. Creates instance of a `Site` model.
