### ISSUE TITLE
Exploration tool throws an error when the returned number of nodes is zero

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#920]
When `http://192.168.50.50:8000/neo4j/annotations` returns an empty node array the exploration tool fails. This should not be the case. The tool should simple not be loaded at all.

@scottx611x Could you attach the error you've seen after clicking on _Exploration_?

**Comment by scottx611x** [comment]
![screen shot 2016-03-02 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/5629547/13470523/8de96cde-e07a-11e5-9b97-32af359c74e0.png)

**Comment by flekschas** [comment]
@scottx611x Could you test this when you're free? d5605c55ab25b316e4e49abce292d7a5a74d3c16 should address the error. You should see a message now tell you that no data is available.
