### ISSUE TITLE
Configure availability zone at runtime

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#926]
Currently `us-east-1b` is hardcoded: https://github.com/parklab/refinery-platform/blob/develop/deployment/volume_cfn.py#L31

This AZ is not available in our AWS account:
![screenshot 2016-03-04 12 34 56](https://cloud.githubusercontent.com/assets/452575/13535311/818213ea-e207-11e5-99e2-5e2929271a0d.png)

This results in failure to create the volume stack:
![screenshot 2016-03-04 12 50 22](https://cloud.githubusercontent.com/assets/452575/13535354/b47e46ce-e207-11e5-9a21-b1b47e2946db.png)

**Comment by drj11** [comment]
That's... entertaining. I knew that the actual availability zones are mapped to zone identifiers in a different way for each account (my `us-east-1a` is not your `us-east-1a`), but I didn't know the list of identifiers could be different.

But the documentation does indeed say that: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones

We'll probably need to use the `describe-availability-zones` command: http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-availability-zones.html

**Comment by hackdna** [comment]
Should we also make this optionally user-configurable (like [Cloud Launch](https://launch.usegalaxy.org/launch) does in advanced settings)?

**Comment by drj11** [comment]
yes probably. I don't think that is so urgent though.

**Comment by hackdna** [comment]
I think we would need this for re-launching Refinery (given an existing EBS volume).

**Comment by drj11** [comment]
We already take measures to make sure the EC2 instance is launched in the same availability zone as the volume. https://github.com/parklab/refinery-platform/pull/881
