### ISSUE TITLE
URLs for downloading analysis results are incorrect on AWS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#927]
Commit 0b896f6.

## Steps to reproduce
Run an analysis

## Observed results
URLs for analysis results are of the form: `http://192.168.50.50:8000/media/file_store/38/6e/1_MACS2_plot.pdf`

## Expected results
Analysis result URLs should contain the actual IP address or host name instead of `192.168.50.50:8000`

**Comment by drj11** [comment]
While this isn't the same bug as #900, I very much hope that it has the same underlying cause as #900

**Comment by ngehlenborg** [comment]
Make download URLs relative.

**Comment by drj11** [comment]
So I think the discussion in the meeting was that the front-end was constructing full absolute URLs and it should not be, as @ngehlenborg says.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-for-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare for SCC demo on AWS</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>
