### ISSUE TITLE
Apache is not configured to serve files from MEDIA_ROOT on AWS

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#928]
From `/etc/apache2/sites-enabled/001-refinery.conf`:
```
<Directory /srv/refinery-platform/media>
    Order deny,allow
    Require all granted
</Directory>
```
This should be set to `/data/media` for AWS deployments.
Also, `Alias /media/ /srv/refinery-platform/media/` needs to be updated accordingly.

**Comment by drj11** [comment]
There are probably a bunch of these, because I haven't actually used refinery much.

**Comment by drj11** [comment]
What's the user visible bug? (that is, how would I test that the end result was successful?)

**Comment by hackdna** [comment]
The easiest way might be to import a [data set](http://stemcellcommons.org/sites/default/files/isa/isa_13880_954189.zip) by providing the URL (`http://<hostname>/data_set_manager/import/`) then check if you can download the imported zip archive in the Django admin (`http://<hostname>/admin/file_store/filestoreitem/`).
