### ISSUE TITLE
Update built-in accounts for AWS deployment

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#932]
Currently, `guest` and `admin` accounts are created with well known passwords which is a problem when deploying on AWS.

One way to solve it would be to configure `admin` account password during deployment and either not create the `guest` account or create it in inactive state.

`admin` account is created here: https://github.com/parklab/refinery-platform/blob/develop/refinery/core/fixtures/superuser.json

`guest` account is created here: https://github.com/parklab/refinery-platform/blob/develop/deployment/refinery-modules/refinery/manifests/init.pp#L115

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8OLy1xSF&#x2F;234-update-built-in-accounts-for-aws-deployment"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update built-in accounts for AWS deployment</a>

**Comment by drj11** [comment]
Can create a hashed password using `make_password` https://docs.djangoproject.com/en/1.9/topics/auth/passwords/#django.contrib.auth.hashers.make_password

**Comment by drj11** [comment]
there is a PR to deactivate the guest account: https://github.com/parklab/refinery-platform/pull/979

**Comment by hackdna** [comment]
Tested 401e979. Vagrant provisioning worked in both existing and brand new VMs. Deployment to AWS failed:
![screenshot 2016-03-22 16 53 04](https://cloud.githubusercontent.com/assets/452575/13967631/a251dc0e-f04e-11e5-8ccf-65ecdf12986d.png)
```
(refinery-platform)ubuntu@ip-172-31-40-147:/srv/refinery-platform/refinery$ supervisorctl status
http://localhost:9001 refused connection
```

**Comment by drj11** [comment]
@ilya mystifying

**Comment by hackdna** [comment]
You can't reproduce the problem?

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-for-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare for SCC demo on AWS</a>

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0dqHQzfq&#x2F;34-prepare-scc-demo-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> prepare SCC demo on AWS</a>

**Comment by scottx611x** [comment]
Tested on: 78236f11a40b3be4911b046ba372d40d6ef67593

User :`admin` has password that I configured, and User:`guest` is `inactive`
