### ISSUE TITLE
Supervisor is not starting automatically during AWS deployment

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#933]
## Steps to reproduce
Spin up a Refinery stack

## Observed results
Supervisor is not running

## Expected results
Supervisor is running as well as all its services

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uGTokZN9&#x2F;225-troubleshoot-supervisord-not-starting-automatically-during-provisioning-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Troubleshoot supervisord not starting automatically during provisioning on AWS</a>

**Comment by drj11** [comment]
PR: https://github.com/parklab/refinery-platform/pull/937

**Comment by drj11** [comment]
Basically the same as #923
