### ISSUE TITLE
Dashboard workflow loading animation seems to be linked to the data set loading.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#934]
I am currently having no workflows in my VM and the _info_ panel is shown immediately but the loading animation keeps animating until all datasets have been loaded while it should stop as soon as all workflows have been loaded.

**Comment by jkmarx** [comment]
On the beta site, this issues is resolved. 
![workflow_indicator](https://cloud.githubusercontent.com/assets/9956764/19904914/06c43964-a04b-11e6-8dff-fa460fa8f298.gif)
