### ISSUE TITLE
Refactor and angularize full-height panels

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#935]
Currently panels are _stretched_ to their full height using jQuery on a global scale (see base.html). This works fine as long as no other part needs to update the height. A problem arises once we want to set different heights because the code can't be controlled by our Angular app.

**Suggestion:**
Create a common Angular directive that sets is able to manage a panel's height. This way we could add more functionality easily (like zeroing or halving the height to show two containers in one panel.)

**Comment by ngehlenborg** [comment]
:+1:

**Comment by flekschas** [comment]
It's basically done with 9bbd6c7dcf40f8253b745a772e587d33becab8a7. I just need to document how to use it. (And merge the branch)

**Comment by flekschas** [comment]
Can be closed because the commit 9bbd6c7dcf40f8253b745a772e587d33becab8a7 has been merged some time ago.
