### ISSUE TITLE
Data set page: columns appear twice

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#959]
For [13086: DNA methylation dynamics during in vivo differentiation of blood and skin stem cells (Part 2: Microarray)](https://refinery-dev.stemcellcommons.org/data_sets/74663672-525c-4adc-abee-74069d65560b/#/files/browse) the column _Cell Type_ appears twice in the data file table.

![bildschirmfoto 2016-03-15 um 20 42 43](https://cloud.githubusercontent.com/assets/932103/13798623/c3116b90-eaee-11e5-8532-f3e0cae95800.png)

**Comment by jkmarx** [comment]
https://github.com/parklab/refinery-platform/issues/446

**Comment by flekschas** [comment]
Yes it's very likely a duplicate. Thanks for figuring out.
