### ISSUE TITLE
Update to AngularJS 1.5.x

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#986]
After some time of testing the first bug fix releases for AngularJS 1.5 are out. I think we can safely look into updating. Angular 1.5 should allow us to gracefully upgrade the UI to get ready for Angular 2.0 which might get released later this year.

**Comment by flekschas** [comment]
Tested Angular 1.5.5 and everything seems to just work fine. Only _ui-grid_ still seems to love Angular 1.4. According to https://github.com/angular-ui/ui-grid/issues/5070 it should just work but someone might have found a bug. We could wait until _ui-grid_ officially supports Angular 1.5.x but what confuses me is that they depend this on dropping support for 1.3 presumably.

**Comment by timothyswt** [comment]
This might be due to bugs in ng-bind-html or $compile that were fixed in 1.5.6 i am hearing reports that 1.5.6 and above works.

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;v2qPcFwx&#x2F;42-986"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #986</a>
