### ISSUE TITLE
grunt test --host fatel error

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#988]
## Reproduce
On the develop branch, in the command line switch to host machine.
Type: grunt test --host

## Observe
<img width="1043" alt="screen shot 2016-04-01 at 10 48 37 am" src="https://cloud.githubusercontent.com/assets/9956764/14210521/519ae282-f7f7-11e5-981d-72e5e311e901.png">

## Expected
UI Test suite to run for Chrome, Firefox, and Safari 

In gruntfile:
<img width="573" alt="screen shot 2016-04-01 at 10 49 32 am" src="https://cloud.githubusercontent.com/assets/9956764/14210547/78600820-f7f7-11e5-8cf6-15679649dd26.png">

**Comment by hackdna** [comment]
"A bug report should include the commit hash in which the problem was discovered"
https://github.com/parklab/refinery-platform/wiki/Tracking-Issues-with-the-Github-Issue-Tracker
Also, we shouldn't use screenshots for text since image content is not searchable.
