### ISSUE TITLE
Invitation API is broken and UI doesn't reflect that error

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#998]
Commit: Any commit equal to or newer than https://refinery-dev.stemcellcommons.org/collaboration

### Steps to reproduce
1. Go to _Collaboration_
2. Click on a group and click on plus in the members panel.
3. Add whatever email and click on invite.

### Observed behavior
The popup states that "Invitation succesfully sent to test@test.de" but the console shows that http://192.168.50.50:8000/api/v1/invitations/?format=json&group_id=XYZ is throwing a 500 error.

### Expected behavior
The error should be caught and an appropriate message should be shown.

This endpoint is throwing different 500 errors:

1. GET http://192.168.50.50:8000/api/v1/invitations/?format=json&group_id=XYZ is related to "TypeError: can't subtract offset-naive and offset-aware datetimes".

**Comment by hackdna** [comment]
Commit doesn't have to be the one where the bug was introduced but the one where it can be reproduced.
